export const fases = [
  { id: 0, titulo: "Herramientas del proyecto", descripcion: "Gestores de paquetes, package.json, semver, scripts, lockfiles y estructura del proyecto.", icono: "wrench" },
  { id: 1, titulo: "Cimientos de JS en el servidor", descripcion: "Modularización, asincronía, Node.js, event loop y módulos nativos.", icono: "cube" },
  { id: 2, titulo: "Red y servidor nativo", descripcion: "Ciclo Request-Response, cabeceras, servidor con node:http y códigos de estado.", icono: "globe" },
  { id: 3, titulo: "Express.js", descripcion: "Enrutamiento, middlewares, motor de plantillas EJS y manejo de errores.", icono: "bolt" },
  { id: 4, titulo: "Arquitectura y APIs", descripcion: "Operaciones CRUD, arquitectura de capas, rutas REST y formularios.", icono: "layers" },
  { id: 5, titulo: "Persistencia y ORM", descripcion: "Persistencia en archivos con fs y Sequelize: modelos, migraciones, transacciones.", icono: "database" },
  { id: 6, titulo: "Seguridad y producción", descripcion: "Variables de entorno, dotenv, NODE_ENV y autenticación JWT.", icono: "shield" },
];

export const tarjetas = [

  // === FASE 0-1: Gestor de paquetes ===
  {
    fase: 0, titulo: "¿Qué es un gestor de paquetes?", menuTitulo: "Gestor de paquetes",
    capas: [
      { nombre: "¿Qué es una librería?", contenido: `<p class="mb-6">Cuando programas, hay problemas que se repiten en todos los proyectos. Otros desarrolladores ya los resolvieron y publicaron su código para que tú lo uses. A eso se le llama <strong>librería</strong> (<em>library</em>).</p><p class="mb-6">Toca cada celda verde para revelar qué librería resuelve cada problema:</p><table><thead><tr><th>Problema</th><th>Librería</th></tr></thead><tbody><tr><td>Verificar que un correo tenga formato válido</td><td><span class="lib-oculta" data-lib="0" data-nombre="validator" onclick="revelarLibreria(0)">?????</span></td></tr><tr><td>Encriptar una contraseña</td><td><span class="lib-oculta" data-lib="1" data-nombre="bcryptjs" onclick="revelarLibreria(1)">?????</span></td></tr><tr><td>Enviar un email automático</td><td><span class="lib-oculta" data-lib="2" data-nombre="nodemailer" onclick="revelarLibreria(2)">?????</span></td></tr><tr><td>Manejar fechas y horas</td><td><span class="lib-oculta" data-lib="3" data-nombre="dayjs" onclick="revelarLibreria(3)">?????</span></td></tr></tbody></table><p class="mt-4" style="font-size:0.85rem;text-align:center;"><button onclick="revelarTodasLibrerias()" style="color:#339933;text-decoration:underline;cursor:pointer;background:none;border:none;font-family:inherit;font-size:inherit;">Revelar todas</button></p><p class="mt-6">Cuando tu proyecto necesita una librería para funcionar, se convierte en una <strong>dependencia</strong>: tu proyecto <em>depende</em> de ella.</p>` },
      { nombre: "¿Qué es un gestor de paquetes?", contenido: `<p class="mb-6">Un <strong>gestor de paquetes</strong> es la herramienta que descarga, instala y administra las librerías de tu proyecto. Todo con un solo comando en la terminal de tu editor.</p><div class="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6"><div class="text-center"><h4 class="font-titulo font-semibold text-verde-oscuro mb-3 border-b border-verde-oscuro/10 pb-2">Sin gestor</h4><p>Ir a la página de cada librería, descargarla, copiar los archivos en tu proyecto, y repetir por cada una.</p></div><div class="text-center"><h4 class="font-titulo font-semibold text-verde-node mb-3 border-b border-verde-node/20 pb-2">Con gestor</h4><p>Un comando: <code>pnpm add nombre</code></p></div></div><table><thead><tr><th>Gestor</th><th>Qué lo distingue</th></tr></thead><tbody><tr><td><strong>npm</strong></td><td>El oficial de Node.js. Viene preinstalado.</td></tr><tr><td><strong>pnpm</strong></td><td>Más rápido, ahorra espacio. Solo accedes a lo que pediste.</td></tr><tr><td><strong>Yarn</strong></td><td>Creado por Facebook para mejorar npm.</td></tr><tr><td><strong>Bun</strong></td><td>Entorno alternativo a Node con gestor ultrarrápido.</td></tr></tbody></table>` },
      { nombre: "npm vs pnpm", contenido: `<p class="mb-6">Instalas la librería <strong>A</strong>, pero A necesita <strong>B</strong> y B necesita <strong>C</strong>. Esas sub-librerías se llaman <strong>dependencias transitivas</strong>. Toca cada botón para ver la diferencia:</p><div style="display:flex;justify-content:center;gap:1rem;margin-bottom:1rem;"><button id="btn-cadena-npm" class="prediccion-btn simbolo-inactivo" onclick="simularCadena('npm')">npm</button><button id="btn-cadena-pnpm" class="prediccion-btn simbolo-inactivo" onclick="simularCadena('pnpm')">pnpm</button></div><div style="display:flex;justify-content:center;gap:0.5rem;align-items:center;margin-bottom:1rem;flex-wrap:wrap;"><div class="cadena-item hidden" style="background:#339933;color:white;padding:0.4rem 1rem;border-radius:0.5rem;font-weight:600;font-size:0.9rem;">A (tú la pediste)</div><span class="cadena-item hidden" style="color:#33402A;">→</span><div class="cadena-item hidden" style="background:#E6B980;color:#7A5B00;padding:0.4rem 1rem;border-radius:0.5rem;font-weight:600;font-size:0.9rem;">B (la necesita A)</div><span class="cadena-item hidden" style="color:#33402A;">→</span><div class="cadena-item hidden" style="background:#E6B980;color:#7A5B00;padding:0.4rem 1rem;border-radius:0.5rem;font-weight:600;font-size:0.9rem;">C (la necesita B)</div></div><div id="cadena-resultado"></div>` },
      { nombre: "Los comandos", contenido: `<p class="mb-6">Los gestores se usan desde la <strong>terminal de tu editor</strong> (el panel donde escribes comandos, no donde escribes código).</p><pre class="bloque-codigo"><code><span class="code-comment">// Descargar todas las librerías del proyecto</span>\n<span class="code-method">pnpm install</span>\n\n<span class="code-comment">// Agregar una librería nueva</span>\n<span class="code-method">pnpm add</span> <span class="code-string">express</span>\n\n<span class="code-comment">// Eliminar una librería</span>\n<span class="code-method">pnpm remove</span> <span class="code-string">express</span>\n\n<span class="code-comment">// Ejecutar el proyecto</span>\n<span class="code-method">pnpm start</span></code></pre><table class="mt-6"><thead><tr><th>Con pnpm</th><th>Con npm</th><th>Qué hace</th></tr></thead><tbody><tr><td><code>pnpm add</code></td><td><code>npm install</code></td><td>Agregar una librería</td></tr><tr><td><code>pnpm remove</code></td><td><code>npm uninstall</code></td><td>Eliminar una librería</td></tr></tbody></table>` },
      { nombre: "¿Dónde lo usas?", contenido: `<p class="mb-6">Cada vez que abres un proyecto por primera vez, las librerías no están incluidas (son demasiado pesadas). Ejecutas <code>pnpm install</code> y el gestor las descarga todas. Si no lo haces, el proyecto no arranca.</p><table><thead><tr><th>Situación</th><th>Comando</th></tr></thead><tbody><tr><td>Abres un proyecto por primera vez</td><td><code>pnpm install</code></td></tr><tr><td>Necesitas una librería nueva</td><td><code>pnpm add nombre</code></td></tr><tr><td>Quieres ejecutar el proyecto</td><td><code>pnpm start</code></td></tr></tbody></table><div class="recuadro-resaltado mt-6"><strong>En la vida real:</strong> cuando instalas una app desde la App Store o Google Play, estás usando un gestor de paquetes sin saberlo. Eliges la app, tocas "Instalar", y la tienda se encarga de todo.</div>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "Abres un proyecto de Node.js por primera vez. Las librerías no están incluidas. ¿Qué comando ejecutas?", opciones: ["pnpm start", "pnpm add node_modules", "pnpm install", "node install"], respuestaCorrecta: 2, retroalimentacion: { correcta: "Exacto: pnpm install lee el archivo de configuración y descarga todas las librerías que el proyecto necesita.", incorrecta: "Piensa: ¿qué comando le dice al gestor 'descarga todo lo que este proyecto necesita'?" } }
  },

  // === FASE 0-2: package.json ===
  {
    fase: 0, titulo: "package.json: la ficha técnica de tu proyecto", menuTitulo: "package.json",
    capas: [
      { nombre: "¿Qué es?", contenido: `<p class="mb-6"><code>package.json</code> es un archivo en formato <strong>JSON</strong> (un formato para escribir datos como pares de clave y valor, usando llaves <code>{ }</code>). Todo proyecto de Node.js tiene uno en su carpeta raíz.</p><p>Es la <strong>ficha técnica</strong> del proyecto: dice cómo se llama, qué librerías necesita y cómo se ejecuta. Sin este archivo, nadie más puede levantar tu proyecto.</p>` },
      { nombre: "Los campos principales", contenido: `<p class="mb-4">Toca cada línea del JSON para ver qué hace ese campo:</p><pre class="bloque-codigo" style="cursor:default;"><code><div class="json-linea" data-campo="name" onclick="mostrarCampo('name')">  <span class="code-string">"name"</span>: <span class="code-string">"mi-proyecto"</span>,</div><div class="json-linea" data-campo="version" onclick="mostrarCampo('version')">  <span class="code-string">"version"</span>: <span class="code-string">"1.0.0"</span>,</div><div class="json-linea" data-campo="type" onclick="mostrarCampo('type')">  <span class="code-string">"type"</span>: <span class="code-string">"module"</span>,</div><div class="json-linea" data-campo="scripts" onclick="mostrarCampo('scripts')">  <span class="code-string">"scripts"</span>: { <span class="code-string">"start"</span>: <span class="code-string">"node ./bin/www"</span> },</div><div class="json-linea" data-campo="dependencies" onclick="mostrarCampo('dependencies')">  <span class="code-string">"dependencies"</span>: { <span class="code-string">"express"</span>: <span class="code-string">"^4.16.1"</span> }</div></code></pre><div id="campo-desc" class="text-center mt-4 opacity-0 transition-opacity duration-300" style="min-height:2rem;font-size:0.9rem;max-width:30rem;margin-left:auto;margin-right:auto;font-weight:500;color:#33402A;"></div>` },
      { nombre: "¿Quién lo crea?", contenido: `<p class="mb-6">No lo escribes entero a mano. Se crea automáticamente:</p><div class="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6"><div class="text-center"><h4 class="font-titulo font-semibold text-verde-oscuro mb-3 border-b border-verde-oscuro/10 pb-2">Desde cero</h4><pre class="bloque-codigo"><code><span class="code-method">pnpm init</span></code></pre><p class="mt-3">Crea un <code>package.json</code> básico.</p></div><div class="text-center"><h4 class="font-titulo font-semibold text-verde-oscuro mb-3 border-b border-verde-oscuro/10 pb-2">Con el generador de Express</h4><pre class="bloque-codigo"><code><span class="code-method">npx</span> <span class="code-string">express-generator</span></code></pre><p class="mt-3">Crea toda la estructura del proyecto, incluyendo el <code>package.json</code>.</p></div></div><p>Las dependencias se agregan solas cuando ejecutas <code>pnpm add express</code>.</p>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "Tu proyecto usa import/export pero Node.js da error con 'import'. ¿Qué falta en tu package.json?", opciones: ['"scripts": { "start": "node app.js" }', '"type": "module"', '"dependencies": { "esm": "^3.0.0" }', '"version": "2.0.0"'], respuestaCorrecta: 1, retroalimentacion: { correcta: 'Exacto: sin "type": "module", Node.js asume CommonJS y no reconoce import/export.', incorrecta: "Piensa: ¿qué campo le dice a Node.js qué sistema de módulos usar?" } }
  },

  // === FASE 0-3: Semver ===
  {
    fase: 0, titulo: "Semver: cómo leer los números de versión", menuTitulo: "Semver",
    capas: [
      { nombre: "El formato X.Y.Z", contenido: `<p class="mb-4"><strong>SemVer</strong> (<em>Semantic Versioning</em>) es el sistema que usa todo el ecosistema de Node.js para numerar las versiones de las librerías. Cada número en el formato <strong>X.Y.Z</strong> tiene un significado.</p><p class="mb-8">Toca cada número para descubrirlo:</p><div style="display:flex;align-items:center;justify-content:center;gap:0.75rem;margin-bottom:0.5rem;"><div style="display:flex;flex-direction:column;align-items:center;gap:0.35rem;"><span class="version-label opacity-0" data-label="major" style="color:#DC6B6B;">MAJOR</span><button class="version-box" data-version="major" onclick="seleccionarVersion('major')">4</button></div><span class="version-dot" style="margin-top:1.2rem;">.</span><div style="display:flex;flex-direction:column;align-items:center;gap:0.35rem;"><span class="version-label opacity-0" data-label="minor" style="color:#5B8BD4;">MINOR</span><button class="version-box" data-version="minor" onclick="seleccionarVersion('minor')">16</button></div><span class="version-dot" style="margin-top:1.2rem;">.</span><div style="display:flex;flex-direction:column;align-items:center;gap:0.35rem;"><span class="version-label opacity-0" data-label="patch" style="color:#339933;">PATCH</span><button class="version-box" data-version="patch" onclick="seleccionarVersion('patch')">1</button></div></div><div id="version-desc" class="text-center mt-6 opacity-0 transition-opacity duration-300" style="min-height:2.5rem;font-size:0.95rem;max-width:30rem;margin-left:auto;margin-right:auto;"></div>` },
      { nombre: "Los símbolos ^ y ~", contenido: `<p class="mb-6">Estos símbolos van antes de la versión en <code>dependencies</code> y controlan qué actualizaciones se aceptan. Toca cada uno para ver la diferencia:</p><div style="display:flex;justify-content:center;gap:1rem;margin-bottom:0.75rem;"><button id="btn-caret" class="prediccion-btn simbolo-activo" style="font-family:'JetBrains Mono',monospace;font-size:1.1rem;min-width:5rem;" onclick="toggleSimbolo('caret')">^</button><button id="btn-tilde" class="prediccion-btn simbolo-inactivo" style="font-family:'JetBrains Mono',monospace;font-size:1.1rem;min-width:5rem;" onclick="toggleSimbolo('tilde')">~</button></div><p id="texto-simbolo" class="text-center text-sm mb-6" style="color:#33402A;opacity:0.7;">Permite MINOR y PATCH. Bloquea MAJOR.</p><p class="text-center text-sm mb-4" style="opacity:0.5;">Versión base: <code>4.16.1</code></p><div style="display:flex;flex-direction:column;gap:0.5rem;max-width:22rem;margin:0 auto;"><div class="version-item vi-aceptada" data-ver="4.16.2"><span class="vi-icono">✓</span><code style="flex:1;font-size:0.9rem;">4.16.2</code><span class="vi-texto">Se instala</span></div><div class="version-item vi-aceptada" data-ver="4.17.0"><span class="vi-icono">✓</span><code style="flex:1;font-size:0.9rem;">4.17.0</code><span class="vi-texto">Se instala</span></div><div class="version-item vi-rechazada" data-ver="5.0.0"><span class="vi-icono">✗</span><code style="flex:1;font-size:0.9rem;">5.0.0</code><span class="vi-texto">No se instala</span></div></div>` },
      { nombre: "Predice el resultado", contenido: `<p class="mb-6">Tu proyecto tiene esta dependencia:</p><pre class="bloque-codigo"><code><span class="code-string">"express"</span>: <span class="code-string">"^4.16.1"</span></code></pre><p class="mt-6 mb-6" style="font-family:'Fredoka',sans-serif;font-weight:600;font-size:1.05rem;">Sale Express 5.0.0. ¿Se instalará automáticamente?</p><div style="display:flex;justify-content:center;gap:1rem;margin-bottom:1rem;"><button class="prediccion-btn" onclick="revelarPrediccion('si')">Sí se instala</button><button class="prediccion-btn" onclick="revelarPrediccion('no')">No se instala</button></div><div id="prediccion-resultado" class="hidden"></div>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "Tu package.json tiene \"dayjs\": \"~1.11.21\". Sale la versión 1.12.0. ¿Qué pasa con pnpm install?", opciones: ["Se instala la 1.12.0 porque ~ permite MINOR", "No se instala porque ~ solo permite PATCH", "Da error porque la versión es muy nueva", "El gestor te pregunta si quieres actualizar"], respuestaCorrecta: 1, retroalimentacion: { correcta: "Exacto: ~ solo permite PATCH (el tercer número). 1.12.0 es un cambio MINOR (segundo número), así que no se instala.", incorrecta: "Revisa qué permite ~: solo PATCH (el tercer número puede subir). ¿1.12.0 es un cambio de PATCH o de MINOR?" } }
  },

  // === FASE 0-4: Scripts ===
  {
    fase: 0, titulo: "Scripts: atajos para ejecutar tu proyecto", menuTitulo: "Scripts",
    capas: [
      { nombre: "¿Qué es un script?", contenido: `<p class="mb-6">Un <strong>script</strong> es un atajo: un nombre corto que representa un comando largo. Se definen dentro de <code>package.json</code> y se ejecutan desde la terminal de tu editor.</p><pre class="bloque-codigo"><code><span class="code-string">"scripts"</span>: {\n  <span class="code-string">"start"</span>: <span class="code-string">"node ./bin/www"</span>\n}</code></pre><p class="mt-6">Ahora en vez de escribir <code>node ./bin/www</code> (y recordar esa ruta), solo escribes <code>pnpm start</code>.</p>` },
      { nombre: "La diferencia", contenido: `<p class="mb-6">Toca cada opción para ver qué pasa en la terminal:</p><div style="display:flex;justify-content:center;gap:1rem;margin-bottom:1rem;"><button id="btn-directo" class="prediccion-btn simbolo-inactivo" onclick="simularScript('directo')">Ejecutar directo</button><button id="btn-script" class="prediccion-btn simbolo-inactivo" onclick="simularScript('script')">Usar script</button></div><pre class="bloque-codigo"><code id="terminal-script" style="min-height:5rem;"><span class="code-comment">// Elige una opción arriba para ver la diferencia</span></code></pre><div class="recuadro-resaltado mt-4"><strong>Dato:</strong> cuando despliegas tu proyecto en un servidor (como Render), el servidor ejecuta <code>npm start</code>. Si no tienes ese script, el despliegue falla.</div>` },
      { nombre: "Cómo se ejecutan", contenido: `<pre class="bloque-codigo"><code><span class="code-comment">// Scripts estándar (start, test): sin "run"</span>\n<span class="code-method">pnpm start</span>\n<span class="code-method">npm start</span>\n\n<span class="code-comment">// Scripts personalizados: necesitan "run"</span>\n<span class="code-method">pnpm run</span> <span class="code-string">miScript</span>\n<span class="code-method">npm run</span> <span class="code-string">miScript</span></code></pre><p class="mt-6">Los scripts <code>start</code> y <code>test</code> son especiales: no necesitan <code>run</code>. Los nombres personalizados sí.</p>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "Tienes el script \"start\": \"node ./bin/www\". ¿Cuál de estos NO levanta tu servidor?", opciones: ["pnpm start", "npm start", "pnpm run start", "pnpm node"], respuestaCorrecta: 3, retroalimentacion: { correcta: "Correcto: \"pnpm node\" no existe como comando.", incorrecta: "Piensa: ¿cuál de esos no tiene relación con los scripts de package.json?" } }
  },

  // === FASE 0-5: El lockfile ===
  {
    fase: 0, titulo: "El lockfile: pnpm-lock.yaml", menuTitulo: "El lockfile",
    capas: [
      { nombre: "¿Qué es?", contenido: `<p class="mb-6">El <strong>lockfile</strong> es un archivo que genera el gestor automáticamente. Registra la <strong>versión exacta</strong> de cada librería instalada (con pnpm: <code>pnpm-lock.yaml</code>, con npm: <code>package-lock.json</code>).</p><table><thead><tr><th></th><th>package.json</th><th>Lockfile</th></tr></thead><tbody><tr><td>Qué registra</td><td>Rango (<code>^4.16.1</code>)</td><td>Versión exacta (<code>4.21.0</code>)</td></tr><tr><td>Dependencias transitivas</td><td>No las lista</td><td>Todas</td></tr><tr><td>Quién lo escribe</td><td>Tú (o <code>pnpm add</code>)</td><td>El gestor, automáticamente</td></tr></tbody></table>` },
      { nombre: "¿Por qué existe?", contenido: `<p class="mb-6"><code>package.json</code> dice <code>"express": "^4.16.1"</code>. Eso es un rango, no una versión exacta. Toca cada opción para ver qué pasa cuando tú y tu compañero ejecutan <code>pnpm install</code>:</p><div style="display:flex;justify-content:center;gap:1rem;margin-bottom:1rem;"><button id="btn-con-lock" class="prediccion-btn simbolo-inactivo" onclick="simularLockfile(true)">Con lockfile</button><button id="btn-sin-lock" class="prediccion-btn simbolo-inactivo" onclick="simularLockfile(false)">Sin lockfile</button></div><div id="lock-resultado" style="max-width:22rem;margin:0 auto;"></div>` },
      { nombre: "Las reglas", contenido: `<table><thead><tr><th>Regla</th><th>Por qué</th></tr></thead><tbody><tr><td><strong>Nunca lo edites a mano</strong></td><td>Lo genera el gestor. Modificarlo puede romper las versiones.</td></tr><tr><td><strong>Siempre súbelo a Git</strong></td><td>Garantiza que todos trabajen con las mismas versiones.</td></tr><tr><td><strong>Si lo borras, se regenera</strong></td><td>Pero el gestor podría instalar versiones diferentes.</td></tr></tbody></table>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "Un compañero borra pnpm-lock.yaml y ejecuta pnpm install. ¿Qué riesgo tiene?", opciones: ["Ninguno, package.json tiene toda la información", "Se instalan versiones potencialmente diferentes", "No se puede instalar nada sin el lockfile", "Solo se instalan las dependencias directas"], respuestaCorrecta: 1, retroalimentacion: { correcta: "Exacto: sin lockfile, el gestor resuelve los rangos de nuevo y puede instalar versiones distintas.", incorrecta: "Piensa en la diferencia entre un rango (^4.16.1) y una versión exacta (4.21.0)." } }
  },

  // === FASE 0-6: node_modules ===
  {
    fase: 0, titulo: "node_modules: dónde viven los paquetes", menuTitulo: "node_modules",
    capas: [
      { nombre: "¿Qué es?", contenido: `<p class="mb-6"><code>node_modules</code> es la carpeta donde el gestor descarga el código de todas las librerías. Puede contener miles de archivos, incluso en un proyecto pequeño.</p><table><thead><tr><th>Regla</th><th>Por qué</th></tr></thead><tbody><tr><td><strong>No se sube a Git</strong></td><td>Es demasiado pesada y se puede regenerar.</td></tr><tr><td><strong>No se edita</strong></td><td>Es código de otros. Si necesitas cambiar algo, lo haces en <em>tu</em> código.</td></tr><tr><td><strong>Se regenera con <code>pnpm install</code></strong></td><td><code>package.json</code> + lockfile tienen la información para recrearla.</td></tr></tbody></table>` },
      { nombre: "El archivo .gitignore", contenido: `<p class="mb-6">Para que Git ignore <code>node_modules</code>, se usa un archivo llamado <code>.gitignore</code> en la raíz del proyecto:</p><pre class="bloque-codigo"><code><span class="code-comment"># Archivo .gitignore</span>\n\n<span class="code-string">node_modules/</span>    <span class="code-comment">// carpeta de librerías</span>\n<span class="code-string">.env</span>              <span class="code-comment">// archivo con contraseñas (lo veremos más adelante)</span></code></pre><p class="mt-6">Sin esta línea, Git subiría miles de archivos innecesarios al repositorio.</p>` },
      { nombre: "El flujo completo", contenido: `<p class="mb-6">Toca cada paso para avanzar en el flujo:</p><div style="display:flex;flex-direction:column;gap:0.5rem;max-width:28rem;margin:0 auto;"><div class="flujo-paso flujo-activo" onclick="avanzarFlujo(0)"><span class="flujo-num">1</span><div><strong>Clonas un proyecto</strong><br><span style="font-size:0.8rem;opacity:0.7;">node_modules no existe (Git la ignoró)</span></div></div><div class="flujo-paso flujo-pendiente" onclick="avanzarFlujo(1)"><span class="flujo-num">2</span><div><strong><code>pnpm install</code></strong><br><span style="font-size:0.8rem;opacity:0.7;">Se crea con todas las librerías</span></div></div><div class="flujo-paso flujo-pendiente" onclick="avanzarFlujo(2)"><span class="flujo-num">3</span><div><strong>Trabajas normalmente</strong><br><span style="font-size:0.8rem;opacity:0.7;">Está ahí, no la tocas</span></div></div><div class="flujo-paso flujo-pendiente" onclick="avanzarFlujo(3)"><span class="flujo-num">4</span><div><strong><code>git push</code></strong><br><span style="font-size:0.8rem;opacity:0.7;">No se sube (Git la ignora)</span></div></div></div><div class="recuadro-resaltado mt-6"><strong>Truco útil:</strong> si tu proyecto se comporta raro, borra <code>node_modules</code> y ejecuta <code>pnpm install</code>. Es el "apagar y encender" del mundo Node.</div>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "Vas a subir tu proyecto a GitHub. ¿Qué haces con node_modules?", opciones: ["La subes para que otros no instalen nada", "La comprimes en .zip", "La agregas al .gitignore", "La renombras"], respuestaCorrecta: 2, retroalimentacion: { correcta: "Exacto: node_modules va en .gitignore. Los demás la regeneran con pnpm install.", incorrecta: "Si node_modules se puede recrear con un comando, ¿tiene sentido subirla? ¿Qué archivo le dice a Git qué ignorar?" } }
  },

  // === FASE 0-7: Express Generator ===
  {
    fase: 0, titulo: "El generador de Express (vista previa)", menuTitulo: "Express Generator",
    capas: [
      { nombre: "¿Qué es?", contenido: `<p class="mb-6"><code>express-generator</code> es una herramienta de línea de comandos que crea automáticamente la estructura de carpetas de un proyecto Express. En vez de crear cada archivo a mano, ejecutas un comando y te genera todo.</p><p>Al usarlo, te pide dos decisiones de configuración.</p>` },
      { nombre: "Motor de vistas", contenido: `<p class="mb-6">El <strong>motor de vistas</strong> (<em>View Engine</em>) decide cómo tu servidor genera las páginas. Toca cada opción para ver qué tipo de proyecto crea:</p><div style="display:flex;justify-content:center;gap:0.75rem;margin-bottom:1rem;flex-wrap:wrap;"><button class="motor-btn simbolo-inactivo" data-motor="ejs" onclick="elegirMotor('ejs')">EJS</button><button class="motor-btn simbolo-inactivo" data-motor="none" onclick="elegirMotor('none')">None</button></div><div id="motor-resultado" style="max-width:28rem;margin:0 auto;min-height:6rem;"></div>` },
      { nombre: "La estructura que genera", contenido: `<pre class="bloque-codigo"><code><span class="code-comment"># Crear proyecto con EJS:</span>\n<span class="code-method">npx</span> <span class="code-string">express-generator</span> --view=ejs mi-proyecto\n\n<span class="code-comment"># Estructura generada:</span>\nmi-proyecto/\n├── bin/\n│   └── www           <span class="code-comment">// arranca el servidor</span>\n├── public/           <span class="code-comment">// CSS, imágenes, JS del frontend</span>\n├── routes/           <span class="code-comment">// las rutas (endpoints)</span>\n├── views/            <span class="code-comment">// plantillas HTML</span>\n├── app.js            <span class="code-comment">// configuración principal</span>\n└── package.json      <span class="code-comment">// la ficha técnica</span></code></pre><p class="mt-6"><code>npx</code> ejecuta herramientas sin instalarlas permanentemente. Descarga <code>express-generator</code>, lo usa una vez y listo.</p>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "Eliges View Engine: None al crear un proyecto. ¿Qué tipo de proyecto es?", opciones: ["Un proyecto sin backend", "Un monolito que genera HTML", "Una API REST que devuelve JSON", "Un proyecto sin rutas"], respuestaCorrecta: 2, retroalimentacion: { correcta: "Exacto: sin motor de vistas, el servidor no genera HTML. Solo devuelve datos JSON.", incorrecta: "Si el servidor no tiene motor de vistas, no puede armar páginas HTML. ¿Qué le queda?" } }
  },

  // === FASE 4: Verbos HTTP y CRUD ===
  {
    fase: 4, titulo: "Verbos HTTP y CRUD", menuTitulo: "Verbos HTTP y CRUD",
    capas: [
      { nombre: "¿Qué es?", contenido: `<p class="mb-6">CRUD son las cuatro operaciones básicas con un dato. Cada una tiene un <strong>verbo HTTP</strong>: la "palabra de acción" que el cliente envía al servidor.</p><table><thead><tr><th>CRUD</th><th>Verbo HTTP</th><th>Qué hace</th></tr></thead><tbody><tr><td><strong>C</strong>reate</td><td><code>POST</code></td><td>Crear un recurso nuevo</td></tr><tr><td><strong>R</strong>ead</td><td><code>GET</code></td><td>Consultar recursos</td></tr><tr><td><strong>U</strong>pdate</td><td><code>PUT</code> / <code>PATCH</code></td><td>Modificar un recurso</td></tr><tr><td><strong>D</strong>elete</td><td><code>DELETE</code></td><td>Borrar un recurso</td></tr></tbody></table><div class="recuadro-resaltado mt-6">La misma URL (<code>/usuarios</code>) sirve para las cuatro. Lo que cambia es el verbo: <strong>enrutamiento semántico</strong>.</div>` },
      { nombre: "El código por dentro", contenido: `<pre class="bloque-codigo"><code><span class="code-keyword">import</span> express <span class="code-keyword">from</span> <span class="code-string">'express'</span>;\n<span class="code-keyword">const</span> app = <span class="code-method">express</span>();\napp.<span class="code-method">use</span>(express.<span class="code-method">json</span>());\n\n<span class="code-keyword">let</span> usuarios = [{ id: <span class="code-number">1</span>, nombre: <span class="code-string">'Ana'</span> }];\n\n<span class="code-comment">// READ</span>\napp.<span class="code-method">get</span>(<span class="code-string">'/usuarios'</span>, (req, res) => {\n  res.<span class="code-method">json</span>(usuarios);\n});\n\n<span class="code-comment">// CREATE</span>\napp.<span class="code-method">post</span>(<span class="code-string">'/usuarios'</span>, (req, res) => {\n  <span class="code-keyword">const</span> nuevo = req.body;\n  nuevo.id = usuarios.length + <span class="code-number">1</span>;\n  usuarios.<span class="code-method">push</span>(nuevo);\n  res.<span class="code-method">status</span>(<span class="code-number">201</span>).<span class="code-method">json</span>(nuevo);\n});</code></pre><table class="mt-6"><thead><tr><th>Pieza</th><th>Qué es</th></tr></thead><tbody><tr><td><code>app.get</code> / <code>app.post</code></td><td>"Cuando llegue este verbo a esta URL, ejecuta esta función"</td></tr><tr><td><code>(req, res)</code></td><td>Parámetros del callback. <code>req</code> = petición. <code>res</code> = respuesta.</td></tr><tr><td><code>req.body</code></td><td>Los datos que mandó el cliente.</td></tr><tr><td><code>res.status(201)</code></td><td>Código de estado (201 = creado).</td></tr><tr><td><code>res.json()</code></td><td>Envía la respuesta como JSON.</td></tr></tbody></table>` },
      { nombre: "¿Dónde lo usas?", contenido: `<p class="mb-6">En la barra del navegador solo puedes hacer <code>GET</code>. Los otros verbos los dispara la página al hacer clic en un botón. El momento es el <strong>clic</strong>.</p><table><thead><tr><th>Verbo</th><th>Cuándo pasa</th></tr></thead><tbody><tr><td><code>GET</code></td><td>Abres Instagram y ves el feed</td></tr><tr><td><code>POST</code></td><td>Publicas una foto o comentario</td></tr><tr><td><code>PUT</code></td><td>Editas tu biografía y tocas "Guardar"</td></tr><tr><td><code>DELETE</code></td><td>Borras una foto o mensaje</td></tr></tbody></table>` },
      { nombre: "¿Qué puedes hacer con esto?", contenido: `<p class="mb-6">Con solo frontend, los datos viven en tu navegador. Con backend, viajan a un lugar central y existen para todos.</p><div class="grid grid-cols-1 md:grid-cols-2 gap-6"><div class="text-center"><h4 class="font-titulo font-semibold text-verde-oscuro mb-3 border-b border-verde-oscuro/10 pb-2">Solo frontend</h4><p>Escribes una nota. En otro teléfono no hay nada.</p></div><div class="text-center"><h4 class="font-titulo font-semibold text-verde-node mb-3 border-b border-verde-node/20 pb-2">Con backend</h4><p>La nota viaja al servidor. Cualquier persona, desde cualquier dispositivo, la ve.</p></div></div>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "Un usuario edita su biografía y toca 'Guardar'. ¿Qué verbo HTTP envía la app?", opciones: ["GET", "POST", "PUT", "DELETE"], respuestaCorrecta: 2, retroalimentacion: { correcta: "Exacto: editar algo que ya existe es PUT (o PATCH).", incorrecta: "¿Qué verbo representa 'actualizar algo que ya existía'?" } }
  },
];