export const tarjetas = [

  // === FASE 10-1: Escalar una aplicación ===
  {
    fase: 10, titulo: "Escalar una aplicación", menuTitulo: "Escalabilidad",
    capas: [
      { nombre: "Vertical vs Horizontal", contenido: `<p class="mb-6">Toca cada estrategia:</p><div style="display:flex;justify-content:center;gap:1rem;margin-bottom:1rem;"><button id="btn-vertical" class="motor-btn simbolo-inactivo" onclick="compararEscalabilidad('vertical')">Vertical</button><button id="btn-horizontal" class="motor-btn simbolo-inactivo" onclick="compararEscalabilidad('horizontal')">Horizontal</button></div><div id="escalabilidad-desc" style="max-width:30rem;margin:0 auto;min-height:7rem;"></div>` },
      { nombre: "¿Qué es un Load Balancer?", contenido: `<p class="mb-6">Un <strong>balanceador de carga</strong> es el punto de entrada único que recibe todas las peticiones y las reparte entre varias réplicas de tu servidor:</p><div style="display:flex;justify-content:center;align-items:center;gap:0.5rem;margin:1.5rem 0;flex-wrap:wrap;"><div style="background:rgba(91,139,212,.35);backdrop-filter:blur(8px);border:1px solid rgba(91,139,212,.5);color:#1d3f6e;padding:0.5rem 1rem;border-radius:0.5rem;font-size:0.85rem;">Clientes</div><span style="opacity:0.4;">→</span><div style="background:rgba(51,153,51,.35);backdrop-filter:blur(8px);border:1px solid rgba(51,153,51,.5);color:#1a4d1a;padding:0.5rem 1rem;border-radius:0.5rem;font-size:0.85rem;">Load Balancer</div><span style="opacity:0.4;">→</span><div style="display:flex;flex-direction:column;gap:0.3rem;"><div style="background:rgba(230,185,128,.4);backdrop-filter:blur(8px);border:1px solid rgba(230,185,128,.55);color:#7A5B00;padding:0.3rem 0.8rem;border-radius:0.4rem;font-size:0.75rem;">Servidor 1</div><div style="background:rgba(230,185,128,.4);backdrop-filter:blur(8px);border:1px solid rgba(230,185,128,.55);color:#7A5B00;padding:0.3rem 0.8rem;border-radius:0.4rem;font-size:0.75rem;">Servidor 2</div><div style="background:rgba(230,185,128,.4);backdrop-filter:blur(8px);border:1px solid rgba(230,185,128,.55);color:#7A5B00;padding:0.3rem 0.8rem;border-radius:0.4rem;font-size:0.75rem;">Servidor 3</div></div></div>` },
      { nombre: "Los 3 algoritmos", contenido: `<p class="mb-6">Toca cada uno:</p><div style="display:flex;justify-content:center;gap:0.5rem;margin-bottom:1rem;flex-wrap:wrap;"><button class="motor-btn simbolo-inactivo" data-algo="round" onclick="mostrarAlgoritmoBalanceo('round')">Round Robin</button><button class="motor-btn simbolo-inactivo" data-algo="least" onclick="mostrarAlgoritmoBalanceo('least')">Least Connections</button><button class="motor-btn simbolo-inactivo" data-algo="iphash" onclick="mostrarAlgoritmoBalanceo('iphash')">IP Hash</button></div><div id="algoritmo-balanceo-desc" style="max-width:30rem;margin:0 auto;min-height:5rem;"></div>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "Tienes servidores donde algunas peticiones son rápidas y otras hacen consultas pesadas a la base de datos. ¿Qué algoritmo de balanceo conviene más?", opciones: ["Round Robin", "Least Connections", "IP Hash", "Ninguno, todos rinden igual"], respuestaCorrecta: 1, retroalimentacion: { correcta: "Exacto: Least Connections dirige tráfico al servidor menos ocupado en tiempo real, ideal cuando las peticiones tardan tiempos muy distintos.", incorrecta: "Round Robin asume que todas las peticiones cuestan lo mismo. Si eso no es cierto, algunos servidores se saturan más que otros. Necesitas el que mide carga en tiempo real." } }
  },

  // === FASE 10-2: Clustering en Node.js ===
  {
    fase: 10, titulo: "Clustering en Node.js", menuTitulo: "Clustering",
    capas: [
      { nombre: "El problema del hilo único", contenido: `<p class="mb-6">Node.js usa <strong>un solo hilo</strong> por defecto. Si tu servidor tiene 8 núcleos de CPU, 7 quedan completamente inactivos para tu aplicación. El módulo <code>cluster</code> clona el proceso en varios "workers" para usar todos los núcleos.</p>` },
      { nombre: "Las piezas del módulo cluster", contenido: `<p class="mb-6">Toca cada una:</p><div style="display:flex;justify-content:center;gap:0.4rem;margin-bottom:1rem;flex-wrap:wrap;"><button class="motor-btn simbolo-inactivo" data-cluster="isprimary" onclick="mostrarPiezaCluster('isprimary')">cluster.isPrimary</button><button class="motor-btn simbolo-inactivo" data-cluster="fork" onclick="mostrarPiezaCluster('fork')">cluster.fork()</button><button class="motor-btn simbolo-inactivo" data-cluster="cpus" onclick="mostrarPiezaCluster('cpus')">os.cpus().length</button><button class="motor-btn simbolo-inactivo" data-cluster="pid" onclick="mostrarPiezaCluster('pid')">process.pid</button></div><div id="pieza-cluster-desc" style="max-width:30rem;margin:0 auto;min-height:5rem;"></div>` },
      { nombre: "El código completo", contenido: `<pre class="bloque-codigo"><code><span class="code-keyword">import</span> cluster <span class="code-keyword">from</span> <span class="code-string">'node:cluster'</span>;\n<span class="code-keyword">import</span> os <span class="code-keyword">from</span> <span class="code-string">'node:os'</span>;\n\n<span class="code-keyword">if</span> (cluster.isPrimary) {\n  <span class="code-keyword">const</span> numeroCpus = os.<span class="code-method">cpus</span>().length;\n\n  <span class="code-comment">// Un worker por cada núcleo disponible</span>\n  <span class="code-keyword">for</span> (<span class="code-keyword">let</span> i = <span class="code-number">0</span>; i < numeroCpus; i++) {\n    cluster.<span class="code-method">fork</span>();\n  }\n\n  <span class="code-comment">// Si un worker muere, se reemplaza automáticamente</span>\n  cluster.<span class="code-method">on</span>(<span class="code-string">'exit'</span>, (worker) => {\n    console.<span class="code-method">warn</span>(<span class="code-string">'Worker caído, creando reemplazo...'</span>);\n    cluster.<span class="code-method">fork</span>();\n  });\n} <span class="code-keyword">else</span> {\n  <span class="code-comment">// Código que corre en cada worker (tu servidor Express normal)</span>\n  <span class="code-keyword">const</span> app = <span class="code-method">express</span>();\n  app.<span class="code-method">get</span>(<span class="code-string">'/api/recurso'</span>, (req, res) => {\n    res.<span class="code-method">json</span>({ pid: process.pid });\n  });\n  app.<span class="code-method">listen</span>(<span class="code-number">3000</span>);\n}</code></pre>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "¿Por qué se usa cluster.on('exit', () => cluster.fork()) en el proceso principal?", opciones: ["Para crear más workers de los necesarios", "Para reemplazar automáticamente un worker que se cayó, sin intervención manual", "Para detener todo el clúster si un worker falla", "Es solo para efectos de logging"], respuestaCorrecta: 1, retroalimentacion: { correcta: "Exacto: cuando un worker muere, ese callback crea uno nuevo de inmediato, manteniendo la capacidad de procesamiento total sin que un humano tenga que intervenir.", incorrecta: "El objetivo es resiliencia automática: reemplazar al worker caído, no detener todo ni solo registrar el evento." } }
  },

  // === FASE 10-3: Gestionar procesos con PM2 ===
  {
    fase: 10, titulo: "Gestionar procesos con PM2", menuTitulo: "PM2",
    capas: [
      { nombre: "Por qué node/nodemon no bastan en producción", contenido: `<p class="mb-6">Toca cada riesgo:</p><div style="display:flex;justify-content:center;gap:0.4rem;margin-bottom:1rem;flex-wrap:wrap;"><button class="motor-btn simbolo-inactivo" data-riesgo="crash" onclick="mostrarRiesgoProduccion('crash')">Caída sin recuperación</button><button class="motor-btn simbolo-inactivo" data-riesgo="reinicio" onclick="mostrarRiesgoProduccion('reinicio')">Reinicios de hardware</button><button class="motor-btn simbolo-inactivo" data-riesgo="mononucleo" onclick="mostrarRiesgoProduccion('mononucleo')">Un solo núcleo</button></div><div id="riesgo-produccion-desc" style="max-width:30rem;margin:0 auto;min-height:5rem;"></div>` },
      { nombre: "Cómo PM2 resuelve cada uno", contenido: `<table><thead><tr><th>Problema</th><th>Solución de PM2</th></tr></thead><tbody><tr><td>Caída del proceso</td><td>Detecta el crash y reinicia en milisegundos</td></tr><tr><td>Reinicio del servidor físico</td><td>Se integra con systemd para arrancar solo al encender la máquina</td></tr><tr><td>Un solo núcleo</td><td>Modo clúster integrado: <code>-i max</code> sin tocar tu código</td></tr></tbody></table>` },
      { nombre: "Comandos básicos", contenido: `<p class="mb-6">Toca cada comando:</p><div style="display:flex;justify-content:center;gap:0.4rem;margin-bottom:1rem;flex-wrap:wrap;"><button class="motor-btn simbolo-inactivo" data-pm2cmd="start" onclick="mostrarComandoPm2('start')">pm2 start</button><button class="motor-btn simbolo-inactivo" data-pm2cmd="stop" onclick="mostrarComandoPm2('stop')">pm2 stop</button><button class="motor-btn simbolo-inactivo" data-pm2cmd="list" onclick="mostrarComandoPm2('list')">pm2 list</button><button class="motor-btn simbolo-inactivo" data-pm2cmd="restart" onclick="mostrarComandoPm2('restart')">pm2 restart</button></div><div id="comando-pm2-desc" style="max-width:30rem;margin:0 auto;min-height:4rem;"></div>` },
      { nombre: "PM2 + balanceadores externos", contenido: `<p class="mb-6">PM2 reparte carga entre los núcleos de <strong>una sola máquina</strong>. Para escalar a <strong>varias máquinas</strong>, se combina con un balanceador externo como <strong>NGINX</strong> o <strong>AWS ELB</strong>:</p><div style="display:flex;justify-content:center;align-items:center;gap:0.5rem;margin:1.5rem 0;flex-wrap:wrap;"><div style="background:rgba(91,139,212,.35);backdrop-filter:blur(8px);border:1px solid rgba(91,139,212,.5);color:#1d3f6e;padding:0.5rem 1rem;border-radius:0.5rem;font-weight:700;font-size:0.85rem;">Usuarios</div><span style="opacity:0.4;">→</span><div style="background:rgba(51,153,51,.35);backdrop-filter:blur(8px);border:1px solid rgba(51,153,51,.5);color:#1a4d1a;padding:0.5rem 1rem;border-radius:0.5rem;font-weight:700;font-size:0.85rem;">NGINX / AWS ELB</div><span style="opacity:0.4;">→</span><div style="display:flex;flex-direction:column;gap:0.3rem;"><div style="background:rgba(230,185,128,.4);backdrop-filter:blur(8px);border:1px solid rgba(230,185,128,.55);color:#7A5B00;padding:0.4rem 0.9rem;border-radius:0.4rem;font-size:0.8rem;">Máquina 1 → PM2 (todos sus núcleos)</div><div style="background:rgba(230,185,128,.4);backdrop-filter:blur(8px);border:1px solid rgba(230,185,128,.55);color:#7A5B00;padding:0.4rem 0.9rem;border-radius:0.4rem;font-size:0.8rem;">Máquina 2 → PM2 (todos sus núcleos)</div></div></div><div class="recuadro-resaltado mt-4" style="text-align:justify;">Son dos capas distintas: el balanceador externo distribuye tráfico <strong>entre máquinas</strong>. Dentro de cada máquina, PM2 distribuye ese tráfico <strong>entre sus núcleos</strong>.</div>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "Quieres que tu app use todos los núcleos disponibles con PM2, sin escribir código de clustering a mano. ¿Qué comando usas?", opciones: ["pm2 start app.js", "pm2 start app.js -i max", "pm2 restart app.js --all-cores", "pm2 cluster app.js"], respuestaCorrecta: 1, retroalimentacion: { correcta: "Exacto: el flag -i max le dice a PM2 que active su modo clúster integrado usando todos los núcleos disponibles.", incorrecta: "PM2 necesita el flag -i (instances) con el valor max para activar el clustering automático." } }
  },

  // === FASE 10-4: Cerrar el servidor de forma segura ===
  {
    fase: 10, titulo: "Cerrar el servidor de forma segura", menuTitulo: "Apagado seguro",
    capas: [
      { nombre: "SIGINT vs SIGTERM", contenido: `<p class="mb-6">Toca cada señal:</p><div style="display:flex;justify-content:center;gap:1rem;margin-bottom:1rem;"><button id="btn-sigint" class="motor-btn simbolo-inactivo" onclick="compararSenales('sigint')">SIGINT</button><button id="btn-sigterm" class="motor-btn simbolo-inactivo" onclick="compararSenales('sigterm')">SIGTERM</button></div><div id="senales-desc" style="max-width:30rem;margin:0 auto;min-height:5rem;"></div>` },
      { nombre: "El flujo de apagado limpio", contenido: `<p class="mb-6">Toca cada paso:</p><div style="display:flex;flex-direction:column;gap:0.5rem;max-width:30rem;margin:0 auto;"><div class="flujo-paso flujo-activo" onclick="avanzarApagado(0)"><span class="flujo-num">1</span><div><strong>Capturar la señal</strong><br><span style="font-size:0.8rem;opacity:0.7;">process.on('SIGINT', callback)</span></div></div><div class="flujo-paso flujo-pendiente" onclick="avanzarApagado(1)"><span class="flujo-num">2</span><div><strong>Dejar de aceptar peticiones nuevas</strong><br><span style="font-size:0.8rem;opacity:0.7;">server.close()</span></div></div><div class="flujo-paso flujo-pendiente" onclick="avanzarApagado(2)"><span class="flujo-num">3</span><div><strong>Cerrar conexiones a la base de datos</strong><br><span style="font-size:0.8rem;opacity:0.7;">await pool.end()</span></div></div><div class="flujo-paso flujo-pendiente" onclick="avanzarApagado(3)"><span class="flujo-num">4</span><div><strong>process.exit(0)</strong><br><span style="font-size:0.8rem;opacity:0.7;">Recién ahora se termina el proceso, de forma segura</span></div></div></div>` },
      { nombre: "El código completo", contenido: `<pre class="bloque-codigo"><code><span class="code-keyword">const</span> server = app.<span class="code-method">listen</span>(PORT);\n\nprocess.<span class="code-method">on</span>(<span class="code-string">'SIGINT'</span>, <span class="code-keyword">async</span> () => {\n  console.<span class="code-method">log</span>(<span class="code-string">'Apagando de forma segura...'</span>);\n  <span class="code-keyword">try</span> {\n    server.<span class="code-method">close</span>(() => console.<span class="code-method">log</span>(<span class="code-string">'Servidor HTTP cerrado'</span>));\n    <span class="code-keyword">await</span> poolDatabase.<span class="code-method">close</span>();\n    process.<span class="code-method">exit</span>(<span class="code-number">0</span>);  <span class="code-comment">// 0 = salida exitosa</span>\n  } <span class="code-keyword">catch</span> (error) {\n    process.<span class="code-method">exit</span>(<span class="code-number">1</span>);  <span class="code-comment">// 1 = salida por error</span>\n  }\n});</code></pre>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "¿Por qué no basta con dejar que Node.js maneje SIGINT por su comportamiento por defecto?", opciones: ["Porque SIGINT no existe en Node.js", "Porque el comportamiento por defecto mata el proceso de inmediato, sin cerrar conexiones de base de datos u otros recursos", "Porque process.on() es más lento", "No hay ninguna diferencia real"], respuestaCorrecta: 1, retroalimentacion: { correcta: "Exacto: sin capturar la señal, Node se detiene abruptamente, dejando posibles transacciones a medias y conexiones abiertas. Capturarla te da la oportunidad de limpiar antes de salir.", incorrecta: "El comportamiento por defecto es justamente el problema: detiene todo de golpe sin darte tiempo de cerrar recursos limpiamente." } }
  },

  // === FASE 10-5: Errores no capturados y errores comunes ===
  {
    fase: 10, titulo: "Errores no capturados y errores comunes", menuTitulo: "Errores comunes",
    capas: [
      { nombre: "uncaughtException", contenido: `<p class="mb-6">Si un error escapa de todo <code>try/catch</code>, Node lo llama <strong>uncaughtException</strong> y, por defecto, mata el proceso de inmediato.</p><pre class="bloque-codigo"><code>process.<span class="code-method">on</span>(<span class="code-string">'uncaughtException'</span>, (error) => {\n  console.<span class="code-method">error</span>(<span class="code-string">'Excepción no capturada:'</span>, error.message);\n  console.<span class="code-method">error</span>(error.stack);\n\n  <span class="code-comment">// Regla de oro: NO seguir corriendo, la memoria puede estar corrupta</span>\n  <span class="code-comment">// Salir con código 1 para que PM2 reinicie una instancia limpia</span>\n  process.<span class="code-method">exit</span>(<span class="code-number">1</span>);\n});</code></pre><div class="recuadro-resaltado mt-4">Capturar el error no significa ignorarlo y seguir. Es para registrar el fallo y salir de forma controlada, dejando que PM2 levante una instancia nueva y limpia.</div>` },
      { nombre: "Decodificar errores comunes", contenido: `<p class="mb-6">Toca cada error:</p><div style="display:flex;justify-content:center;gap:0.4rem;margin-bottom:1rem;flex-wrap:wrap;"><button class="motor-btn simbolo-inactivo" data-err="module" onclick="mostrarErrorComun('module')">Cannot find module</button><button class="motor-btn simbolo-inactivo" data-err="eaddr" onclick="mostrarErrorComun('eaddr')">EADDRINUSE</button><button class="motor-btn simbolo-inactivo" data-err="syntax" onclick="mostrarErrorComun('syntax')">SyntaxError</button><button class="motor-btn simbolo-inactivo" data-err="ref" onclick="mostrarErrorComun('ref')">ReferenceError</button><button class="motor-btn simbolo-inactivo" data-err="enoent" onclick="mostrarErrorComun('enoent')">ENOENT</button></div><div id="error-comun-desc" style="max-width:30rem;margin:0 auto;min-height:4rem;"></div>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "Intentas arrancar tu servidor en el puerto 3000, pero ya hay otro proceso usándolo. ¿Qué error verás?", opciones: ["ENOENT", "Cannot find module", "EADDRINUSE", "ReferenceError"], respuestaCorrecta: 2, retroalimentacion: { correcta: "Exacto: EADDRINUSE (Address In Use) significa que el puerto de red ya está ocupado por otro proceso.", incorrecta: "ENOENT es de archivos, ReferenceError es de variables no declaradas. El error de un puerto ya ocupado es EADDRINUSE." } }
  },

  // === FASE 10-6: Procesos en segundo plano y versiones de Node ===
  {
    fase: 10, titulo: "Procesos en segundo plano y nvm", menuTitulo: "Background y nvm",
    capas: [
      { nombre: "Foreground vs Background", contenido: `<p class="mb-6">Por defecto, un comando ocupa la terminal (<strong>foreground</strong>) hasta que termina. Agregar <code>&</code> al final lo manda a <strong>background</strong>, liberando la terminal:</p><pre class="bloque-codigo"><code><span class="code-comment">// Ocupa la terminal hasta Ctrl+C</span>\nnode app.js\n\n<span class="code-comment">// Libera la terminal de inmediato</span>\nnode app.js &</code></pre>` },
      { nombre: "Comandos de gestión de procesos", contenido: `<p class="mb-6">Toca cada comando:</p><div style="display:flex;justify-content:center;gap:0.4rem;margin-bottom:1rem;flex-wrap:wrap;"><button class="motor-btn simbolo-inactivo" data-termcmd="jobs" onclick="mostrarComandoTerminal('jobs')">jobs</button><button class="motor-btn simbolo-inactivo" data-termcmd="fg" onclick="mostrarComandoTerminal('fg')">fg</button><button class="motor-btn simbolo-inactivo" data-termcmd="psaux" onclick="mostrarComandoTerminal('psaux')">ps aux | grep node</button><button class="motor-btn simbolo-inactivo" data-termcmd="kill" onclick="mostrarComandoTerminal('kill')">kill PID</button></div><div id="comando-terminal-desc" style="max-width:30rem;margin:0 auto;min-height:4rem;"></div>` },
      { nombre: "nvm: múltiples versiones de Node", contenido: `<p class="mb-6">Un proyecto antiguo puede necesitar Node 14, y uno nuevo Node 22. Instalar ambas versiones globalmente genera conflictos. <strong>nvm</strong> (Node Version Manager) las aísla y permite alternar entre ellas:</p><pre class="bloque-codigo"><code><span class="code-comment">// Instala y activa la última versión estable de Node</span>\nnvm install node</code></pre>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "Sospechas que quedó un proceso de Node corriendo en segundo plano de una sesión anterior y quieres encontrarlo. ¿Qué comando usas?", opciones: ["nvm install node", "jobs", "ps aux | grep node", "pm2 list"], respuestaCorrecta: 2, retroalimentacion: { correcta: "Exacto: ps aux lista todos los procesos del sistema, y grep node filtra solo los relacionados con Node. jobs solo muestra procesos de la sesión de terminal actual, no de sesiones anteriores.", incorrecta: "jobs solo ve procesos de la sesión de terminal activa. Para buscar en todo el sistema, incluso procesos de sesiones anteriores, necesitas ps aux | grep node." } }
  },
];
