export const tarjetas = [

  // === FASE 7-1: Los principios de REST ===
  {
    fase: 7, titulo: "Los principios de REST", menuTitulo: "Principios REST",
    capas: [
      { nombre: "¿Qué es REST?", contenido: `<p class="mb-6"><strong>REST</strong> (Representational State Transfer) no es un protocolo ni un estándar de código: es un <strong>estilo de arquitectura</strong>, un conjunto de restricciones de diseño para transferir datos entre sistemas de forma eficiente y desacoplada.</p><p class="mb-6">Tiene 5 principios formales. Toca cada uno:</p><div style="display:flex;justify-content:center;gap:0.4rem;margin-bottom:1rem;flex-wrap:wrap;"><button class="motor-btn simbolo-inactivo" data-rest="cliente" onclick="mostrarPrincipioRest('cliente')">Cliente-Servidor</button><button class="motor-btn simbolo-inactivo" data-rest="stateless" onclick="mostrarPrincipioRest('stateless')">Stateless</button><button class="motor-btn simbolo-inactivo" data-rest="cache" onclick="mostrarPrincipioRest('cache')">Cacheable</button><button class="motor-btn simbolo-inactivo" data-rest="uniforme" onclick="mostrarPrincipioRest('uniforme')">Interfaz Uniforme</button><button class="motor-btn simbolo-inactivo" data-rest="capas" onclick="mostrarPrincipioRest('capas')">Sistema de Capas</button></div><div id="principio-rest-desc" style="max-width:32rem;margin:0 auto;min-height:6rem;"></div>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "Tu API guarda en memoria RAM del servidor quién inició sesión. Si escalas a 3 servidores detrás de un balanceador de carga, ¿qué principio de REST estás rompiendo?", opciones: ["Cacheable", "Stateless", "Sistema de Capas", "Interfaz Uniforme"], respuestaCorrecta: 1, retroalimentacion: { correcta: "Exacto: guardar sesión en memoria rompe Stateless. Si la siguiente petición llega a otro servidor del clúster, ese servidor no sabrá quién eres.", incorrecta: "Piensa: el problema es que el servidor 'recuerda' algo entre peticiones. ¿Cuál principio prohíbe justamente eso?" } }
  },

  // === FASE 7-2: HATEOAS y versionamiento ===
  {
    fase: 7, titulo: "HATEOAS y versionamiento", menuTitulo: "HATEOAS y versiones",
    capas: [
      { nombre: "¿Qué es HATEOAS?", contenido: `<p class="mb-6">Normalmente, el cliente tiene URLs "hardcodeadas" en su código. Si el servidor cambia una ruta, el cliente se rompe. <strong>HATEOAS</strong> resuelve esto: el servidor devuelve, junto con los datos, los enlaces de las acciones disponibles.</p><pre class="bloque-codigo"><code>{\n  <span class="code-string">"id"</span>: <span class="code-number">105</span>,\n  <span class="code-string">"nombre"</span>: <span class="code-string">"Sofía"</span>,\n  <span class="code-string">"links"</span>: [\n    { <span class="code-string">"rel"</span>: <span class="code-string">"self"</span>, <span class="code-string">"href"</span>: <span class="code-string">"/api/v1/usuarios/105"</span>, <span class="code-string">"method"</span>: <span class="code-string">"GET"</span> },\n    { <span class="code-string">"rel"</span>: <span class="code-string">"update"</span>, <span class="code-string">"href"</span>: <span class="code-string">"/api/v1/usuarios/105"</span>, <span class="code-string">"method"</span>: <span class="code-string">"PUT"</span> },\n    { <span class="code-string">"rel"</span>: <span class="code-string">"delete"</span>, <span class="code-string">"href"</span>: <span class="code-string">"/api/v1/usuarios/105"</span>, <span class="code-string">"method"</span>: <span class="code-string">"DELETE"</span> }\n  ]\n}</code></pre>` },
      { nombre: "Versionamiento: URL vs Header", contenido: `<p class="mb-6">Tu API cambiará con el tiempo. Toca cada estrategia:</p><div style="display:flex;justify-content:center;gap:1rem;margin-bottom:1rem;"><button id="btn-version-url" class="motor-btn simbolo-inactivo" onclick="compararVersionamiento('url')">En la URL</button><button id="btn-version-header" class="motor-btn simbolo-inactivo" onclick="compararVersionamiento('header')">En un Header</button></div><div id="version-comparar-desc" style="max-width:30rem;margin:0 auto;min-height:7rem;"></div>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "¿Por qué HATEOAS ayuda a que el cliente no se rompa cuando el servidor reorganiza sus rutas?", opciones: ["Porque HATEOAS encripta las URLs", "Porque el cliente lee las URLs dinámicamente desde la respuesta, en vez de tenerlas escritas en su propio código", "Porque HATEOAS elimina la necesidad de rutas", "Porque el servidor nunca cambia sus rutas si usa HATEOAS"], respuestaCorrecta: 1, retroalimentacion: { correcta: "Exacto: el cliente no memoriza URLs, las obtiene del JSON de respuesta cada vez. Si el servidor las cambia, el cliente simplemente lee las nuevas.", incorrecta: "HATEOAS no impide que las rutas cambien. Lo que hace es que el cliente ya no necesita tenerlas escritas de antemano en su código." } }
  },

  // === FASE 7-3: Diseño de URLs y anidamiento ===
  {
    fase: 7, titulo: "Diseño de URLs y anidamiento", menuTitulo: "Diseño de URLs",
    capas: [
      { nombre: "Sustantivos en plural, no verbos", contenido: `<p class="mb-6">Una URL identifica un <strong>recurso</strong> (sustantivo), no una acción (verbo). El verbo HTTP ya dice qué hacer:</p><table><thead><tr><th>Mal diseño</th><th>Buen diseño REST</th></tr></thead><tbody><tr><td><code>GET /obtenerUsuarios</code></td><td><code>GET /usuarios</code></td></tr><tr><td><code>POST /crearUsuario</code></td><td><code>POST /usuarios</code></td></tr><tr><td><code>POST /modificarUsuarioPorId</code></td><td><code>PUT /usuarios/:id</code></td></tr></tbody></table>` },
      { nombre: "Anidamiento: cuándo sí y cuándo no", contenido: `<p class="mb-6"><code>/usuarios/:id/publicaciones</code> tiene sentido cuando el hijo depende del padre. Pero no anides más de 2 niveles:</p><table><thead><tr><th>Evitar (sobreanidado)</th><th>Preferir</th></tr></thead><tbody><tr><td><code>DELETE /usuarios/:id/publicaciones/:pubId</code></td><td><code>DELETE /publicaciones/:pubId</code></td></tr></tbody></table><p class="mt-4">Si ya tienes el ID único de la publicación, no necesitas arrastrar el ID del usuario en la URL para eliminarla.</p>` },
      { nombre: "Query params para colecciones", contenido: `<p class="mb-6">Toca cada caso de uso:</p><div style="display:flex;justify-content:center;gap:0.4rem;margin-bottom:1rem;flex-wrap:wrap;"><button class="motor-btn simbolo-inactivo" data-qp="filtrado" onclick="mostrarQueryParam('filtrado')">Filtrado</button><button class="motor-btn simbolo-inactivo" data-qp="busqueda" onclick="mostrarQueryParam('busqueda')">Búsqueda</button><button class="motor-btn simbolo-inactivo" data-qp="orden" onclick="mostrarQueryParam('orden')">Ordenamiento</button><button class="motor-btn simbolo-inactivo" data-qp="paginacion" onclick="mostrarQueryParam('paginacion')">Paginación</button></div><div id="query-param-desc" style="max-width:30rem;margin:0 auto;min-height:4rem;"></div>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "Tienes una tabla con 1 millón de productos. ¿Qué query params usas para no traer todo de golpe?", opciones: ["?buscar=zapatos", "?pagina=2&limite=50", "?ordenarPor=precio", "?estado=activo"], respuestaCorrecta: 1, retroalimentacion: { correcta: "Exacto: paginación con pagina y limite controla cuántos registros viajan por red en cada solicitud, evitando agotar la memoria del servidor y el cliente.", incorrecta: "Los otros son válidos para filtrar/buscar/ordenar, pero no limitan cuántos registros se devuelven. ¿Cuál controla el tamaño del bloque de datos?" } }
  },

  // === FASE 7-4: Rutas y controladores ===
  {
    fase: 7, titulo: "Estructura: rutas y controladores", menuTitulo: "Rutas y controladores",
    capas: [
      { nombre: "El problema de un solo archivo", contenido: `<p class="mb-6">Tener todas las rutas y toda la lógica en un solo <code>app.js</code> genera problemas reales en un proyecto que crece:</p><table><thead><tr><th>Problema</th><th>Por qué duele</th></tr></thead><tbody><tr><td>Alta carga cognitiva</td><td>Miles de líneas dificultan leer y depurar</td></tr><tr><td>Conflictos en Git</td><td>Varios desarrolladores editando el mismo archivo generan merge conflicts</td></tr><tr><td>Imposible testear aislado</td><td>No puedes probar la lógica sin levantar todo el servidor HTTP</td></tr></tbody></table>` },
      { nombre: "routes vs controllers", contenido: `<p class="mb-6">Toca cada carpeta:</p><div style="display:flex;justify-content:center;gap:1rem;margin-bottom:1rem;"><button id="btn-routes" class="motor-btn simbolo-inactivo" onclick="compararRoutesControllers('routes')">/routes</button><button id="btn-controllers" class="motor-btn simbolo-inactivo" onclick="compararRoutesControllers('controllers')">/controllers</button></div><div id="routes-controllers-desc" style="max-width:30rem;margin:0 auto;min-height:6rem;"></div>` },
      { nombre: "Cómo se conectan", contenido: `<pre class="bloque-codigo"><code><span class="code-comment">// usuarios.controller.js: la lógica</span>\n<span class="code-keyword">export const</span> listarUsuarios = <span class="code-keyword">async</span> (req, res) => {\n  <span class="code-keyword">try</span> {\n    <span class="code-keyword">const</span> usuarios = [{ id: <span class="code-number">1</span>, nombre: <span class="code-string">'Andrés'</span> }];\n    res.<span class="code-method">status</span>(<span class="code-number">200</span>).<span class="code-method">json</span>(usuarios);\n  } <span class="code-keyword">catch</span> (error) {\n    res.<span class="code-method">status</span>(<span class="code-number">500</span>).<span class="code-method">json</span>({ error: <span class="code-string">'Fallo interno'</span> });\n  }\n};\n\n<span class="code-comment">// usuarios.routes.js: el mapa</span>\n<span class="code-keyword">import</span> { Router } <span class="code-keyword">from</span> <span class="code-string">'express'</span>;\n<span class="code-keyword">import</span> { listarUsuarios } <span class="code-keyword">from</span> <span class="code-string">'./usuarios.controller.js'</span>;\n\n<span class="code-keyword">const</span> router = <span class="code-method">Router</span>();\nrouter.<span class="code-method">get</span>(<span class="code-string">'/usuarios'</span>, listarUsuarios);  <span class="code-comment">// sin paréntesis: pasa la referencia</span>\n\n<span class="code-keyword">export default</span> router;</code></pre>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "En router.get('/usuarios', listarUsuarios), ¿por qué listarUsuarios va SIN paréntesis?", opciones: ["Es un error de sintaxis, deberían llevar paréntesis", "Se pasa la función como referencia; Express la ejecutará cuando llegue la petición, no antes", "Sin paréntesis la función no hace nada", "Los paréntesis solo se usan en controladores async"], respuestaCorrecta: 1, retroalimentacion: { correcta: "Exacto: con paréntesis la ejecutarías inmediatamente al cargar el archivo. Sin ellos, le pasas la función a Express para que la ejecute cuando corresponda.", incorrecta: "Piensa en la diferencia entre 'esta es la función' (sin paréntesis) y 'ejecuta la función ahora' (con paréntesis). ¿Cuál necesita Express?" } }
  },

  // === FASE 7-5: Respuestas estandarizadas ===
  {
    fase: 7, titulo: "Respuestas estandarizadas", menuTitulo: "Respuestas estandarizadas",
    capas: [
      { nombre: "¿Por qué un formato fijo?", contenido: `<p class="mb-6">Si cada endpoint devuelve una forma distinta de JSON, el frontend tiene que adivinar dónde están los datos en cada caso. Un formato fijo (<code>status</code>, <code>code</code>, <code>data</code>, <code>message</code>) permite escribir <strong>un solo</strong> manejador genérico para toda la API.</p>` },
      { nombre: "400 vs 422", contenido: `<p class="mb-6">Toca cada código:</p><div style="display:flex;justify-content:center;gap:1rem;margin-bottom:1rem;"><button id="btn-400" class="motor-btn simbolo-inactivo" onclick="comparar400422('400')">400</button><button id="btn-422" class="motor-btn simbolo-inactivo" onclick="comparar400422('422')">422</button></div><div id="comparar-400-422-desc" style="max-width:30rem;margin:0 auto;min-height:6rem;"></div>` },
      { nombre: "Éxito vs error, mismo formato", contenido: `<p class="mb-6">Toca cada una:</p><div style="display:flex;justify-content:center;gap:1rem;margin-bottom:1rem;"><button id="btn-resp-exito" class="motor-btn simbolo-inactivo" onclick="mostrarRespuestaEstandar('exito')">Respuesta exitosa</button><button id="btn-resp-error" class="motor-btn simbolo-inactivo" onclick="mostrarRespuestaEstandar('error')">Respuesta de error</button></div><pre class="bloque-codigo"><code id="respuesta-estandar-codigo" style="min-height:7rem;"><span class="code-comment">// Elige una opción arriba</span></code></pre>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "Un cliente envía { \"edad\": -5 }. El JSON está bien formado, pero -5 no es una edad válida. ¿Qué código de estado corresponde?", opciones: ["400 Bad Request", "422 Unprocessable Entity", "404 Not Found", "500 Internal Server Error"], respuestaCorrecta: 1, retroalimentacion: { correcta: "Exacto: el JSON se parseó sin problema (por eso no es 400). El problema es semántico: el valor no cumple las reglas de negocio. Eso es 422.", incorrecta: "400 es para errores de sintaxis (JSON malformado). Aquí el JSON está bien escrito, solo que el valor -5 no tiene sentido de negocio." } }
  },

  // === FASE 7-6: Middleware global de errores en una API ===
  {
    fase: 7, titulo: "Middleware global de errores en una API", menuTitulo: "Errores en la API completa",
    capas: [
      { nombre: "El error viaja entre archivos", contenido: `<p class="mb-6">Aunque tu ruta y tu controlador estén en archivos distintos, Express los fusiona en <strong>una sola cadena de ejecución</strong>. Cuando el controlador llama <code>next(error)</code>, Express salta directo al middleware de error global, sin importar en qué archivo ocurrió el fallo.</p>` },
      { nombre: "Consola del servidor vs cliente", contenido: `<p class="mb-6">El middleware de error separa dos audiencias distintas. Toca cada una:</p><div style="display:flex;justify-content:center;gap:1rem;margin-bottom:1rem;"><button id="btn-consola-server" class="motor-btn simbolo-inactivo" onclick="compararAudienciaError('servidor')">Para el servidor</button><button id="btn-cliente-api" class="motor-btn simbolo-inactivo" onclick="compararAudienciaError('cliente')">Para el cliente</button></div><div id="audiencia-error-desc" style="max-width:30rem;margin:0 auto;min-height:7rem;"></div>` },
      { nombre: "El flujo completo", contenido: `<pre class="bloque-codigo"><code><span class="code-comment">// controllers/usuarios.controller.js</span>\n<span class="code-keyword">export const</span> registrarUsuario = <span class="code-keyword">async</span> (req, res, next) => {\n  <span class="code-keyword">try</span> {\n    <span class="code-keyword">const</span> nuevo = <span class="code-keyword">await</span> Usuario.<span class="code-method">create</span>(req.body);\n    res.<span class="code-method">status</span>(<span class="code-number">201</span>).<span class="code-method">json</span>({ status: <span class="code-string">'success'</span>, data: nuevo });\n  } <span class="code-keyword">catch</span> (error) {\n    <span class="code-method">next</span>(error);  <span class="code-comment">// viaja al middleware global, sin importar el archivo</span>\n  }\n};\n\n<span class="code-comment">// app.js</span>\napp.<span class="code-method">use</span>(<span class="code-string">'/api'</span>, usuariosRouter);\n\napp.<span class="code-method">use</span>((err, req, res, next) => {\n  console.<span class="code-method">error</span>(err.stack);  <span class="code-comment">// detalle técnico, solo en consola del servidor</span>\n\n  <span class="code-keyword">let</span> codigo = err.statusCode || <span class="code-number">500</span>;\n  <span class="code-keyword">if</span> (err.name === <span class="code-string">'SequelizeValidationError'</span>) codigo = <span class="code-number">422</span>;\n\n  res.<span class="code-method">status</span>(codigo).<span class="code-method">json</span>({\n    status: <span class="code-string">'error'</span>,\n    code: codigo,\n    message: <span class="code-string">'Ocurrió un error al procesar la solicitud.'</span>  <span class="code-comment">// genérico, sin detalles técnicos</span>\n  });\n});</code></pre>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "¿Por qué el middleware de error NO debe enviar err.stack en la respuesta JSON al cliente?", opciones: ["Porque hace la respuesta muy pesada", "Porque expone rutas de archivos, versiones de librerías y estructura interna: una vulnerabilidad de seguridad", "Porque err.stack no es texto válido para JSON", "No hay ningún problema en enviarlo"], respuestaCorrecta: 1, retroalimentacion: { correcta: "Exacto: err.stack revela detalles internos del servidor que un atacante podría usar para diseñar un ataque dirigido. Se registra solo en la consola del servidor, nunca se envía al cliente.", incorrecta: "El problema no es de tamaño ni de formato. Es que err.stack contiene información interna sensible sobre tu infraestructura." } }
  },
];
