export const tarjetas = [

  // === FASE 5-1: Conectarse a PostgreSQL ===
  {
    fase: 5, titulo: "Conectarse a PostgreSQL", menuTitulo: "Conexión con pg",
    capas: [
      { nombre: "RDBMS y PostgreSQL", contenido: `<p class="mb-6">Un <strong>RDBMS</strong> (Relational Database Management System) almacena datos en tablas organizadas por filas y columnas, vinculadas entre sí mediante claves primarias y foráneas. <strong>PostgreSQL</strong> es un RDBMS de código abierto, elegido en backend profesional por su tolerancia a fallos y cumplimiento estricto de estándares.</p><p>Para hablar con PostgreSQL desde Node.js, necesitas un driver: el paquete <code>pg</code>.</p>` },
      { nombre: "Client vs Pool", contenido: `<p class="mb-6">Toca cada opción para comparar:</p><div style="display:flex;justify-content:center;gap:1rem;margin-bottom:1rem;"><button id="btn-client" class="motor-btn simbolo-inactivo" onclick="compararClientPool('client')">Client</button><button id="btn-pool" class="motor-btn simbolo-inactivo" onclick="compararClientPool('pool')">Pool</button></div><div id="client-pool-resultado" style="max-width:30rem;margin:0 auto;min-height:8rem;"></div>` },
      { nombre: "Conexión con variables de entorno", contenido: `<p class="mb-6">Las credenciales nunca van escritas directamente en el código. Se guardan en un archivo <code>.env</code> (que va en <code>.gitignore</code>) y se leen con <code>dotenv</code>:</p><pre class="bloque-codigo"><code><span class="code-comment"># Archivo .env</span>\nDB_USER=desarrollador\nDB_PASSWORD=clave_secreta\nDB_HOST=127.0.0.1\nDB_PORT=5432\nDB_DATABASE=mi_base</code></pre><pre class="bloque-codigo mt-3"><code><span class="code-keyword">import</span> pg <span class="code-keyword">from</span> <span class="code-string">'pg'</span>;\n<span class="code-keyword">import</span> <span class="code-string">'dotenv/config'</span>;  <span class="code-comment">// carga el .env en process.env</span>\n\n<span class="code-keyword">const</span> pool = <span class="code-keyword">new</span> pg.<span class="code-method">Pool</span>({\n  user: process.env.DB_USER,\n  password: process.env.DB_PASSWORD,\n  host: process.env.DB_HOST,\n  port: <span class="code-method">parseInt</span>(process.env.DB_PORT, <span class="code-number">10</span>),\n  database: process.env.DB_DATABASE\n});\n\n<span class="code-keyword">export default</span> pool;</code></pre>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "Tu servidor Express recibe muchas peticiones simultáneas que necesitan consultar la base de datos. ¿Qué deberías usar: Client o Pool?", opciones: ["Client, porque es más simple", "Pool, porque reutiliza conexiones y evita crear una nueva por cada petición", "No importa, ambos rinden igual", "Client, porque Pool no soporta PostgreSQL"], respuestaCorrecta: 1, retroalimentacion: { correcta: "Exacto: Pool mantiene varias conexiones listas y las reutiliza, evitando el costo de abrir y cerrar un socket TCP en cada petición.", incorrecta: "Piensa en el costo de abrir una conexión TCP nueva por cada petición HTTP que llega. ¿Cuál de los dos evita ese costo repetido?" } }
  },

  // === FASE 5-2: Consultas SELECT ===
  {
    fase: 5, titulo: "Consultas SELECT y el objeto Result", menuTitulo: "Consultas SELECT",
    capas: [
      { nombre: "pool.query() y el objeto Result", contenido: `<p class="mb-6"><code>pool.query()</code> envía SQL al motor y devuelve una promesa que se resuelve en un objeto <strong>Result</strong>. Toca cada propiedad:</p><div style="display:flex;justify-content:center;gap:0.5rem;margin-bottom:1rem;flex-wrap:wrap;"><button class="motor-btn simbolo-inactivo" data-result="rows" onclick="mostrarResultProp('rows')">rows</button><button class="motor-btn simbolo-inactivo" data-result="rowCount" onclick="mostrarResultProp('rowCount')">rowCount</button><button class="motor-btn simbolo-inactivo" data-result="fields" onclick="mostrarResultProp('fields')">fields</button></div><div id="result-prop-desc" style="max-width:30rem;margin:0 auto;min-height:5rem;"></div>` },
      { nombre: "Consultas parametrizadas", contenido: `<p class="mb-6">En vez de escribir el valor directo en el SQL, usas marcadores <code>$1</code>, <code>$2</code> y pasas los valores en un arreglo separado:</p><pre class="bloque-codigo"><code><span class="code-keyword">async function</span> <span class="code-method">obtenerUsuarioPorId</span>(id) {\n  <span class="code-keyword">const</span> sql = <span class="code-string">'SELECT id, email, rol FROM usuarios WHERE id = $1'</span>;\n\n  <span class="code-keyword">try</span> {\n    <span class="code-keyword">const</span> resultado = <span class="code-keyword">await</span> pool.<span class="code-method">query</span>(sql, [id]);\n\n    <span class="code-keyword">if</span> (resultado.rowCount === <span class="code-number">0</span>) {\n      <span class="code-keyword">return null</span>;\n    }\n    <span class="code-keyword">return</span> resultado.rows[<span class="code-number">0</span>];\n  } <span class="code-keyword">catch</span> (error) {\n    console.<span class="code-method">error</span>(error.message);\n    <span class="code-keyword">throw</span> error;\n  }\n}</code></pre>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "Ejecutas un SELECT que no encuentra ningún registro. ¿Qué valor tendrá resultado.rowCount?", opciones: ["undefined", "null", "0", "Lanza un error automáticamente"], respuestaCorrecta: 2, retroalimentacion: { correcta: "Exacto: rowCount será 0. La consulta se ejecuta sin error, simplemente no encontró coincidencias.", incorrecta: "La consulta no falla por no encontrar nada: simplemente devuelve 0 filas. rowCount refleja ese número exacto." } }
  },

  // === FASE 5-3: Prevención de SQL Injection ===
  {
    fase: 5, titulo: "Prevención de SQL Injection", menuTitulo: "SQL Injection",
    capas: [
      { nombre: "¿Qué es SQL Injection?", contenido: `<p class="mb-6">Ocurre cuando concatenas directamente datos del usuario dentro del texto SQL. El motor recibe todo como <strong>un solo string</strong> y no puede distinguir qué es código y qué es dato.</p><p class="mb-6">Si un usuario malicioso escribe <code>' OR '1'='1</code> en un campo de email, puede alterar por completo el significado de la consulta.</p>` },
      { nombre: "Comparar: vulnerable vs segura", contenido: `<p class="mb-6">Toca cada versión para ver qué pasa con el mismo ataque:</p><div style="display:flex;justify-content:center;gap:1rem;margin-bottom:1rem;"><button id="btn-vulnerable" class="motor-btn simbolo-inactivo" onclick="compararInjection('vulnerable')">Concatenada</button><button id="btn-segura" class="motor-btn simbolo-inactivo" onclick="compararInjection('segura')">Parametrizada</button></div><pre class="bloque-codigo"><code id="injection-codigo" style="min-height:6rem;"><span class="code-comment">// Elige una opción arriba</span></code></pre><div id="injection-resultado" class="mt-3"></div>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "¿Por qué una consulta parametrizada ($1, $2) es inmune a SQL Injection?", opciones: ["Porque encripta los datos antes de enviarlos", "Porque el motor compila la estructura SQL antes de recibir los valores, tratándolos siempre como datos", "Porque es más rápida que concatenar texto", "Porque valida automáticamente el formato del email"], respuestaCorrecta: 1, retroalimentacion: { correcta: "Exacto: la consulta se compila y analiza ANTES de que lleguen los valores. Cuando llegan, solo se insertan como datos literales, nunca como código ejecutable.", incorrecta: "No es un tema de velocidad ni de encriptación. Piensa en el orden: ¿qué pasa primero, la compilación del SQL o el envío de los valores?" } }
  },

  // === FASE 5-4: Modificar datos: INSERT, UPDATE, DELETE ===
  {
    fase: 5, titulo: "Modificar datos: INSERT, UPDATE, DELETE", menuTitulo: "INSERT, UPDATE, DELETE",
    capas: [
      { nombre: "Las 3 operaciones", contenido: `<p class="mb-6">Todas siguen el mismo patrón: SQL con <code>$1</code>, <code>$2</code> y un arreglo de valores. Toca cada una:</p><div style="display:flex;justify-content:center;gap:0.5rem;margin-bottom:1rem;flex-wrap:wrap;"><button class="motor-btn simbolo-inactivo" data-sql="insert" onclick="mostrarSqlOp('insert')">INSERT</button><button class="motor-btn simbolo-inactivo" data-sql="update" onclick="mostrarSqlOp('update')">UPDATE</button><button class="motor-btn simbolo-inactivo" data-sql="delete" onclick="mostrarSqlOp('delete')">DELETE</button></div><pre class="bloque-codigo"><code id="sql-op-codigo" style="min-height:5rem;"><span class="code-comment">// Elige una operación arriba</span></code></pre>` },
      { nombre: "RETURNING: recuperar el ID generado", contenido: `<p class="mb-6">Por defecto, un INSERT no te devuelve el registro creado. <code>RETURNING</code> lo obliga a hacerlo, evitando una segunda consulta:</p><pre class="bloque-codigo"><code><span class="code-keyword">const</span> sql = <span class="code-string">'INSERT INTO usuarios (email) VALUES ($1) RETURNING id'</span>;\n<span class="code-keyword">const</span> resultado = <span class="code-keyword">await</span> pool.<span class="code-method">query</span>(sql, [<span class="code-string">'correo@test.com'</span>]);\n\n<span class="code-comment">// Sin hacer una segunda consulta, ya tenemos el ID</span>\n<span class="code-keyword">const</span> nuevoId = resultado.rows[<span class="code-number">0</span>].id;</code></pre>` },
      { nombre: "rowCount: verificar si existía", contenido: `<p class="mb-6">Un UPDATE o DELETE sobre un ID que no existe <strong>no lanza error</strong>: simplemente no afecta ninguna fila. <code>rowCount</code> es la única forma de saberlo:</p><pre class="bloque-codigo"><code><span class="code-keyword">const</span> resultado = <span class="code-keyword">await</span> pool.<span class="code-method">query</span>(\n  <span class="code-string">'UPDATE usuarios SET estado = $1 WHERE id = $2'</span>,\n  [<span class="code-string">'inactivo'</span>, <span class="code-number">9999</span>]  <span class="code-comment">// este ID no existe</span>\n);\n\n<span class="code-keyword">if</span> (resultado.rowCount === <span class="code-number">0</span>) {\n  <span class="code-comment">// La consulta "funcionó" pero no encontró el registro</span>\n  <span class="code-comment">// Aquí devuelves un 404, no un 200</span>\n}</code></pre>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "Ejecutas un DELETE con un id que no existe en la tabla. ¿Qué pasa?", opciones: ["PostgreSQL lanza un error", "La promesa se resuelve con éxito, pero rowCount es 0", "El servidor se cae", "Se elimina el primer registro de la tabla por error"], respuestaCorrecta: 1, retroalimentacion: { correcta: "Exacto: no es un error, la consulta es válida. Simplemente no había ninguna fila que coincidiera, así que rowCount queda en 0.", incorrecta: "PostgreSQL no lanza error por no encontrar coincidencias en un WHERE. La consulta se ejecuta bien, solo que no afecta ninguna fila." } }
  },

  // === FASE 5-5: Transacciones y ACID ===
  {
    fase: 5, titulo: "Transacciones y propiedades ACID", menuTitulo: "Transacciones",
    capas: [
      { nombre: "¿Por qué agrupar consultas?", contenido: `<p class="mb-6">Si transfieres saldo entre dos cuentas, necesitas <strong>restar de una y sumar a la otra</strong>. Si el servidor falla justo entre esos dos pasos, el dinero desaparece del sistema. Una <strong>transacción</strong> garantiza "todo o nada".</p>` },
      { nombre: "Las 4 propiedades ACID", contenido: `<p class="mb-6">Toca cada letra:</p><div style="display:flex;justify-content:center;gap:0.5rem;margin-bottom:1rem;flex-wrap:wrap;"><button class="motor-btn simbolo-inactivo" data-acid="a" onclick="mostrarAcid('a')">A</button><button class="motor-btn simbolo-inactivo" data-acid="c" onclick="mostrarAcid('c')">C</button><button class="motor-btn simbolo-inactivo" data-acid="i" onclick="mostrarAcid('i')">I</button><button class="motor-btn simbolo-inactivo" data-acid="d" onclick="mostrarAcid('d')">D</button></div><div id="acid-desc" style="max-width:30rem;margin:0 auto;min-height:5rem;"></div>` },
      { nombre: "BEGIN, COMMIT, ROLLBACK", contenido: `<p class="mb-6">Una transacción necesita un <strong>único cliente</strong> reservado (no un Pool que reparte conexiones). Toca cada paso del flujo:</p><div style="display:flex;flex-direction:column;gap:0.5rem;max-width:30rem;margin:0 auto;"><div class="flujo-paso flujo-activo" onclick="avanzarTransaccion(0)"><span class="flujo-num">1</span><div><strong>pool.connect()</strong><br><span style="font-size:0.8rem;opacity:0.7;">Reserva un cliente exclusivo del pool</span></div></div><div class="flujo-paso flujo-pendiente" onclick="avanzarTransaccion(1)"><span class="flujo-num">2</span><div><strong>BEGIN</strong><br><span style="font-size:0.8rem;opacity:0.7;">Inicia el bloque de transacción</span></div></div><div class="flujo-paso flujo-pendiente" onclick="avanzarTransaccion(2)"><span class="flujo-num">3</span><div><strong>Las consultas (UPDATE, UPDATE...)</strong><br><span style="font-size:0.8rem;opacity:0.7;">Se ejecutan sobre ese mismo cliente</span></div></div><div class="flujo-paso flujo-pendiente" onclick="avanzarTransaccion(3)"><span class="flujo-num">4</span><div><strong>COMMIT o ROLLBACK</strong><br><span style="font-size:0.8rem;opacity:0.7;">Todo sale bien → COMMIT. Algo falla → ROLLBACK</span></div></div><div class="flujo-paso flujo-pendiente" onclick="avanzarTransaccion(4)"><span class="flujo-num">5</span><div><strong>client.release()</strong><br><span style="font-size:0.8rem;opacity:0.7;">Devuelve el cliente al pool (siempre, en un finally)</span></div></div></div>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "En una transferencia bancaria, la resta de la cuenta origen se ejecuta bien, pero la suma a la cuenta destino falla. ¿Qué debe pasar?", opciones: ["Se hace COMMIT de la resta y se reintenta la suma después", "Se hace ROLLBACK: se revierte también la resta", "El dinero queda restado y nunca se resuelve", "No importa, ambas operaciones son independientes"], respuestaCorrecta: 1, retroalimentacion: { correcta: "Exacto: es la propiedad de Atomicidad. Si una parte de la transacción falla, TODO se revierte, como si nada hubiera pasado.", incorrecta: "Recuerda la 'A' de ACID: Atomicidad. Todo o nada. Si falla una parte, no puedes dejar la otra aplicada a medias." } }
  },

  // === FASE 5-6: Manejo de errores de conexión ===
  {
    fase: 5, titulo: "Manejo de errores de conexión", menuTitulo: "Errores de conexión",
    capas: [
      { nombre: "¿Qué puede fallar?", contenido: `<p class="mb-6">Conectarse a una base de datos en producción puede fallar por varias razones:</p><table><thead><tr><th>Problema</th><th>Ejemplo</th></tr></thead><tbody><tr><td>Servidor caído</td><td>PostgreSQL se reinició o se quedó sin RAM</td></tr><tr><td>Bloqueo de red</td><td>El puerto 5432 está bloqueado por un firewall</td></tr><tr><td>Credenciales incorrectas</td><td>La contraseña en .env cambió y nadie la actualizó</td></tr><tr><td>Saturación</td><td>Se alcanzó el límite máximo de conexiones simultáneas</td></tr></tbody></table><div class="recuadro-resaltado mt-4">Sin try/catch, cualquiera de estos errores puede tumbar completamente tu servidor Express.</div>` },
      { nombre: "Reintentos con backoff", contenido: `<p class="mb-6">En vez de reintentar inmediatamente (lo que satura la red sin dar tiempo a recuperarse), se espera <strong>cada vez más tiempo</strong> entre intento e intento. Toca cada intento para ver el patrón:</p><div style="display:flex;justify-content:center;gap:0.5rem;margin-bottom:1rem;flex-wrap:wrap;"><button class="motor-btn simbolo-inactivo" onclick="mostrarBackoff(1)">Intento 1</button><button class="motor-btn simbolo-inactivo" onclick="mostrarBackoff(2)">Intento 2</button><button class="motor-btn simbolo-inactivo" onclick="mostrarBackoff(3)">Intento 3</button><button class="motor-btn simbolo-inactivo" onclick="mostrarBackoff(4)">Intento 4</button></div><div id="backoff-resultado" class="text-center" style="min-height:3rem;font-size:0.95rem;font-weight:600;"></div>` },
      { nombre: "El código completo", contenido: `<pre class="bloque-codigo"><code><span class="code-keyword">const</span> esperar = (ms) => <span class="code-keyword">new</span> Promise((resolve) => setTimeout(resolve, ms));\n\n<span class="code-keyword">async function</span> <span class="code-method">conectarConReintentos</span>(maxIntentos = <span class="code-number">5</span>) {\n  <span class="code-keyword">let</span> intento = <span class="code-number">1</span>;\n\n  <span class="code-keyword">while</span> (intento <= maxIntentos) {\n    <span class="code-keyword">try</span> {\n      <span class="code-keyword">const</span> client = <span class="code-keyword">await</span> pool.<span class="code-method">connect</span>();\n      client.<span class="code-method">release</span>();\n      console.<span class="code-method">log</span>(<span class="code-string">'Conectado con éxito'</span>);\n      <span class="code-keyword">return</span>;\n    } <span class="code-keyword">catch</span> (error) {\n      <span class="code-keyword">if</span> (intento === maxIntentos) <span class="code-keyword">throw</span> error;\n\n      <span class="code-comment">// Backoff exponencial: 1s, 2s, 4s, 8s...</span>\n      <span class="code-keyword">const</span> tiempoEspera = <span class="code-number">1000</span> * Math.<span class="code-method">pow</span>(<span class="code-number">2</span>, intento - <span class="code-number">1</span>);\n      <span class="code-keyword">await</span> <span class="code-method">esperar</span>(tiempoEspera);\n      intento++;\n    }\n  }\n}</code></pre>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "¿Por qué es mejor esperar cada vez más tiempo entre reintentos (backoff), en vez de reintentar inmediatamente una y otra vez?", opciones: ["Porque hace que el código sea más corto", "Porque le da tiempo real al sistema para recuperarse, en vez de saturarlo con reintentos inútiles", "Porque PostgreSQL lo exige por configuración", "No hay ninguna ventaja real"], respuestaCorrecta: 1, retroalimentacion: { correcta: "Exacto: reintentar sin esperar satura la red sin darle tiempo al servidor de recuperarse. Esperar progresivamente aumenta las probabilidades de éxito en el siguiente intento.", incorrecta: "Piensa: si el servidor está caído, ¿reintentar cada 10 milisegundos ayuda en algo, o solo agrega más carga inútil?" } }
  },
];
