export const tarjetas = [

  // === FASE 6-1: Qué es un ORM ===
  {
    fase: 6, titulo: "¿Qué es un ORM?", menuTitulo: "¿Qué es un ORM?",
    capas: [
      { nombre: "El problema que resuelve", contenido: `<p class="mb-6">PostgreSQL guarda datos en tablas, filas y columnas. JavaScript trabaja con objetos y clases. Un <strong>ORM</strong> (Object-Relational Mapping) es la capa que traduce automáticamente entre ambos mundos.</p><table><thead><tr><th>Sin ORM (pg puro)</th><th>Con Sequelize</th></tr></thead><tbody><tr><td>Escribes SQL a mano en cada consulta</td><td>Llamas métodos sobre clases de JavaScript</td></tr><tr><td>Mapeas result.rows manualmente</td><td>El ORM devuelve instancias listas para usar</td></tr><tr><td>Sin autocompletado del editor</td><td>Tu editor sugiere propiedades y métodos</td></tr></tbody></table>` },
      { nombre: "Comparar código: pg vs Sequelize", contenido: `<p class="mb-6">Toca cada versión para ver el mismo INSERT:</p><div style="display:flex;justify-content:center;gap:1rem;margin-bottom:1rem;"><button id="btn-pg" class="motor-btn simbolo-inactivo" onclick="compararOrm('pg')">Con pg (SQL manual)</button><button id="btn-sequelize" class="motor-btn simbolo-inactivo" onclick="compararOrm('sequelize')">Con Sequelize</button></div><pre class="bloque-codigo"><code id="orm-codigo" style="min-height:5rem;"><span class="code-comment">// Elige una opción arriba</span></code></pre>` },
      { nombre: "Qué ganas y qué pierdes", contenido: `<p class="mb-6">Adoptar un ORM tiene beneficios claros, pero también implica renunciar a algo:</p><table><thead><tr><th>Ganas</th><th>Pierdes</th></tr></thead><tbody><tr><td>Código más limpio y legible</td><td>Rendimiento en operaciones masivas</td></tr><tr><td>Protección automática contra SQL Injection</td><td>Control granular absoluto del SQL generado</td></tr><tr><td>createdAt/updatedAt automáticos</td><td>—</td></tr><tr><td>Portabilidad entre motores de BD</td><td>—</td></tr></tbody></table><p class="mt-4">Se instala con: <code>npm install sequelize pg pg-hstore</code></p>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "¿Por qué Sequelize necesita también el paquete pg instalado, si Sequelize ya es el ORM?", opciones: ["No lo necesita, es opcional", "pg es el driver de red real; Sequelize delega en él la comunicación TCP con PostgreSQL", "pg es solo para desarrollo, no para producción", "Sequelize y pg son el mismo paquete con nombres distintos"], respuestaCorrecta: 1, retroalimentacion: { correcta: "Exacto: Sequelize no habla directamente por la red. Usa pg por debajo para la conexión física con PostgreSQL.", incorrecta: "Sequelize es una capa de abstracción, pero necesita un driver real para comunicarse por la red. Ese driver es pg." } }
  },

  // === FASE 6-2: Clases de ES6 ===
  {
    fase: 6, titulo: "Clases de ES6: la base del ORM", menuTitulo: "Clases ES6",
    capas: [
      { nombre: "Los 4 conceptos clave", contenido: `<p class="mb-6">Sequelize usa clases de JavaScript para definir modelos. Toca cada concepto:</p><div style="display:flex;justify-content:center;gap:0.5rem;margin-bottom:1rem;flex-wrap:wrap;"><button class="motor-btn simbolo-inactivo" data-clase="class" onclick="mostrarConceptoClase('class')">class</button><button class="motor-btn simbolo-inactivo" data-clase="constructor" onclick="mostrarConceptoClase('constructor')">constructor</button><button class="motor-btn simbolo-inactivo" data-clase="extends" onclick="mostrarConceptoClase('extends')">extends</button><button class="motor-btn simbolo-inactivo" data-clase="super" onclick="mostrarConceptoClase('super')">super()</button></div><div id="clase-concepto-desc" style="max-width:30rem;margin:0 auto;min-height:5rem;"></div>` },
      { nombre: "get y set", contenido: `<p class="mb-6">Un <strong>getter</strong> intercepta la lectura de una propiedad; un <strong>setter</strong> intercepta su escritura, permitiendo validar antes de guardar. Se usan sin paréntesis, como si fueran propiedades normales.</p><pre class="bloque-codigo"><code><span class="code-keyword">class</span> Servidor {\n  <span class="code-method">constructor</span>() {\n    this._estado = <span class="code-string">'inactivo'</span>;\n  }\n\n  <span class="code-keyword">get</span> <span class="code-method">estado</span>() {\n    <span class="code-keyword">return</span> this._estado.<span class="code-method">toUpperCase</span>();\n  }\n\n  <span class="code-keyword">set</span> <span class="code-method">estado</span>(nuevo) {\n    <span class="code-keyword">const</span> validos = [<span class="code-string">'activo'</span>, <span class="code-string">'inactivo'</span>];\n    <span class="code-keyword">if</span> (validos.<span class="code-method">includes</span>(nuevo)) this._estado = nuevo;\n  }\n}\n\n<span class="code-keyword">const</span> s = <span class="code-keyword">new</span> Servidor();\ns.estado = <span class="code-string">'activo'</span>;   <span class="code-comment">// usa el SET, sin paréntesis</span>\nconsole.<span class="code-method">log</span>(s.estado);  <span class="code-comment">// usa el GET → 'ACTIVO'</span></code></pre>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "Una clase ServidorExpress extiende de RecursoRed. ¿Qué línea debe ir primero, obligatoriamente, dentro del constructor de ServidorExpress?", opciones: ["this.framework = framework;", "super(ip, puerto);", "console.log('creado');", "new RecursoRed();"], respuestaCorrecta: 1, retroalimentacion: { correcta: "Exacto: super() debe llamarse antes que cualquier otra línea, para que la clase padre inicialice sus propiedades primero.", incorrecta: "JavaScript exige que super() se ejecute antes de usar 'this' en el constructor de una clase hija. Sin eso, ni siquiera compila." } }
  },

  // === FASE 6-3: Definir un modelo ===
  {
    fase: 6, titulo: "Definir un modelo en Sequelize", menuTitulo: "Definir un modelo",
    capas: [
      { nombre: "Dos formas de definir un modelo", contenido: `<p class="mb-6">Toca cada una:</p><div style="display:flex;justify-content:center;gap:1rem;margin-bottom:1rem;"><button id="btn-define" class="motor-btn simbolo-inactivo" onclick="compararDefinicionModelo('define')">sequelize.define()</button><button id="btn-init" class="motor-btn simbolo-inactivo" onclick="compararDefinicionModelo('init')">class + Model.init()</button></div><div id="definicion-modelo-desc" style="max-width:30rem;margin:0 auto;min-height:6rem;"></div>` },
      { nombre: "El modelo completo con DataTypes y validaciones", contenido: `<pre class="bloque-codigo"><code><span class="code-keyword">import</span> { Model, DataTypes } <span class="code-keyword">from</span> <span class="code-string">'sequelize'</span>;\n\n<span class="code-keyword">class</span> Usuario <span class="code-keyword">extends</span> Model {}\n\nUsuario.<span class="code-method">init</span>({\n  nombre: {\n    type: DataTypes.STRING,\n    allowNull: <span class="code-keyword">false</span>,  <span class="code-comment">// restricción física: NOT NULL</span>\n    validate: { notEmpty: <span class="code-keyword">true</span> }  <span class="code-comment">// validación del ORM</span>\n  },\n  email: {\n    type: DataTypes.STRING,\n    unique: <span class="code-keyword">true</span>,\n    validate: { isEmail: <span class="code-keyword">true</span> }\n  },\n  edad: {\n    type: DataTypes.INTEGER,\n    validate: { min: <span class="code-number">18</span> }\n  }\n}, {\n  sequelize: conexion,\n  modelName: <span class="code-string">'Usuario'</span>,\n  tableName: <span class="code-string">'usuarios'</span>\n});</code></pre>` },
      { nombre: "sequelize.sync()", contenido: `<p class="mb-6">Crea las tablas físicas en PostgreSQL a partir de tus modelos:</p><table><thead><tr><th>Comando</th><th>Qué hace</th></tr></thead><tbody><tr><td><code>sequelize.sync()</code></td><td>Crea las tablas que aún no existen</td></tr><tr><td><code>sequelize.sync({ force: true })</code></td><td><strong>Borra</strong> las tablas existentes (DROP TABLE) y las recrea desde cero</td></tr></tbody></table><div class="recuadro-resaltado mt-4"><code>{ force: true }</code> elimina todos los datos permanentemente. Solo se usa en desarrollo, nunca en producción.</div>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "¿Qué le pasa a los datos existentes si ejecutas sequelize.sync({ force: true }) en una base de datos con información real?", opciones: ["No pasa nada, es seguro", "Se eliminan por completo: las tablas se borran y se recrean vacías", "Se guardan en un respaldo automático", "Solo se actualiza la estructura, los datos se conservan"], respuestaCorrecta: 1, retroalimentacion: { correcta: "Exacto: force:true ejecuta DROP TABLE antes de recrear. Es destructivo e irreversible. Nunca se usa en producción.", incorrecta: "force:true no es una actualización segura: literalmente borra las tablas primero. Todo lo que había en ellas desaparece." } }
  },

  // === FASE 6-4: CRUD con Sequelize ===
  {
    fase: 6, titulo: "CRUD con Sequelize", menuTitulo: "CRUD con Sequelize",
    capas: [
      { nombre: "Los 5 métodos", contenido: `<p class="mb-6">Toca cada método para ver su código y el SQL equivalente que genera por detrás:</p><div style="display:flex;justify-content:center;gap:0.4rem;margin-bottom:1rem;flex-wrap:wrap;"><button class="motor-btn simbolo-inactivo" data-crud2="create" onclick="mostrarCrudSequelize('create')">create</button><button class="motor-btn simbolo-inactivo" data-crud2="findAll" onclick="mostrarCrudSequelize('findAll')">findAll</button><button class="motor-btn simbolo-inactivo" data-crud2="findByPk" onclick="mostrarCrudSequelize('findByPk')">findByPk</button><button class="motor-btn simbolo-inactivo" data-crud2="update" onclick="mostrarCrudSequelize('update')">update</button><button class="motor-btn simbolo-inactivo" data-crud2="destroy" onclick="mostrarCrudSequelize('destroy')">destroy</button></div><pre class="bloque-codigo"><code id="crud-sequelize-codigo" style="min-height:4rem;"><span class="code-comment">// Elige un método arriba</span></code></pre><div class="consola-simulada mt-3"><div class="consola-header">SQL que genera Sequelize por detrás</div><pre id="crud-sequelize-sql" style="margin:0;background:transparent;padding:0;font-size:inherit;line-height:inherit;"><span style="opacity:0.4;">Esperando...</span></pre></div>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "¿Qué devuelve Usuario.update({ nombre: 'Nuevo' }, { where: { id: 1 } })?", opciones: ["El usuario actualizado directamente", "Un arreglo donde la primera posición es el número de filas afectadas", "true o false", "El SQL generado como string"], respuestaCorrecta: 1, retroalimentacion: { correcta: "Exacto: update() devuelve un arreglo, y el primer elemento es cuántas filas fueron modificadas.", incorrecta: "update() no devuelve el registro directamente. Devuelve un arreglo con el conteo de filas afectadas en la primera posición." } }
  },

  // === FASE 6-5: Relaciones 1:1 y 1:N ===
  {
    fase: 6, titulo: "Relaciones 1:1 y 1:N", menuTitulo: "Relaciones 1:1 y 1:N",
    capas: [
      { nombre: "hasOne, hasMany y belongsTo", contenido: `<p class="mb-6">Toca cada método:</p><div style="display:flex;justify-content:center;gap:0.5rem;margin-bottom:1rem;flex-wrap:wrap;"><button class="motor-btn simbolo-inactivo" data-rel="hasOne" onclick="mostrarRelacion('hasOne')">hasOne</button><button class="motor-btn simbolo-inactivo" data-rel="hasMany" onclick="mostrarRelacion('hasMany')">hasMany</button><button class="motor-btn simbolo-inactivo" data-rel="belongsTo" onclick="mostrarRelacion('belongsTo')">belongsTo</button></div><div id="relacion-desc" style="max-width:30rem;margin:0 auto;min-height:5rem;"></div>` },
      { nombre: "Clave foránea y CASCADE", contenido: `<pre class="bloque-codigo"><code><span class="code-comment">// Un Usuario tiene muchas Publicaciones</span>\nUsuario.<span class="code-method">hasMany</span>(Publicacion, {\n  foreignKey: <span class="code-string">'usuarioId'</span>,  <span class="code-comment">// columna creada en 'publicaciones'</span>\n  onDelete: <span class="code-string">'CASCADE'</span>       <span class="code-comment">// si se borra el usuario, se borran sus posts</span>\n});\n\n<span class="code-comment">// Cada Publicación pertenece a un Usuario</span>\nPublicacion.<span class="code-method">belongsTo</span>(Usuario, {\n  foreignKey: <span class="code-string">'usuarioId'</span>\n});</code></pre><div class="recuadro-resaltado mt-4">Sin <code>onDelete: 'CASCADE'</code>, borrar un usuario dejaría sus publicaciones "huérfanas": apuntando a un <code>usuarioId</code> que ya no existe.</div>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "Un Usuario tiene muchas Publicaciones. ¿En qué modelo va foreignKey con belongsTo?", opciones: ["En Usuario", "En Publicacion (el modelo hijo)", "En ambos por igual", "No se necesita, Sequelize lo infiere solo"], respuestaCorrecta: 1, retroalimentacion: { correcta: "Exacto: belongsTo va en el modelo hijo (Publicacion), porque es la publicación la que 'pertenece a' un usuario y contiene la clave foránea.", incorrecta: "Piensa en la dirección de la relación: ¿quién apunta a quién? La publicación apunta al usuario, no al revés." } }
  },

  // === FASE 6-6: Relaciones N:M y eager loading ===
  {
    fase: 6, titulo: "Relaciones N:M y eager loading", menuTitulo: "Relaciones N:M",
    capas: [
      { nombre: "La tabla intermedia", contenido: `<p class="mb-6">Una relación N:M (muchos a muchos) necesita una <strong>tabla puente</strong> que guarda pares de claves foráneas. Sequelize la crea automáticamente con <code>through</code>:</p><pre class="bloque-codigo"><code>Estudiante.<span class="code-method">belongsToMany</span>(Curso, {\n  through: <span class="code-string">'estudiante_cursos'</span>,  <span class="code-comment">// nombre de la tabla intermedia</span>\n  foreignKey: <span class="code-string">'estudianteId'</span>\n});\n\nCurso.<span class="code-method">belongsToMany</span>(Estudiante, {\n  through: <span class="code-string">'estudiante_cursos'</span>,\n  foreignKey: <span class="code-string">'cursoId'</span>\n});</code></pre>` },
      { nombre: "Métodos autogenerados", contenido: `<p class="mb-6">Al declarar <code>belongsToMany</code>, Sequelize agrega métodos automáticos a cada instancia. Toca cada uno:</p><div style="display:flex;justify-content:center;gap:0.5rem;margin-bottom:1rem;flex-wrap:wrap;"><button class="motor-btn simbolo-inactivo" data-metodoauto="add" onclick="mostrarMetodoAuto('add')">addCurso()</button><button class="motor-btn simbolo-inactivo" data-metodoauto="set" onclick="mostrarMetodoAuto('set')">setCursos()</button><button class="motor-btn simbolo-inactivo" data-metodoauto="get" onclick="mostrarMetodoAuto('get')">getCursos()</button><button class="motor-btn simbolo-inactivo" data-metodoauto="remove" onclick="mostrarMetodoAuto('remove')">removeCurso()</button></div><div id="metodo-auto-desc" style="max-width:30rem;margin:0 auto;min-height:4rem;"></div>` },
      { nombre: "Eager loading con include", contenido: `<p class="mb-6"><strong>Eager loading</strong> trae el registro principal junto con sus relaciones en <strong>una sola consulta</strong> (usando JOIN por detrás), evitando el problema de hacer N consultas adicionales en un bucle:</p><pre class="bloque-codigo"><code><span class="code-keyword">const</span> estudiante = <span class="code-keyword">await</span> Estudiante.<span class="code-method">findByPk</span>(id, {\n  include: { model: Curso }  <span class="code-comment">// trae los cursos en la MISMA consulta</span>\n});\n\nestudiante.Cursos.<span class="code-method">forEach</span>(curso => {\n  console.<span class="code-method">log</span>(curso.titulo);\n});</code></pre><div class="recuadro-resaltado mt-4">Sin <code>include</code>, tendrías que hacer una consulta para el estudiante y luego, en un bucle, una consulta más por cada curso. Eso se llama el problema "N+1 queries".</div>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "¿Qué problema de rendimiento evita usar include (eager loading) en vez de consultar las relaciones en un bucle separado?", opciones: ["El problema de SQL Injection", "El problema de N+1 queries (una consulta extra por cada elemento del bucle)", "El problema de ACID", "El problema de CORS"], respuestaCorrecta: 1, retroalimentacion: { correcta: "Exacto: sin include, traerías el registro principal y luego harías una consulta adicional por cada relación en un bucle. Con include, todo va en una sola consulta con JOIN.", incorrecta: "No es un tema de seguridad ni de transacciones. Es un problema de rendimiento clásico llamado 'N+1 queries'." } }
  },
];
