export const tarjetas = [

  // === FASE 1-1: ¿Qué es Node.js? ===
  {
    fase: 1, titulo: "¿Qué es Node.js?", menuTitulo: "¿Qué es Node.js?",
    capas: [
      { nombre: "JavaScript estaba encerrado", contenido: `<p class="mb-6">Históricamente, JavaScript solo podía ejecutarse <strong>dentro de un navegador web</strong> (Chrome, Firefox, Safari). No podía acceder al disco duro, ni crear servidores, ni hacer nada fuera de la página web.</p><div style="display:flex;justify-content:center;gap:2rem;align-items:center;margin:2rem 0;flex-wrap:wrap;"><div style="text-align:center;padding:1.5rem;border:2px dashed rgba(51,64,42,0.2);border-radius:1rem;min-width:8rem;"><svg class="w-8 h-8 mx-auto mb-2" style="color:#33402A;opacity:0.5;" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M12 21a9.004 9.004 0 0 0 8.716-6.747M12 21a9.004 9.004 0 0 1-8.716-6.747M12 21c2.485 0 4.5-4.03 4.5-9S14.485 3 12 3m0 18c-2.485 0-4.5-4.03-4.5-9S9.515 3 12 3m0 0a8.997 8.997 0 0 1 7.843 4.582M12 3a8.997 8.997 0 0 0-7.843 4.582m15.686 0A11.953 11.953 0 0 1 12 10.5c-2.998 0-5.74-1.1-7.843-2.918m15.686 0A8.959 8.959 0 0 1 21 12c0 .778-.099 1.533-.284 2.253m0 0A17.919 17.919 0 0 1 12 16.5a17.92 17.92 0 0 1-8.716-2.247m0 0A9.015 9.015 0 0 1 3 12c0-1.605.42-3.113 1.157-4.418"/></svg><p style="font-weight:600;font-size:0.85rem;">Navegador</p><p style="font-size:0.8rem;opacity:0.6;">JS vive aquí</p></div><div style="font-size:1.5rem;opacity:0.3;">→</div><div style="text-align:center;padding:1.5rem;border:2px solid #339933;border-radius:1rem;min-width:8rem;background:rgba(51,153,51,0.05);"><svg class="w-8 h-8 mx-auto mb-2" style="color:#339933;" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M5.25 14.25h13.5m-13.5 0a3 3 0 0 1-3-3m3 3a3 3 0 1 0 0 6h13.5a3 3 0 1 0 0-6m-16.5-3a3 3 0 0 1 3-3h13.5a3 3 0 0 1 3 3m-19.5 0a4.5 4.5 0 0 1 .9-2.7L5.737 5.1a3.375 3.375 0 0 1 2.7-1.35h7.126c1.062 0 2.062.5 2.7 1.35l2.587 3.45a4.5 4.5 0 0 1 .9 2.7m0 0a3 3 0 0 1-3 3m0 3h.008v.008h-.008v-.008Zm0-6h.008v.008h-.008v-.008Z"/></svg><p style="font-weight:600;font-size:0.85rem;color:#339933;">Node.js</p><p style="font-size:0.8rem;opacity:0.6;">JS corre en cualquier computador</p></div></div><p>Un <strong>entorno de ejecución</strong> (<em>runtime</em>) es el software que toma tu código JavaScript (que es solo texto) y lo convierte en instrucciones que el procesador de la computadora puede ejecutar. <strong>Node.js</strong> es ese entorno, pero fuera del navegador.</p>` },
      { nombre: "El motor V8", contenido: `<p class="mb-6">Dentro de Chrome hay un componente llamado <strong>V8</strong>: es el motor que traduce JavaScript a código de máquina (el lenguaje que entiende el procesador). Es ultrarrápido porque compila directamente, sin pasos intermedios.</p><div style="display:flex;justify-content:center;align-items:center;gap:0.75rem;margin:2rem 0;flex-wrap:wrap;"><div style="background:#2B231B;color:#EAD9B8;padding:0.75rem 1.25rem;border-radius:0.5rem;font-family:'JetBrains Mono',monospace;font-size:0.85rem;">app.js</div><div style="font-size:1.2rem;opacity:0.4;">→</div><div style="background:#339933;color:white;padding:0.75rem 1.25rem;border-radius:0.5rem;font-weight:700;font-size:0.9rem;">V8</div><div style="font-size:1.2rem;opacity:0.4;">→</div><div style="background:#33402A;color:#FBF5E9;padding:0.75rem 1.25rem;border-radius:0.5rem;font-family:'JetBrains Mono',monospace;font-size:0.85rem;">01100101</div></div><p>Node.js tomó ese motor V8, lo sacó del navegador y le agregó herramientas del sistema operativo (acceso a archivos, red, procesos). Eso es lo que permite que JS corra en un servidor.</p>` },
      { nombre: "¿Qué desbloqueó Node.js?", contenido: `<p class="mb-6">Toca cada capacidad para revelarla:</p><div style="display:flex;flex-direction:column;gap:0.5rem;max-width:28rem;margin:0 auto;"><div class="cap-item" data-cap="0" onclick="revelarCapacidad(0)"><span class="cap-icono">?</span><span class="cap-texto">Leer y escribir archivos en el disco</span></div><div class="cap-item" data-cap="1" onclick="revelarCapacidad(1)"><span class="cap-icono">?</span><span class="cap-texto">Crear servidores web que reciben peticiones</span></div><div class="cap-item" data-cap="2" onclick="revelarCapacidad(2)"><span class="cap-icono">?</span><span class="cap-texto">Acceder a variables del sistema operativo</span></div><div class="cap-item" data-cap="3" onclick="revelarCapacidad(3)"><span class="cap-icono">?</span><span class="cap-texto">Conectarse a bases de datos</span></div></div><div class="recuadro-resaltado mt-6">Nada de esto es posible desde un navegador. Node.js convirtió a JavaScript de un lenguaje "solo para páginas web" en un lenguaje para construir cualquier cosa.</div>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "¿Qué es Node.js?", opciones: ["Un lenguaje de programación nuevo", "Un framework como React", "Un entorno de ejecución que permite correr JS fuera del navegador", "Un navegador web especial para programadores"], respuestaCorrecta: 2, retroalimentacion: { correcta: "Exacto: Node.js no es un lenguaje ni un framework. Es el entorno que permite ejecutar JavaScript en cualquier computador, no solo en el navegador.", incorrecta: "Node.js no es un lenguaje (sigue siendo JavaScript) ni un framework. Piensa: ¿qué hace posible que JS corra en un servidor?" } }
  },

  // === FASE 1-2: Node.js vs navegador ===
  {
    fase: 1, titulo: "Node.js vs el navegador", menuTitulo: "Node vs navegador",
    capas: [
      { nombre: "Dos entornos, un lenguaje", contenido: `<p class="mb-6">JavaScript es el mismo lenguaje en ambos lados. Lo que cambia es el <strong>entorno</strong>: cada uno le da herramientas diferentes. Toca cada botón para ver qué tiene cada uno:</p><div style="display:flex;justify-content:center;gap:1rem;margin-bottom:1rem;"><button id="btn-navegador" class="motor-btn simbolo-inactivo" onclick="toggleEntorno('navegador')">Navegador</button><button id="btn-node" class="motor-btn simbolo-inactivo" onclick="toggleEntorno('node')">Node.js</button></div><div id="entorno-contenido" style="max-width:26rem;margin:0 auto;min-height:12rem;"></div>` },
      { nombre: "La regla simple", contenido: `<div class="grid grid-cols-1 md:grid-cols-2 gap-6"><div class="text-center"><h4 class="font-titulo font-semibold text-verde-oscuro mb-3 border-b border-verde-oscuro/10 pb-2">Navegador</h4><p>Lo que el <strong>usuario ve y toca</strong>: la pantalla, los botones, las animaciones, el HTML.</p><p class="mt-3" style="font-size:0.85rem;opacity:0.7;">Tiene: DOM, window, eventos del mouse</p></div><div class="text-center"><h4 class="font-titulo font-semibold text-verde-node mb-3 border-b border-verde-node/20 pb-2">Node.js</h4><p>Lo que pasa <strong>detrás de escena</strong>: guardar datos, verificar contraseñas, enviar correos.</p><p class="mt-3" style="font-size:0.85rem;opacity:0.7;">Tiene: fs, http, process, os</p></div></div><div class="recuadro-resaltado mt-6">No se reemplazan: se complementan. El navegador muestra la página, Node.js maneja los datos.</div>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "¿Cuál de estos SOLO existe en Node.js, no en el navegador?", opciones: ["document.getElementById()", "console.log()", "fs.readFile()", "fetch()"], respuestaCorrecta: 2, retroalimentacion: { correcta: "Exacto: fs (file system) es un módulo de Node.js para leer y escribir archivos. El navegador no tiene acceso al disco.", incorrecta: "Piensa: ¿cuál de estas operaciones toca el disco duro? Eso solo es posible en Node." } }
  },

  // === FASE 1-3: CommonJS vs ESM ===
  {
    fase: 1, titulo: "CommonJS vs ESM", menuTitulo: "CommonJS vs ESM",
    capas: [
      { nombre: "Dos formas de organizar código", contenido: `<p class="mb-6">Cuando un proyecto crece, divides el código en varios archivos. Para que un archivo use código de otro, necesitas un <strong>sistema de módulos</strong>. En JavaScript hay dos:</p><table><thead><tr><th></th><th>CommonJS (CJS)</th><th>ES Modules (ESM)</th></tr></thead><tbody><tr><td>Creado por</td><td>Node.js (2009)</td><td>El estándar de JavaScript (2015)</td></tr><tr><td>Exportar</td><td><code>module.exports</code></td><td><code>export</code></td></tr><tr><td>Importar</td><td><code>require()</code></td><td><code>import</code></td></tr><tr><td>Recomendado</td><td>Proyectos antiguos</td><td><strong>Proyectos nuevos</strong></td></tr></tbody></table>` },
      { nombre: "Compara el código", contenido: `<p class="mb-6">El mismo archivo, en los dos sistemas. Toca cada uno para comparar:</p><div style="display:flex;justify-content:center;gap:1rem;margin-bottom:1rem;"><button id="btn-cjs" class="motor-btn simbolo-inactivo" onclick="toggleModulo('cjs')">CommonJS</button><button id="btn-esm" class="motor-btn simbolo-inactivo" onclick="toggleModulo('esm')">ESM</button></div><pre class="bloque-codigo"><code id="modulo-codigo" style="min-height:8rem;"><span class="code-comment">// Toca un botón arriba para ver el código</span></code></pre>` },
      { nombre: "Cómo activar ESM", contenido: `<p class="mb-6">Por defecto, Node.js usa CommonJS. Hay tres formas de decirle que use ESM:</p><table><thead><tr><th>Forma</th><th>Cómo</th><th>Alcance</th></tr></thead><tbody><tr><td>En package.json</td><td><code>"type": "module"</code></td><td>Todos los .js del proyecto</td></tr><tr><td>Extensión .mjs</td><td>Renombrar el archivo a <code>.mjs</code></td><td>Solo ese archivo</td></tr><tr><td>Extensión .cjs</td><td>Renombrar a <code>.cjs</code></td><td>Fuerza CommonJS en un proyecto ESM</td></tr></tbody></table><div class="recuadro-resaltado mt-6">La forma más común es <code>"type": "module"</code> en package.json. Las extensiones <code>.mjs</code> y <code>.cjs</code> se usan para excepciones puntuales.</div>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "¿Cuál es la forma recomendada de activar ESM en todo tu proyecto?", opciones: ["Renombrar todos los archivos a .mjs", "Agregar \"type\": \"module\" en package.json", "Escribir \"use strict\" al inicio de cada archivo", "Instalar la librería esm con pnpm add"], respuestaCorrecta: 1, retroalimentacion: { correcta: "Exacto: \"type\": \"module\" en package.json activa ESM para todos los archivos .js del proyecto.", incorrecta: "Piensa: ¿qué forma aplica a todo el proyecto sin tener que renombrar cada archivo?" } }
  },

  // === FASE 1-4: Módulos nativos ===
  {
    fase: 1, titulo: "Módulos nativos de Node", menuTitulo: "Módulos nativos",
    capas: [
      { nombre: "¿Qué son?", contenido: `<p class="mb-6">Los <strong>módulos nativos</strong> son librerías que ya vienen incluidas en Node.js. No necesitas instalar nada: solo importarlos con el prefijo <code>node:</code>.</p><table><thead><tr><th>Módulo</th><th>Para qué sirve</th></tr></thead><tbody><tr><td><code>path</code></td><td>Construir rutas de archivos compatibles con cualquier sistema operativo</td></tr><tr><td><code>fs</code></td><td>Leer, escribir, crear y eliminar archivos en el disco</td></tr><tr><td><code>os</code></td><td>Obtener información del sistema (RAM, CPU, plataforma)</td></tr></tbody></table>` },
      { nombre: "Pruébalos en consola", contenido: `<p class="mb-6">Toca cada módulo para ver su código y lo que muestra en consola:</p><div style="display:flex;justify-content:center;gap:0.75rem;margin-bottom:1rem;"><button class="motor-btn simbolo-inactivo" data-mod="path" onclick="probarModulo('path')">path</button><button class="motor-btn simbolo-inactivo" data-mod="fs" onclick="probarModulo('fs')">fs</button><button class="motor-btn simbolo-inactivo" data-mod="os" onclick="probarModulo('os')">os</button></div><pre class="bloque-codigo"><code id="mod-codigo" style="min-height:4rem;"><span class="code-comment">// Elige un módulo arriba</span></code></pre><div class="consola-simulada mt-3"><div class="consola-header">Consola</div><div id="mod-consola"><span style="opacity:0.4;">Esperando...</span></div></div>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "Quieres leer el contenido de un archivo de texto en Node.js. ¿Qué módulo nativo usas?", opciones: ["path", "os", "fs", "http"], respuestaCorrecta: 2, retroalimentacion: { correcta: "Exacto: fs (file system) es el módulo para leer y escribir archivos.", incorrecta: "Piensa: ¿cuál módulo se encarga de interactuar con el sistema de archivos del disco?" } }
  },

  // === FASE 1-5: El objeto process ===
  {
    fase: 1, titulo: "El objeto process", menuTitulo: "process",
    capas: [
      { nombre: "¿Qué es process?", contenido: `<p class="mb-6"><code>process</code> es un objeto <strong>global</strong> de Node.js (no necesitas importarlo). Contiene información y control sobre el programa que se está ejecutando.</p><p class="mb-6">No existe en el navegador porque el navegador no tiene acceso al sistema operativo del usuario por motivos de seguridad.</p><table><thead><tr><th>Propiedad</th><th>Qué contiene</th></tr></thead><tbody><tr><td><code>process.env</code></td><td>Variables de entorno del sistema (contraseñas, configuración)</td></tr><tr><td><code>process.argv</code></td><td>Argumentos que escribiste al ejecutar el programa en la terminal</td></tr></tbody></table>` },
      { nombre: "process.env en acción", contenido: `<p class="mb-6"><code>process.env</code> es un objeto que contiene las <strong>variables de entorno</strong>: valores de configuración que viven fuera del código (contraseñas, puertos, claves secretas). Se definen en un archivo <code>.env</code> y se leen así:</p><pre class="bloque-codigo"><code><span class="code-comment">// Archivo .env (NO es código, es configuración)</span>\n<span class="code-string">PORT</span>=<span class="code-number">3000</span>\n<span class="code-string">DB_PASSWORD</span>=<span class="code-string">miClaveSecreta</span>\n\n<span class="code-comment">// En tu código app.js</span>\n<span class="code-keyword">const</span> puerto = process.env.<span class="code-method">PORT</span>;         <span class="code-comment">// "3000"</span>\n<span class="code-keyword">const</span> clave = process.env.<span class="code-method">DB_PASSWORD</span>;  <span class="code-comment">// "miClaveSecreta"</span></code></pre><div class="consola-simulada mt-3"><div class="consola-header">¿Por qué no poner la contraseña directamente en el código?</div><div>Porque el código se sube a GitHub y cualquiera podría verla. Las variables de entorno se guardan en <code>.env</code>, que va en el <code>.gitignore</code> (nunca se sube).</div></div>` },
      { nombre: "process.argv en acción", contenido: `<p class="mb-6"><code>process.argv</code> es un arreglo (<em>array</em>) que contiene cada palabra que escribiste en la terminal al ejecutar tu programa. Toca cada ejemplo para ver qué contiene:</p><div style="display:flex;justify-content:center;gap:0.75rem;margin-bottom:1rem;flex-wrap:wrap;"><button class="motor-btn simbolo-inactivo" onclick="simularArgv('basico')">node app.js</button><button class="motor-btn simbolo-inactivo" onclick="simularArgv('args')">node app.js --port=4000</button></div><pre class="bloque-codigo"><code id="argv-terminal" style="min-height:1rem;"><span class="code-comment">// Elige un comando arriba</span></code></pre><div class="consola-simulada mt-3"><div class="consola-header">console.log(process.argv)</div><div id="argv-resultado"><span style="opacity:0.4;">Esperando...</span></div></div>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "¿Por qué process no existe en el navegador?", opciones: ["Porque es un módulo que hay que instalar", "Porque el navegador no tiene acceso al sistema operativo", "Porque solo funciona con CommonJS", "Porque requiere permisos de administrador"], respuestaCorrecta: 1, retroalimentacion: { correcta: "Exacto: el navegador está aislado del sistema operativo por seguridad. No puede acceder a procesos, variables de entorno ni argumentos de terminal.", incorrecta: "Piensa: ¿por qué el navegador no puede acceder a las contraseñas del sistema ni a la terminal?" } }
  },

  // === FASE 1-6: Asincronía ===
  {
    fase: 1, titulo: "Asincronía y async/await", menuTitulo: "Asincronía",
    capas: [
      { nombre: "¿Por qué existe la asincronía?", contenido: `<p class="mb-6">Node.js usa <strong>un solo hilo</strong> para ejecutar tu código. Si una operación lenta (leer un archivo, consultar una base de datos) bloquea ese hilo, <strong>nadie más puede ser atendido</strong> hasta que termine.</p><p>La asincronía resuelve esto: Node inicia la tarea lenta, sigue con lo demás, y vuelve cuando la tarea termina.</p>` },
      { nombre: "Síncrono vs asíncrono", contenido: `<p class="mb-6">Toca cada botón para ver cómo se ejecuta el mismo programa. Fíjate en el <strong>orden</strong> de la consola:</p><div style="display:flex;justify-content:center;gap:1rem;margin-bottom:1rem;"><button id="btn-sync" class="motor-btn simbolo-inactivo" onclick="ejecutarCodigo('sync')">Síncrono</button><button id="btn-async" class="motor-btn simbolo-inactivo" onclick="ejecutarCodigo('async')">Asíncrono</button></div><pre class="bloque-codigo"><code id="async-codigo" style="min-height:6rem;"><span class="code-comment">// Elige una opción arriba</span></code></pre><div class="consola-simulada mt-3"><div class="consola-header">Consola</div><pre id="async-consola" style="margin:0;background:transparent;padding:0;font-size:inherit;line-height:inherit;"><span style="opacity:0.4;">Esperando...</span></pre></div>` },
      { nombre: "Los 3 estados de una Promesa", contenido: `<p class="mb-6">Una <strong>Promesa</strong> (<em>Promise</em>) es un objeto que representa el resultado futuro de una operación asíncrona. Toca cada estado para ver el código que lo produce:</p><div style="display:flex;justify-content:center;gap:0.75rem;margin-bottom:1rem;flex-wrap:wrap;"><button class="promesa-estado" data-estado="pending" onclick="simularPromesa('pending')">Pending</button><button class="promesa-estado" data-estado="fulfilled" onclick="simularPromesa('fulfilled')">Fulfilled</button><button class="promesa-estado" data-estado="rejected" onclick="simularPromesa('rejected')">Rejected</button></div><pre class="bloque-codigo"><code id="promesa-codigo" style="min-height:4rem;"><span class="code-comment">// Toca un estado arriba</span></code></pre><div class="consola-simulada mt-3"><div class="consola-header">Resultado</div><pre id="promesa-salida" style="margin:0;background:transparent;padding:0;font-size:inherit;line-height:inherit;"><span style="opacity:0.4;">Toca un estado...</span></pre></div>` },
      { nombre: "async/await", contenido: `<p class="mb-6"><code>async/await</code> es una forma más limpia de trabajar con promesas. En vez de encadenar <code>.then()</code>, escribes código que se lee como si fuera síncrono:</p><pre class="bloque-codigo"><code><span class="code-keyword">import</span> fs <span class="code-keyword">from</span> <span class="code-string">'node:fs/promises'</span>;\n\n<span class="code-keyword">async function</span> <span class="code-method">leerArchivo</span>() {\n  <span class="code-keyword">try</span> {\n    <span class="code-comment">// await pausa aquí hasta que el archivo termine de leerse</span>\n    <span class="code-keyword">const</span> contenido = <span class="code-keyword">await</span> fs.<span class="code-method">readFile</span>(<span class="code-string">'config.json'</span>, <span class="code-string">'utf-8'</span>);\n    console.<span class="code-method">log</span>(contenido);  <span class="code-comment">// solo se ejecuta cuando la lectura terminó</span>\n  } <span class="code-keyword">catch</span> (error) {\n    <span class="code-comment">// si el archivo no existe o hay un error, cae aquí</span>\n    console.<span class="code-method">log</span>(<span class="code-string">'Error:'</span>, error.message);\n  }\n}\n\n<span class="code-method">leerArchivo</span>();</code></pre><table class="mt-4"><thead><tr><th>Pieza</th><th>Qué hace</th></tr></thead><tbody><tr><td><code>async</code></td><td>Marca la función como asíncrona. Siempre retorna una promesa.</td></tr><tr><td><code>await</code></td><td>Pausa la función hasta que la promesa se resuelva. Solo funciona dentro de <code>async</code>.</td></tr><tr><td><code>try/catch</code></td><td>Captura errores si la promesa es rechazada (ej: archivo no existe).</td></tr></tbody></table>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "¿En qué orden aparecen los mensajes?\n\nconsole.log('A');\nawait fs.readFile('archivo.txt');\nconsole.log('B');", opciones: ["A, B (en orden, await espera)", "B, A (se invierte)", "A (solo se muestra el primero)", "Depende de la velocidad del disco"], respuestaCorrecta: 0, retroalimentacion: { correcta: "Exacto: await pausa la función hasta que la lectura termine, así que B espera. El orden es A, luego B.", incorrecta: "Recuerda: await detiene la ejecución dentro de la función hasta que la promesa se resuelva." } }
  },

  // === FASE 1-7: Event Loop y Thread Pool ===
  {
    fase: 1, titulo: "Event Loop y Thread Pool", menuTitulo: "Event Loop",
    capas: [
      { nombre: "El motor de la asincronía", contenido: `<p class="mb-6">JavaScript en Node.js ejecuta todo tu código en <strong>un único hilo principal</strong>. El <strong>Event Loop</strong> (bucle de eventos) es el mecanismo que hace posible que, con un solo hilo, el servidor haga varias cosas "a la vez" sin bloquearse.</p><p class="mb-6">Cuando tu código lanza una operación lenta (leer un archivo, consultar PostgreSQL), Node <strong>no espera ahí parado</strong>. Delega la tarea, sigue con lo demás, y vuelve cuando la tarea avisa que terminó. Toca cada paso para ver el ciclo:</p><div style="display:flex;flex-direction:column;gap:0.5rem;max-width:30rem;margin:0 auto;"><div class="flujo-paso flujo-activo" onclick="avanzarEventLoop(0)"><span class="flujo-num">1</span><div><strong>Tu código se ejecuta</strong><br><span style="font-size:0.8rem;opacity:0.7;">El hilo principal corre línea por línea, de forma síncrona</span></div></div><div class="flujo-paso flujo-pendiente" onclick="avanzarEventLoop(1)"><span class="flujo-num">2</span><div><strong>Llega una tarea lenta</strong><br><span style="font-size:0.8rem;opacity:0.7;">Node la delega (al sistema operativo o al Thread Pool) y sigue adelante</span></div></div><div class="flujo-paso flujo-pendiente" onclick="avanzarEventLoop(2)"><span class="flujo-num">3</span><div><strong>La tarea termina en segundo plano</strong><br><span style="font-size:0.8rem;opacity:0.7;">Su callback se coloca en la "cola de callbacks" (callback queue)</span></div></div><div class="flujo-paso flujo-pendiente" onclick="avanzarEventLoop(3)"><span class="flujo-num">4</span><div><strong>El Event Loop revisa: ¿está vacía la pila?</strong><br><span style="font-size:0.8rem;opacity:0.7;">Si el hilo principal ya no tiene código síncrono pendiente, toma el callback de la cola y lo ejecuta</span></div></div></div>` },
      { nombre: "Hilo principal vs Thread Pool", contenido: `<p class="mb-6">Algunas operaciones (como <code>crypto</code> o ciertas de <code>fs</code>) son demasiado pesadas para resolverlas solo con el hilo principal. Ahí entra el <strong>Thread Pool</strong>: un grupo de hilos auxiliares administrados por <strong>libuv</strong> (la librería de bajo nivel de Node). Toca cada uno para comparar:</p><div style="display:flex;justify-content:center;gap:1rem;margin-bottom:1rem;"><button id="btn-hilo-principal" class="motor-btn simbolo-inactivo" onclick="compararHilos('principal')">Hilo principal</button><button id="btn-thread-pool" class="motor-btn simbolo-inactivo" onclick="compararHilos('pool')">Thread Pool</button></div><div id="hilos-resultado" style="max-width:28rem;margin:0 auto;min-height:6rem;"></div>` },
      { nombre: "El Callback Hell", contenido: `<p class="mb-6">Antes de las Promesas, encadenar varias operaciones asíncronas dependientes entre sí obligaba a anidar callbacks uno dentro de otro. El código crecía hacia la derecha, formando lo que se conoce como <strong>Callback Hell</strong> ("infierno de callbacks"):</p><pre class="bloque-codigo"><code><span class="code-comment">// Buscar usuario → validar permisos → consultar historial → guardar log</span>\n<span class="code-method">buscarUsuario</span>(id, (err, usuario) => {\n  <span class="code-keyword">if</span> (err) <span class="code-keyword">return</span> <span class="code-method">manejarError</span>(err);\n\n  <span class="code-method">obtenerPermisos</span>(usuario.rol, (err, permisos) => {\n    <span class="code-keyword">if</span> (err) <span class="code-keyword">return</span> <span class="code-method">manejarError</span>(err);\n\n    <span class="code-method">consultarHistorial</span>(usuario.id, (err, historial) => {\n      <span class="code-keyword">if</span> (err) <span class="code-keyword">return</span> <span class="code-method">manejarError</span>(err);\n\n      <span class="code-method">guardarLog</span>(usuario.id, (err) => {\n        <span class="code-keyword">if</span> (err) <span class="code-keyword">return</span> <span class="code-method">manejarError</span>(err);\n        console.<span class="code-method">log</span>(<span class="code-string">'Listo'</span>);\n      });\n    });\n  });\n});</code></pre><div class="recuadro-resaltado mt-4">Cada nivel de anidamiento agrega una capa de indentación. Con 4 operaciones ya es difícil de leer. Con 8, es prácticamente imposible de mantener.</div>` },
      { nombre: "Cómo se resolvió", contenido: `<p class="mb-6">Toca cada solución para ver el mismo flujo, resuelto:</p><div style="display:flex;justify-content:center;gap:1rem;margin-bottom:1rem;"><button id="btn-promesas" class="motor-btn simbolo-inactivo" onclick="mostrarSolucion('promesas')">Con Promesas</button><button id="btn-asyncawait" class="motor-btn simbolo-inactivo" onclick="mostrarSolucion('asyncawait')">Con async/await</button></div><pre class="bloque-codigo"><code id="solucion-codigo" style="min-height:8rem;"><span class="code-comment">// Elige una opción arriba</span></code></pre>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "¿Por qué el Event Loop necesita que la pila de llamadas (call stack) esté vacía antes de ejecutar un callback pendiente?", opciones: ["Es una regla arbitraria de Node.js", "Porque Node solo tiene un hilo: no puede ejecutar dos cosas de JavaScript al mismo tiempo", "Porque los callbacks son más lentos que el código normal", "No es necesario, se ejecutan en paralelo"], respuestaCorrecta: 1, retroalimentacion: { correcta: "Exacto: al ser single-thread, el hilo principal solo puede hacer una cosa a la vez. Debe terminar el código síncrono actual antes de atender el siguiente callback.", incorrecta: "Recuerda: Node.js ejecuta JavaScript en un solo hilo. Si ese hilo está ocupado con código síncrono, no puede simultáneamente ejecutar un callback." } }
  },

];
