export const tarjetas = [

  // === FASE 9-1: Qué es JWT y por qué es stateless ===
  {
    fase: 9, titulo: "¿Qué es JWT y por qué es stateless?", menuTitulo: "¿Qué es JWT?",
    capas: [
      { nombre: "El problema de la autenticación en HTTP", contenido: `<p class="mb-6">HTTP es <strong>stateless</strong>: cada petición es aislada, el servidor no recuerda nada de la anterior. Pero necesitas restringir acceso a ciertas rutas. La solución: que cada petición traiga su propia prueba de identidad.</p><p><strong>JWT</strong> (JSON Web Token) es un estándar para transmitir esa identidad como un objeto JSON firmado digitalmente, en vez de guardar una sesión en el servidor.</p>` },
      { nombre: "El flujo completo", contenido: `<p class="mb-6">Toca cada paso:</p><div style="display:flex;flex-direction:column;gap:0.5rem;max-width:30rem;margin:0 auto;"><div class="flujo-paso flujo-activo" onclick="avanzarFlujoJwt(0)"><span class="flujo-num">1</span><div><strong>Emisión</strong><br><span style="font-size:0.8rem;opacity:0.7;">El cliente envía usuario/contraseña. El servidor los valida y firma un token con los datos básicos.</span></div></div><div class="flujo-paso flujo-pendiente" onclick="avanzarFlujoJwt(1)"><span class="flujo-num">2</span><div><strong>Transporte</strong><br><span style="font-size:0.8rem;opacity:0.7;">El cliente guarda el token en su almacenamiento local.</span></div></div><div class="flujo-paso flujo-pendiente" onclick="avanzarFlujoJwt(2)"><span class="flujo-num">3</span><div><strong>Verificación</strong><br><span style="font-size:0.8rem;opacity:0.7;">En cada petición protegida, el cliente envía el token. El servidor verifica su firma.</span></div></div></div>` },
      { nombre: "Por qué escala mejor que las sesiones", contenido: `<p class="mb-6">Con sesiones tradicionales (stateful), el servidor guarda el estado en memoria. Si tienes varios servidores detrás de un balanceador de carga, esto se rompe:</p><table><thead><tr><th></th><th>Sesiones (stateful)</th><th>JWT (stateless)</th></tr></thead><tbody><tr><td>Petición llega al Servidor A, luego al B</td><td>El Servidor B no conoce la sesión creada en A</td><td>Cualquier servidor valida el token con la misma clave secreta</td></tr><tr><td>Escalar horizontalmente</td><td>Necesita caché centralizado (ej. Redis)</td><td>Funciona sin infraestructura extra</td></tr></tbody></table>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "¿Por qué la autenticación con JWT es más fácil de escalar a varios servidores que las sesiones tradicionales?", opciones: ["Porque JWT es más corto de escribir", "Porque cualquier servidor puede verificar el token matemáticamente, sin consultar un estado guardado en memoria", "Porque JWT no necesita clave secreta", "Porque los tokens JWT nunca expiran"], respuestaCorrecta: 1, retroalimentacion: { correcta: "Exacto: la verificación es una operación matemática local con la clave secreta. No hace falta que el servidor 'recuerde' nada de antes.", incorrecta: "Piensa: con sesiones, el servidor que la creó es el único que la conoce. Con JWT, ¿qué necesita cualquier servidor para validar el token?" } }
  },

  // === FASE 9-2: Anatomía de un token ===
  {
    fase: 9, titulo: "Anatomía de un token JWT", menuTitulo: "Anatomía del token",
    capas: [
      { nombre: "Las 3 partes", contenido: `<p class="mb-6">Un JWT es un string dividido en 3 partes por puntos: <code>header.payload.signature</code>. Toca cada una:</p><div style="display:flex;justify-content:center;gap:0.5rem;margin-bottom:1rem;flex-wrap:wrap;"><button class="motor-btn simbolo-inactivo" data-jwt="header" onclick="mostrarParteJwt('header')">Header</button><button class="motor-btn simbolo-inactivo" data-jwt="payload" onclick="mostrarParteJwt('payload')">Payload</button><button class="motor-btn simbolo-inactivo" data-jwt="signature" onclick="mostrarParteJwt('signature')">Signature</button></div><div id="parte-jwt-desc" style="max-width:30rem;margin:0 auto;min-height:6rem;"></div>` },
      { nombre: "Los claims del payload", contenido: `<pre class="bloque-codigo"><code>{\n  <span class="code-string">"sub"</span>: <span class="code-number">105</span>,          <span class="code-comment">// Subject: a quién pertenece el token</span>\n  <span class="code-string">"iat"</span>: <span class="code-number">1785900000</span>,  <span class="code-comment">// Issued At: cuándo se creó</span>\n  <span class="code-string">"exp"</span>: <span class="code-number">1785900900</span>   <span class="code-comment">// Expiration: cuándo deja de ser válido</span>\n}</code></pre><div class="recuadro-resaltado mt-4">Si la hora actual supera <code>exp</code>, el servidor rechaza el token automáticamente, sin importar que la firma sea válida.</div>` },
      { nombre: "Base64URL: codificar no es encriptar", contenido: `<p class="mb-6">El Header y el Payload se codifican en <strong>Base64URL</strong> (una variante de Base64 segura para URLs). Esto es solo para transportar el JSON de forma limpia, <strong>no oculta la información</strong>.</p><div class="recuadro-resaltado">Cualquiera puede decodificar el header y el payload sin la clave secreta. Por eso, <strong>nunca</strong> pongas contraseñas ni datos sensibles dentro del payload de un JWT.</div>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "¿Por qué NUNCA debes guardar la contraseña del usuario dentro del payload de un JWT?", opciones: ["Porque el payload tiene un límite de tamaño muy pequeño", "Porque el payload solo está codificado en Base64URL, no encriptado: cualquiera puede leerlo", "Porque jwt.sign() no acepta strings largos", "No hay ningún problema en hacerlo"], respuestaCorrecta: 1, retroalimentacion: { correcta: "Exacto: Base64URL es reversible por cualquiera, sin necesidad de la clave secreta. El payload es público, solo la firma está protegida.", incorrecta: "El problema no es de tamaño. Es que Base64URL no es encriptación: cualquiera con el token puede leer el contenido del payload." } }
  },

  // === FASE 9-3: Generar un token ===
  {
    fase: 9, titulo: "Generar un token: jwt.sign()", menuTitulo: "jwt.sign()",
    capas: [
      { nombre: "Los 3 parámetros de jwt.sign()", contenido: `<p class="mb-6">Toca cada parámetro:</p><div style="display:flex;justify-content:center;gap:0.5rem;margin-bottom:1rem;flex-wrap:wrap;"><button class="motor-btn simbolo-inactivo" data-signparam="payload" onclick="mostrarParamSign('payload')">payload</button><button class="motor-btn simbolo-inactivo" data-signparam="secret" onclick="mostrarParamSign('secret')">secretOrPrivateKey</button><button class="motor-btn simbolo-inactivo" data-signparam="options" onclick="mostrarParamSign('options')">options</button></div><div id="param-sign-desc" style="max-width:30rem;margin:0 auto;min-height:5rem;"></div>` },
      { nombre: "Ruta de login completa", contenido: `<pre class="bloque-codigo"><code>router.<span class="code-method">post</span>(<span class="code-string">'/login'</span>, <span class="code-keyword">async</span> (req, res, next) => {\n  <span class="code-keyword">try</span> {\n    <span class="code-keyword">const</span> { email, password } = req.body;\n    <span class="code-keyword">const</span> usuario = <span class="code-keyword">await</span> <span class="code-method">buscarUsuarioYVerificarPassword</span>(email, password);\n\n    <span class="code-keyword">if</span> (!usuario) {\n      <span class="code-keyword">return</span> res.<span class="code-method">status</span>(<span class="code-number">401</span>).<span class="code-method">json</span>({ message: <span class="code-string">'Credenciales inválidas'</span> });\n    }\n\n    <span class="code-keyword">const</span> payload = { sub: usuario.id, rol: usuario.rol };\n    <span class="code-keyword">const</span> token = jwt.<span class="code-method">sign</span>(payload, process.env.JWT_SECRET, {\n      algorithm: <span class="code-string">'HS256'</span>,\n      expiresIn: <span class="code-string">'15m'</span>  <span class="code-comment">// corto: si se roba, la ventana de riesgo es pequeña</span>\n    });\n\n    res.<span class="code-method">status</span>(<span class="code-number">200</span>).<span class="code-method">json</span>({ status: <span class="code-string">'success'</span>, data: { token } });\n  } <span class="code-keyword">catch</span> (error) {\n    <span class="code-method">next</span>(error);\n  }\n});</code></pre>` },
      { nombre: "Access token vs Refresh token", contenido: `<p class="mb-6">Un token de 15 minutos protege bien, pero obliga a re-loguearse seguido. Un token de 30 días protege mal si se roba. La solución: usar los dos.</p><table><thead><tr><th></th><th>Access Token</th><th>Refresh Token</th></tr></thead><tbody><tr><td>Duración</td><td>Corta (15 min)</td><td>Larga (7-30 días)</td></tr><tr><td>Uso</td><td>Cada petición a rutas protegidas</td><td>Solo para pedir un Access Token nuevo</td></tr><tr><td>¿Se puede revocar?</td><td>No (es stateless)</td><td>Sí (se guarda en la BD y se puede eliminar)</td></tr></tbody></table>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "¿Por qué se prefiere un expiresIn corto (como 15 minutos) para el Access Token?", opciones: ["Para que el servidor use menos memoria", "Si el token se roba, la ventana de tiempo en que el atacante puede usarlo es pequeña", "Porque jwt.sign() no acepta tiempos largos", "No hay ninguna razón real, es una convención sin motivo"], respuestaCorrecta: 1, retroalimentacion: { correcta: "Exacto: al ser stateless, no puedes 'apagar' un token robado. Un tiempo corto de vida limita el daño posible si eso ocurre.", incorrecta: "Piensa en el peor escenario: alguien roba el token. ¿Qué gana el sistema si ese token expira rápido?" } }
  },

  // === FASE 9-4: Middleware de verificación ===
  {
    fase: 9, titulo: "Middleware para verificar el token", menuTitulo: "Verificar el token",
    capas: [
      { nombre: "La cabecera Authorization: Bearer", contenido: `<p class="mb-6">El cliente envía el token en la cabecera <code>Authorization</code>, con el formato <strong>Bearer</strong>:</p><pre class="bloque-codigo"><code>Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...</code></pre><p class="mt-4">"Bearer" (portador) es el esquema estándar de la industria para tokens de este tipo.</p>` },
      { nombre: "Los 4 pasos del middleware", contenido: `<p class="mb-6">Toca cada paso:</p><div style="display:flex;flex-direction:column;gap:0.5rem;max-width:30rem;margin:0 auto;"><div class="flujo-paso flujo-activo" onclick="avanzarMiddlewareJwt(0)"><span class="flujo-num">1</span><div><strong>Lectura</strong><br><span style="font-size:0.8rem;opacity:0.7;">req.headers.authorization</span></div></div><div class="flujo-paso flujo-pendiente" onclick="avanzarMiddlewareJwt(1)"><span class="flujo-num">2</span><div><strong>Extracción</strong><br><span style="font-size:0.8rem;opacity:0.7;">Verifica que empiece con "Bearer " y separa el token</span></div></div><div class="flujo-paso flujo-pendiente" onclick="avanzarMiddlewareJwt(2)"><span class="flujo-num">3</span><div><strong>Verificación</strong><br><span style="font-size:0.8rem;opacity:0.7;">jwt.verify(token, claveSecreta)</span></div></div><div class="flujo-paso flujo-pendiente" onclick="avanzarMiddlewareJwt(3)"><span class="flujo-num">4</span><div><strong>Propagación</strong><br><span style="font-size:0.8rem;opacity:0.7;">Si es válido, guarda el payload en req.user y llama next()</span></div></div></div>` },
      { nombre: "El middleware completo", contenido: `<pre class="bloque-codigo"><code><span class="code-keyword">export const</span> verificarToken = (req, res, next) => {\n  <span class="code-keyword">const</span> authHeader = req.headers.authorization;\n\n  <span class="code-keyword">if</span> (!authHeader || !authHeader.<span class="code-method">startsWith</span>(<span class="code-string">'Bearer '</span>)) {\n    <span class="code-keyword">return</span> res.<span class="code-method">status</span>(<span class="code-number">401</span>).<span class="code-method">json</span>({ message: <span class="code-string">'Sin token válido'</span> });\n  }\n\n  <span class="code-keyword">const</span> token = authHeader.<span class="code-method">split</span>(<span class="code-string">' '</span>)[<span class="code-number">1</span>];\n\n  <span class="code-keyword">try</span> {\n    <span class="code-keyword">const</span> decoded = jwt.<span class="code-method">verify</span>(token, process.env.JWT_SECRET);\n    req.user = decoded;  <span class="code-comment">// disponible para el controlador siguiente</span>\n    <span class="code-method">next</span>();\n  } <span class="code-keyword">catch</span> (error) {\n    <span class="code-keyword">return</span> res.<span class="code-method">status</span>(<span class="code-number">401</span>).<span class="code-method">json</span>({ message: <span class="code-string">'Token inválido o expirado'</span> });\n  }\n};\n\n<span class="code-comment">// Proteger una ruta:</span>\nrouter.<span class="code-method">get</span>(<span class="code-string">'/perfil'</span>, verificarToken, obtenerPerfil);</code></pre>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "En router.get('/perfil', verificarToken, obtenerPerfil), ¿qué pasa si verificarToken NO llama a next()?", opciones: ["obtenerPerfil se ejecuta de todas formas", "obtenerPerfil nunca se ejecuta; la petición termina en la respuesta que dio verificarToken", "Express lanza un error de servidor", "El middleware se ejecuta en un bucle infinito"], respuestaCorrecta: 1, retroalimentacion: { correcta: "Exacto: sin next(), Express no avanza al siguiente eslabón. Si verificarToken ya envió una respuesta (como el 401), ahí termina el flujo.", incorrecta: "Recuerda cómo funcionan los middlewares: sin next(), no se pasa al siguiente. obtenerPerfil jamás se alcanza." } }
  },

  // === FASE 9-5: Dónde guardar el token ===
  {
    fase: 9, titulo: "Dónde guardar el token en el cliente", menuTitulo: "Guardar el token",
    capas: [
      { nombre: "Las 3 opciones", contenido: `<p class="mb-6">Toca cada una:</p><div style="display:flex;justify-content:center;gap:0.5rem;margin-bottom:1rem;flex-wrap:wrap;"><button class="motor-btn simbolo-inactivo" data-storage="local" onclick="mostrarStorage('local')">localStorage</button><button class="motor-btn simbolo-inactivo" data-storage="session" onclick="mostrarStorage('session')">sessionStorage</button><button class="motor-btn simbolo-inactivo" data-storage="cookie" onclick="mostrarStorage('cookie')">Cookies</button></div><div id="storage-desc" style="max-width:30rem;margin:0 auto;min-height:5rem;"></div>` },
      { nombre: "XSS vs CSRF: no hay opción perfecta", contenido: `<p class="mb-6">Toca cada riesgo:</p><div style="display:flex;justify-content:center;gap:1rem;margin-bottom:1rem;"><button id="btn-xss" class="motor-btn simbolo-inactivo" onclick="compararXssCsrf('xss')">XSS</button><button id="btn-csrf" class="motor-btn simbolo-inactivo" onclick="compararXssCsrf('csrf')">CSRF</button></div><div id="xss-csrf-desc" style="max-width:30rem;margin:0 auto;min-height:7rem;"></div><div class="recuadro-resaltado mt-4">localStorage te protege de CSRF pero expone a XSS. Cookies con HttpOnly te protegen de XSS pero exponen a CSRF. Es un balance, no una solución perfecta.</div>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "Guardas el JWT en localStorage. Tu sitio tiene una vulnerabilidad XSS. ¿Qué puede hacer un atacante?", opciones: ["Nada, localStorage está protegido por el navegador", "Ejecutar localStorage.getItem('token') desde el script inyectado y robar el token", "Solo puede leer cookies, no localStorage", "El ataque XSS no afecta a JWT de ninguna forma"], respuestaCorrecta: 1, retroalimentacion: { correcta: "Exacto: cualquier script que corra en tu página (incluido uno inyectado por XSS) tiene acceso libre a localStorage. Puede robar el token y enviarlo a un servidor externo.", incorrecta: "localStorage es accesible por cualquier JavaScript que corra en la página, incluyendo scripts maliciosos inyectados por XSS." } }
  },

  // === FASE 9-6: Consumir una ruta protegida ===
  {
    fase: 9, titulo: "Consumir una ruta protegida desde el cliente", menuTitulo: "Consumir con fetch",
    capas: [
      { nombre: "Configurar el header en fetch()", contenido: `<pre class="bloque-codigo"><code><span class="code-keyword">const</span> respuesta = <span class="code-keyword">await</span> <span class="code-method">fetch</span>(<span class="code-string">'/api/perfil'</span>, {\n  method: <span class="code-string">'GET'</span>,\n  headers: {\n    <span class="code-string">'Authorization'</span>: \`Bearer \${token}\`  <span class="code-comment">// el token se inyecta en el string</span>\n  }\n});</code></pre><p class="mt-4">El segundo parámetro de <code>fetch()</code> es un objeto de configuración. La clave <code>Authorization</code> es exactamente la que tu middleware espera leer.</p>` },
      { nombre: "El flujo completo: login + consulta protegida", contenido: `<pre class="bloque-codigo"><code><span class="code-keyword">let</span> accessToken = <span class="code-keyword">null</span>;\n\n<span class="code-keyword">async function</span> <span class="code-method">iniciarSesion</span>(email, password) {\n  <span class="code-keyword">const</span> respuesta = <span class="code-keyword">await</span> <span class="code-method">fetch</span>(<span class="code-string">'/api/login'</span>, {\n    method: <span class="code-string">'POST'</span>,\n    headers: { <span class="code-string">'Content-Type'</span>: <span class="code-string">'application/json'</span> },\n    body: JSON.<span class="code-method">stringify</span>({ email, password })\n  });\n  <span class="code-keyword">const</span> datos = <span class="code-keyword">await</span> respuesta.<span class="code-method">json</span>();\n  <span class="code-keyword">if</span> (datos.status === <span class="code-string">'success'</span>) {\n    accessToken = datos.data.token;  <span class="code-comment">// guardamos el token</span>\n  }\n}\n\n<span class="code-keyword">async function</span> <span class="code-method">consultarPerfil</span>() {\n  <span class="code-keyword">const</span> respuesta = <span class="code-keyword">await</span> <span class="code-method">fetch</span>(<span class="code-string">'/api/perfil'</span>, {\n    headers: { <span class="code-string">'Authorization'</span>: \`Bearer \${accessToken}\` }  <span class="code-comment">// lo reutilizamos</span>\n  });\n  <span class="code-keyword">const</span> datos = <span class="code-keyword">await</span> respuesta.<span class="code-method">json</span>();\n  console.<span class="code-method">log</span>(datos);\n}</code></pre>` },
      { nombre: "Manejar el 401", contenido: `<p class="mb-6">Si el token expiró o es inválido, el servidor responde <code>401</code>. El cliente debe manejarlo, no solo mostrar el JSON crudo:</p><pre class="bloque-codigo"><code><span class="code-keyword">if</span> (respuesta.status === <span class="code-number">401</span>) {\n  console.<span class="code-method">error</span>(<span class="code-string">'Sesión expirada, inicia sesión de nuevo'</span>);\n  <span class="code-comment">// aquí normalmente redirigirías al login</span>\n}</code></pre>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "¿Por qué el header se escribe como 'Authorization': `Bearer ${token}` y no solo 'Authorization': token?", opciones: ["Es lo mismo, no hay diferencia", "El servidor espera el formato exacto 'Bearer <token>' con la palabra Bearer y un espacio antes del token", "Bearer es el nombre de la librería usada", "Es solo una convención decorativa sin efecto real"], respuestaCorrecta: 1, retroalimentacion: { correcta: "Exacto: el middleware busca específicamente el prefijo 'Bearer ' para saber que ahí empieza el token. Sin ese formato exacto, authHeader.startsWith('Bearer ') fallaría.", incorrecta: "El middleware del servidor verifica explícitamente que el header empiece con 'Bearer '. Sin ese formato, la extracción del token falla." } }
  },
];
