export const tarjetas = [

  // === FASE 3-1: ¿Qué es Express.js? ===
  {
    fase: 3, titulo: "¿Qué es Express.js?", menuTitulo: "¿Qué es Express?",
    capas: [
      { nombre: "El problema de node:http", contenido: `<p class="mb-6">Ya viste cómo crear un servidor con <code>node:http</code>. Funciona, pero es de <strong>muy bajo nivel</strong>: solo abre un canal de red y analiza texto crudo de HTTP. Todo lo demás lo tienes que programar tú.</p><p class="mb-6"><strong>Express.js</strong> es una librería que se monta sobre <code>node:http</code> y te da herramientas listas para no reinventar la rueda. Toca cada problema para ver la diferencia:</p><div style="display:flex;flex-direction:column;gap:0.5rem;max-width:30rem;margin:0 auto;" id="express-problemas"><div class="cap-item" data-cap="e0" onclick="revelarExpress(0)"><span class="cap-icono">?</span><span class="cap-texto">Gestionar rutas (/usuarios, /productos...)</span></div><div class="cap-item" data-cap="e1" onclick="revelarExpress(1)"><span class="cap-icono">?</span><span class="cap-texto">Leer datos que envía el cliente (JSON, formularios)</span></div><div class="cap-item" data-cap="e2" onclick="revelarExpress(2)"><span class="cap-icono">?</span><span class="cap-texto">Enviar respuestas con formato correcto</span></div><div class="cap-item" data-cap="e3" onclick="revelarExpress(3)"><span class="cap-icono">?</span><span class="cap-texto">Ejecutar lógica común para todas las rutas</span></div></div><div id="express-detalle" class="mt-4" style="max-width:30rem;margin-left:auto;margin-right:auto;min-height:3rem;"></div>` },
      { nombre: "Cómo se instala", contenido: `<p class="mb-6">Express no viene con Node.js: es una librería externa que se instala con el gestor de paquetes.</p><pre class="bloque-codigo"><code><span class="code-comment">// Instalar Express en tu proyecto</span>\n<span class="code-method">pnpm add</span> <span class="code-string">express</span></code></pre><p class="mt-6">Al ejecutar ese comando, pasan dos cosas automáticamente:</p><table class="mt-2"><thead><tr><th>Qué pasa</th><th>Dónde</th></tr></thead><tbody><tr><td>Se descarga el código de Express</td><td><code>node_modules/express/</code></td></tr><tr><td>Se registra como dependencia</td><td><code>package.json → dependencies</code></td></tr></tbody></table>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "¿Qué relación tiene Express con node:http?", opciones: ["Express reemplaza node:http completamente", "Express se monta sobre node:http y lo simplifica", "Son dos cosas independientes", "Express es un módulo nativo de Node"], respuestaCorrecta: 1, retroalimentacion: { correcta: "Exacto: Express usa node:http internamente. Cuando haces app.listen(), Express ejecuta http.createServer() por ti detrás de escena.", incorrecta: "Express no reemplaza node:http ni es independiente. Piensa: ¿qué hace Express cuando arrancas el servidor con app.listen()?" } }
  },

  // === FASE 3-2: Tu primer servidor con Express ===
  {
    fase: 3, titulo: "Tu primer servidor con Express", menuTitulo: "Servidor Express",
    capas: [
      { nombre: "El código completo", contenido: `<pre class="bloque-codigo"><code><span class="code-comment">// 1. Importamos Express (librería instalada con pnpm add)</span>\n<span class="code-keyword">import</span> express <span class="code-keyword">from</span> <span class="code-string">'express'</span>;\n\n<span class="code-comment">// 2. Creamos la aplicación</span>\n<span class="code-comment">//    express() devuelve un objeto con toda la funcionalidad</span>\n<span class="code-keyword">const</span> app = <span class="code-method">express</span>();\n\n<span class="code-comment">// 3. Definimos una ruta: cuando alguien visite "/", responder</span>\napp.<span class="code-method">get</span>(<span class="code-string">'/'</span>, (req, res) => {\n  res.<span class="code-method">send</span>(<span class="code-string">'Servidor Express activo'</span>);\n});\n\n<span class="code-comment">// 4. Arrancamos el servidor en el puerto 3000</span>\napp.<span class="code-method">listen</span>(<span class="code-number">3000</span>, () => {\n  console.<span class="code-method">log</span>(<span class="code-string">'Servidor en http://localhost:3000'</span>);\n});</code></pre>` },
      { nombre: "node:http vs Express", contenido: `<p class="mb-6">El mismo servidor, en ambas versiones. Toca para comparar:</p><div style="display:flex;justify-content:center;gap:1rem;margin-bottom:1rem;"><button id="btn-nativo" class="motor-btn simbolo-inactivo" onclick="compararServidor('nativo')">node:http</button><button id="btn-express" class="motor-btn simbolo-inactivo" onclick="compararServidor('express')">Express</button></div><pre class="bloque-codigo"><code id="comparar-codigo" style="min-height:8rem;"><span class="code-comment">// Elige una opción arriba</span></code></pre>` },
      { nombre: "Las piezas nuevas", contenido: `<table><thead><tr><th>Express</th><th>Qué hace</th><th>Equivalente en node:http</th></tr></thead><tbody><tr><td><code>express()</code></td><td>Crea la aplicación con toda la funcionalidad de Express</td><td><code>http.createServer()</code></td></tr><tr><td><code>app.get(ruta, fn)</code></td><td>Define qué hacer cuando llega un GET a esa ruta</td><td><code>if (req.url === '/' && req.method === 'GET')</code></td></tr><tr><td><code>res.send()</code></td><td>Envía respuesta, fija headers y cierra conexión automáticamente</td><td><code>res.setHeader() + res.end()</code></td></tr><tr><td><code>app.listen()</code></td><td>Arranca el servidor (llama a http.createServer internamente)</td><td><code>server.listen()</code></td></tr></tbody></table><div class="recuadro-resaltado mt-4">Express no reemplaza node:http: lo envuelve. Cuando escribes <code>app.listen()</code>, Express ejecuta <code>http.createServer(app)</code> internamente.</div>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "¿Cuál es la diferencia principal entre res.send() de Express y res.end() de node:http?", opciones: ["No hay diferencia, hacen lo mismo", "res.send() fija el Content-Type y el Content-Length automáticamente", "res.send() solo sirve para JSON", "res.end() es más rápido"], respuestaCorrecta: 1, retroalimentacion: { correcta: "Exacto: res.send() detecta el tipo de dato que le pasas, fija las cabeceras apropiadas y cierra la conexión. Con res.end() tienes que hacer todo eso a mano.", incorrecta: "Piensa en lo que tenías que hacer manualmente con node:http (setHeader, statusCode, end). ¿Cuántos de esos pasos hace res.send() por ti?" } }
  },

  // === FASE 3-3: Rutas y parámetros ===
  {
    fase: 3, titulo: "Rutas y parámetros", menuTitulo: "Rutas y parámetros",
    capas: [
      { nombre: "Definir rutas", contenido: `<p class="mb-6">Cada ruta combina un <strong>método HTTP</strong> (qué quiero hacer) con una <strong>URL</strong> (dónde). Express ejecuta la función solo si coinciden ambos:</p><pre class="bloque-codigo"><code><span class="code-comment">// Solo se ejecuta si el cliente envía GET a /productos</span>\napp.<span class="code-method">get</span>(<span class="code-string">'/productos'</span>, (req, res) => {\n  res.<span class="code-method">send</span>(<span class="code-string">'Lista de productos'</span>);\n});\n\n<span class="code-comment">// Solo se ejecuta si el cliente envía POST a /productos</span>\napp.<span class="code-method">post</span>(<span class="code-string">'/productos'</span>, (req, res) => {\n  res.<span class="code-method">send</span>(<span class="code-string">'Producto creado'</span>);\n});</code></pre><div class="recuadro-resaltado mt-4">La misma URL (<code>/productos</code>) puede tener funciones diferentes según el verbo. Eso es lo que aprendiste como <strong>enrutamiento semántico</strong> en la Fase 4.</div>` },
      { nombre: "params vs query", contenido: `<p class="mb-6">Hay dos formas de enviar datos en la URL. Toca cada una para comparar:</p><div style="display:flex;justify-content:center;gap:1rem;margin-bottom:1rem;"><button id="btn-params" class="motor-btn simbolo-inactivo" onclick="compararParams('params')">req.params</button><button id="btn-query" class="motor-btn simbolo-inactivo" onclick="compararParams('query')">req.query</button></div><pre class="bloque-codigo"><code id="params-codigo" style="min-height:6rem;"><span class="code-comment">// Elige una opción arriba</span></code></pre><div class="consola-simulada mt-3"><div class="consola-header">Resultado</div><pre id="params-resultado" style="margin:0;background:transparent;padding:0;font-size:inherit;line-height:inherit;"><span style="opacity:0.4;">Esperando...</span></pre></div>` },
      { nombre: "Cuándo usar cada uno", contenido: `<table><thead><tr><th></th><th>req.params</th><th>req.query</th></tr></thead><tbody><tr><td>Para qué</td><td>Identificar <strong>un</strong> recurso específico</td><td>Filtrar, ordenar o paginar</td></tr><tr><td>¿Obligatorio?</td><td>Sí (si falta, la ruta no coincide)</td><td>No (es opcional)</td></tr><tr><td>En la URL</td><td><code>/productos/<strong>45</strong></code></td><td><code>/productos?<strong>color=rojo</strong></code></td></tr><tr><td>En Express</td><td><code>app.get('/productos/:id')</code></td><td><code>app.get('/productos')</code></td></tr><tr><td>Se lee con</td><td><code>req.params.id</code></td><td><code>req.query.color</code></td></tr></tbody></table>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "Tienes la ruta app.get('/usuarios/:id'). Un cliente visita /usuarios/88. ¿Qué valor tiene req.params.id?", opciones: ["undefined", "':id'", "'88'", "88 (número)"], respuestaCorrecta: 2, retroalimentacion: { correcta: "Exacto: Express captura el valor '88' como string y lo guarda en req.params.id.", incorrecta: "Los :id en la ruta son variables. Express toma lo que el cliente puso en esa posición de la URL y lo guarda como string en req.params." } }
  },

  // === FASE 3-4: Middlewares ===
  {
    fase: 3, titulo: "Middlewares", menuTitulo: "Middlewares",
    capas: [
      { nombre: "¿Qué es un middleware?", contenido: `<p class="mb-6">Un <strong>middleware</strong> es una función que se ejecuta <strong>entre</strong> que la petición llega al servidor y que la respuesta sale. Tiene acceso a <code>req</code>, <code>res</code> y a una función especial llamada <code>next()</code>.</p><pre class="bloque-codigo"><code><span class="code-comment">// Un middleware básico: registra cada petición que llega</span>\napp.<span class="code-method">use</span>((req, res, next) => {\n  console.<span class="code-method">log</span>(<span class="code-string">'Petición recibida:'</span>, req.method, req.url);\n  <span class="code-method">next</span>();  <span class="code-comment">// pasa al siguiente middleware o ruta</span>\n});</code></pre><table class="mt-4"><thead><tr><th>Pieza</th><th>Qué hace</th></tr></thead><tbody><tr><td><code>app.use(fn)</code></td><td>Registra el middleware para <strong>todas</strong> las rutas y métodos</td></tr><tr><td><code>next()</code></td><td>Le dice a Express: "ya terminé, pasa al siguiente"</td></tr></tbody></table>` },
      { nombre: "La cadena", contenido: `<p class="mb-6">Los middlewares se ejecutan en el orden en que los escribiste. Toca cada paso para ver el flujo:</p><div style="display:flex;flex-direction:column;gap:0.5rem;max-width:30rem;margin:0 auto;"><div class="flujo-paso flujo-activo" onclick="avanzarCadena(0)"><span class="flujo-num">1</span><div><strong>express.json()</strong><br><span style="font-size:0.8rem;opacity:0.7;">Convierte los bytes del body en un objeto JS → req.body</span></div></div><div class="flujo-paso flujo-pendiente" onclick="avanzarCadena(1)"><span class="flujo-num">2</span><div><strong>Tu middleware de log</strong><br><span style="font-size:0.8rem;opacity:0.7;">Imprime "Petición recibida: GET /usuarios" → next()</span></div></div><div class="flujo-paso flujo-pendiente" onclick="avanzarCadena(2)"><span class="flujo-num">3</span><div><strong>app.get('/usuarios', fn)</strong><br><span style="font-size:0.8rem;opacity:0.7;">La ruta coincide → ejecuta la función y envía res.json()</span></div></div></div><div class="recuadro-resaltado mt-6">Si un middleware no llama a <code>next()</code> y no envía respuesta, la petición se queda <strong>colgada</strong>: el navegador esperará hasta que la conexión expire.</div>` },
      { nombre: "Middleware vs ruta", contenido: `<table><thead><tr><th></th><th>Middleware</th><th>Ruta</th></tr></thead><tbody><tr><td>Propósito</td><td>Preparar, validar, registrar</td><td>Responder al cliente</td></tr><tr><td>¿Llama next()?</td><td>Sí (pasa al siguiente)</td><td>No (es el destino final)</td></tr><tr><td>¿Envía respuesta?</td><td>Normalmente no</td><td>Sí (res.send, res.json...)</td></tr><tr><td>¿Para qué rutas?</td><td>Todas (con app.use)</td><td>Una específica (app.get('/ruta'))</td></tr></tbody></table><pre class="bloque-codigo mt-4"><code><span class="code-comment">// Middleware: prepara (no responde, llama next)</span>\napp.<span class="code-method">use</span>(express.<span class="code-method">json</span>());\n\n<span class="code-comment">// Ruta: responde (no llama next)</span>\napp.<span class="code-method">get</span>(<span class="code-string">'/usuarios'</span>, (req, res) => {\n  res.<span class="code-method">json</span>(usuarios);\n});</code></pre>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "¿Qué pasa si un middleware no llama a next() y no envía respuesta?", opciones: ["Express llama a next() automáticamente", "Se ejecuta la siguiente ruta de todos modos", "La petición se queda colgada indefinidamente", "El servidor se reinicia"], respuestaCorrecta: 2, retroalimentacion: { correcta: "Exacto: Express no sabe que el middleware terminó. Sin next() ni respuesta, el cliente se queda esperando hasta que la conexión expire por timeout.", incorrecta: "Express no asume nada: necesita que tú explícitamente llames next() o envíes una respuesta. Si no haces ninguna de las dos, ¿qué le pasa al cliente?" } }
  },

  // === FASE 3-5: Motor de plantillas EJS ===
  {
    fase: 3, titulo: "Motor de plantillas EJS", menuTitulo: "EJS",
    capas: [
      { nombre: "¿Qué es EJS?", contenido: `<p class="mb-6"><strong>EJS</strong> (<em>Embedded JavaScript</em>) es un motor de plantillas: una herramienta que permite generar HTML dinámico en el servidor, fusionando HTML estático con datos de JavaScript.</p><pre class="bloque-codigo"><code><span class="code-comment">// 1. Configurar EJS en Express</span>\napp.<span class="code-method">set</span>(<span class="code-string">'view engine'</span>, <span class="code-string">'ejs'</span>);\n\n<span class="code-comment">// 2. En la ruta, renderizar una vista pasándole datos</span>\napp.<span class="code-method">get</span>(<span class="code-string">'/usuario'</span>, (req, res) => {\n  res.<span class="code-method">render</span>(<span class="code-string">'perfil'</span>, { nombre: <span class="code-string">'Carlos'</span> });\n});\n\n<span class="code-comment">// Express busca el archivo views/perfil.ejs</span>\n<span class="code-comment">// Le pasa { nombre: 'Carlos' } como datos</span>\n<span class="code-comment">// EJS genera el HTML final y lo envía al navegador</span></code></pre>` },
      { nombre: "Las etiquetas de EJS", contenido: `<p class="mb-6">EJS usa etiquetas especiales para insertar JavaScript dentro del HTML. Toca cada tipo:</p><div style="display:flex;justify-content:center;gap:1rem;margin-bottom:1rem;"><button id="btn-ejs-salida" class="motor-btn simbolo-inactivo" onclick="mostrarEjs('salida')"><%= %> Salida</button><button id="btn-ejs-control" class="motor-btn simbolo-inactivo" onclick="mostrarEjs('control')"><% %> Control</button></div><div id="ejs-ejemplo" style="max-width:30rem;margin:0 auto;min-height:6rem;"></div>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "¿Qué diferencia hay entre <%= nombre %> y <% nombre %> en EJS?", opciones: ["No hay diferencia", "<%= %> imprime el valor en el HTML, <% %> ejecuta lógica sin imprimir", "<% %> imprime y <%= %> ejecuta", "<%= %> es para strings y <% %> para números"], respuestaCorrecta: 1, retroalimentacion: { correcta: "Exacto: el signo = hace que el valor se inserte visiblemente en el HTML. Sin él, el código se ejecuta pero no se muestra (útil para if, for, etc.).", incorrecta: "Piensa en el = como 'imprimir'. Con = se ve en la página. Sin = se ejecuta en silencio (para lógica como if o for)." } }
  },

  // === FASE 3-6: Manejo de errores ===
  {
    fase: 3, titulo: "Manejo de errores en Express", menuTitulo: "Manejo de errores",
    capas: [
      { nombre: "El middleware de error", contenido: `<p class="mb-6">Express tiene un tipo especial de middleware para errores. Lo diferencia porque recibe <strong>4 parámetros</strong> en vez de 3:</p><pre class="bloque-codigo"><code><span class="code-comment">// Middleware normal: 3 parámetros</span>\napp.<span class="code-method">use</span>((req, res, next) => { ... });\n\n<span class="code-comment">// Middleware de ERROR: 4 parámetros</span>\n<span class="code-comment">// Express sabe que es de error por el número de argumentos</span>\napp.<span class="code-method">use</span>((err, req, res, next) => {\n  console.<span class="code-method">error</span>(err.message);\n  res.<span class="code-method">status</span>(<span class="code-number">500</span>).<span class="code-method">json</span>({ error: <span class="code-string">'Error interno del servidor'</span> });\n});</code></pre><div class="recuadro-resaltado mt-4">Este middleware debe ir al <strong>final del archivo</strong>, después de todas las rutas. Si lo pones antes, no capturará errores de las rutas que vengan después.</div>` },
      { nombre: "El orden importa", contenido: `<p class="mb-6">Express procesa todo de arriba hacia abajo. Toca cada paso para ver el orden correcto:</p><div style="display:flex;flex-direction:column;gap:0.5rem;max-width:30rem;margin:0 auto;"><div class="flujo-paso flujo-activo" onclick="avanzarOrdenError(0)"><span class="flujo-num">1</span><div><strong>Middlewares globales</strong><br><span style="font-size:0.8rem;opacity:0.7;">express.json(), cors(), logs...</span></div></div><div class="flujo-paso flujo-pendiente" onclick="avanzarOrdenError(1)"><span class="flujo-num">2</span><div><strong>Rutas normales</strong><br><span style="font-size:0.8rem;opacity:0.7;">app.get(), app.post(), etc.</span></div></div><div class="flujo-paso flujo-pendiente" onclick="avanzarOrdenError(2)"><span class="flujo-num">3</span><div><strong>Middleware 404</strong><br><span style="font-size:0.8rem;opacity:0.7;">"Ninguna ruta coincidió" → res.status(404)</span></div></div><div class="flujo-paso flujo-pendiente" onclick="avanzarOrdenError(3)"><span class="flujo-num">4</span><div><strong>Middleware de error (4 params)</strong><br><span style="font-size:0.8rem;opacity:0.7;">Captura errores de las rutas → res.status(500)</span></div></div></div>` },
      { nombre: "try/catch + next(error)", contenido: `<p class="mb-6">En rutas asíncronas (<code>async</code>), Express no captura errores automáticamente. Necesitas <code>try/catch</code> y pasarle el error a <code>next()</code>:</p><pre class="bloque-codigo"><code>app.<span class="code-method">get</span>(<span class="code-string">'/usuarios/:id'</span>, <span class="code-keyword">async</span> (req, res, next) => {\n  <span class="code-keyword">try</span> {\n    <span class="code-comment">// Si esto falla (ej: la base de datos está caída)</span>\n    <span class="code-keyword">const</span> usuario = <span class="code-keyword">await</span> <span class="code-method">buscarUsuario</span>(req.params.id);\n    res.<span class="code-method">json</span>(usuario);\n  } <span class="code-keyword">catch</span> (error) {\n    <span class="code-comment">// next(error) salta directo al middleware de error</span>\n    <span class="code-method">next</span>(error);\n  }\n});</code></pre><table class="mt-4"><thead><tr><th>Sin next(error)</th><th>Con next(error)</th></tr></thead><tbody><tr><td>El error se pierde en silencio</td><td>El middleware de error lo captura</td></tr><tr><td>El cliente se queda esperando</td><td>El cliente recibe un mensaje de error</td></tr></tbody></table>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "¿Por qué el middleware de error debe ir al final del archivo?", opciones: ["Porque es más lento que los demás", "Porque Express procesa de arriba hacia abajo, y solo puede capturar errores de lo que ya pasó", "Porque solo funciona con POST", "No importa dónde se ponga"], respuestaCorrecta: 1, retroalimentacion: { correcta: "Exacto: Express procesa la pila de arriba hacia abajo. Si el middleware de error está antes de una ruta, no podrá capturar los errores que ocurran en ella.", incorrecta: "Piensa en el orden: Express lee el archivo de arriba hacia abajo. ¿Puede capturar un error de algo que todavía no ha procesado?" } }
  },
];
