export const tarjetas = [

  // === FASE 2-1: ¿Qué es una petición HTTP? ===
  {
    fase: 2, titulo: "¿Qué es una petición HTTP?", menuTitulo: "Petición HTTP",
    capas: [
      { nombre: "Cliente y servidor", contenido: `<p class="mb-6">Toda comunicación en la web ocurre entre dos programas: el <strong>cliente</strong> (quien pide) y el <strong>servidor</strong> (quien responde).</p><div class="grid grid-cols-1 md:grid-cols-2 gap-6"><div style="text-align:center;padding:1.5rem;border:2px solid rgba(51,64,42,0.15);border-radius:1rem;"><svg class="w-8 h-8 mx-auto mb-2" style="color:#5B8BD4;" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M9 17.25v1.007a3 3 0 0 1-.879 2.122L7.5 21h9l-.621-.621A3 3 0 0 1 15 18.257V17.25m6-12V15a2.25 2.25 0 0 1-2.25 2.25H5.25A2.25 2.25 0 0 1 3 15V5.25m18 0A2.25 2.25 0 0 0 18.75 3H5.25A2.25 2.25 0 0 0 3 5.25m18 0V12a2.25 2.25 0 0 1-2.25 2.25H5.25A2.25 2.25 0 0 1 3 12V5.25"/></svg><p style="font-weight:700;font-size:0.95rem;color:#5B8BD4;">Cliente</p><p style="font-size:0.85rem;">El navegador del usuario. <strong>Inicia</strong> la comunicación pidiendo datos.</p></div><div style="text-align:center;padding:1.5rem;border:2px solid #339933;border-radius:1rem;background:rgba(51,153,51,0.03);"><svg class="w-8 h-8 mx-auto mb-2" style="color:#339933;" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M5.25 14.25h13.5m-13.5 0a3 3 0 0 1-3-3m3 3a3 3 0 1 0 0 6h13.5a3 3 0 1 0 0-6m-16.5-3a3 3 0 0 1 3-3h13.5a3 3 0 0 1 3 3m-19.5 0a4.5 4.5 0 0 1 .9-2.7L5.737 5.1a3.375 3.375 0 0 1 2.7-1.35h7.126c1.062 0 2.062.5 2.7 1.35l2.587 3.45a4.5 4.5 0 0 1 .9 2.7"/></svg><p style="font-weight:700;font-size:0.95rem;color:#339933;">Servidor</p><p style="font-size:0.85rem;">Un computador que espera peticiones y <strong>responde</strong> con datos.</p></div></div>` },
      { nombre: "El ciclo completo", contenido: `<p class="mb-6"><strong>HTTP</strong> (<em>HyperText Transfer Protocol</em>) es el protocolo que define cómo se comunican el cliente y el servidor. Toca cada paso para avanzar:</p><div style="display:flex;flex-direction:column;gap:0.5rem;max-width:30rem;margin:0 auto;"><div class="flujo-paso flujo-activo" onclick="avanzarFlujo(0)"><span class="flujo-num">1</span><div><strong>El usuario hace algo</strong><br><span style="font-size:0.8rem;opacity:0.7;">Hace clic en un enlace, envía un formulario, abre una página</span></div></div><div class="flujo-paso flujo-pendiente" onclick="avanzarFlujo(1)"><span class="flujo-num">2</span><div><strong>El navegador arma la petición</strong><br><span style="font-size:0.8rem;opacity:0.7;">Método HTTP + URL + cabeceras + cuerpo (si hay datos)</span></div></div><div class="flujo-paso flujo-pendiente" onclick="avanzarFlujo(2)"><span class="flujo-num">3</span><div><strong>El servidor recibe y procesa</strong><br><span style="font-size:0.8rem;opacity:0.7;">Analiza la ruta, ejecuta la lógica, consulta datos si es necesario</span></div></div><div class="flujo-paso flujo-pendiente" onclick="avanzarFlujo(3)"><span class="flujo-num">4</span><div><strong>El servidor envía la respuesta</strong><br><span style="font-size:0.8rem;opacity:0.7;">Código de estado + cabeceras + cuerpo (HTML, JSON, etc.)</span></div></div></div>` },
      { nombre: "¿Qué viaja en cada dirección?", contenido: `<div class="grid grid-cols-1 md:grid-cols-2 gap-6"><div><h4 class="font-titulo font-semibold text-verde-oscuro mb-3 border-b border-verde-oscuro/10 pb-2" style="text-align:center;">Petición (Request)</h4><table><thead><tr><th>Parte</th><th>Qué es</th></tr></thead><tbody><tr><td><code>Método</code></td><td>La acción: GET, POST, PUT, DELETE</td></tr><tr><td><code>URL</code></td><td>La dirección del recurso</td></tr><tr><td><code>Headers</code></td><td>Metadatos (quién eres, qué aceptas)</td></tr><tr><td><code>Body</code></td><td>Datos del usuario (solo en POST/PUT)</td></tr></tbody></table></div><div><h4 class="font-titulo font-semibold text-verde-node mb-3 border-b border-verde-node/20 pb-2" style="text-align:center;">Respuesta (Response)</h4><table><thead><tr><th>Parte</th><th>Qué es</th></tr></thead><tbody><tr><td><code>Status</code></td><td>Código numérico: 200, 404, 500...</td></tr><tr><td><code>Headers</code></td><td>Metadatos (formato, tamaño)</td></tr><tr><td><code>Body</code></td><td>El contenido: HTML, JSON, imagen</td></tr></tbody></table></div></div>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "Un usuario abre Instagram en su navegador. ¿Quién es el cliente y quién es el servidor?", opciones: ["El servidor es el navegador, el cliente es Instagram", "El cliente es el navegador, el servidor es el computador de Instagram", "Ambos son clientes", "Ambos son servidores"], respuestaCorrecta: 1, retroalimentacion: { correcta: "Exacto: el navegador (cliente) pide los datos, y el computador de Instagram (servidor) responde con el feed, las fotos, etc.", incorrecta: "El cliente es quien inicia la petición pidiendo datos. El servidor es quien espera y responde. ¿Cuál de los dos pide?" } }
  },

  // === FASE 2-2: Partes de una URL ===
  {
    fase: 2, titulo: "Partes de una URL", menuTitulo: "Partes de una URL",
    capas: [
      { nombre: "Anatomía de una URL", contenido: `<p class="mb-6">Toca cada parte de la URL para ver qué significa:</p><div style="background:#2B231B;border-radius:0.5rem;padding:1.25rem;font-family:'JetBrains Mono',monospace;font-size:0.85rem;text-align:center;margin-bottom:0.5rem;display:flex;flex-wrap:wrap;justify-content:center;gap:0;line-height:2.2;"><span class="url-parte" data-url="protocolo" onclick="mostrarParteUrl('protocolo')" style="color:#C9A0DC;cursor:pointer;padding:0.15rem 0.1rem;border-radius:0.25rem;transition:all 0.2s;">https://</span><span class="url-parte" data-url="dominio" onclick="mostrarParteUrl('dominio')" style="color:#A6C58C;cursor:pointer;padding:0.15rem 0.1rem;border-radius:0.25rem;transition:all 0.2s;">www.tienda.com</span><span class="url-parte" data-url="ruta" onclick="mostrarParteUrl('ruta')" style="color:#E6B980;cursor:pointer;padding:0.15rem 0.1rem;border-radius:0.25rem;transition:all 0.2s;">/productos/buscar</span><span class="url-parte" data-url="params" onclick="mostrarParteUrl('params')" style="color:#D4976C;cursor:pointer;padding:0.15rem 0.1rem;border-radius:0.25rem;transition:all 0.2s;">?categoria=zapatos&color=rojo</span></div><div id="url-desc" class="text-center mt-4 opacity-0 transition-opacity duration-300" style="min-height:3rem;font-size:0.9rem;max-width:32rem;margin-left:auto;margin-right:auto;"></div>` },
      { nombre: "Los query params", contenido: `<p class="mb-6">Los <strong>query params</strong> son datos extra que van al final de la URL, después del <code>?</code>. Sirven para filtrar o modificar lo que pides sin cambiar la ruta.</p><pre class="bloque-codigo"><code><span class="code-comment">// La estructura es: ?clave=valor&otraClave=otroValor</span>\n\n<span class="code-string">/productos/buscar</span><span class="code-keyword">?</span><span style="color:#E6B980;">categoria</span>=<span class="code-string">zapatos</span><span class="code-keyword">&</span><span style="color:#E6B980;">color</span>=<span class="code-string">rojo</span>\n\n<span class="code-comment">// ?  → marca el inicio de los parámetros</span>\n<span class="code-comment">// &  → separa un parámetro del siguiente</span>\n<span class="code-comment">// =  → une cada clave con su valor</span></code></pre><div class="recuadro-resaltado mt-4">Los usas todo el tiempo sin darte cuenta. Cuando buscas en Google, la URL se ve así: <code>google.com/search?q=node+js</code> — el <code>q</code> es el query param con tu búsqueda.</div>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "En la URL https://api.clima.com/v2/pronostico?ciudad=santiago&dias=5, ¿cuál es la ruta (path)?", opciones: ["https://api.clima.com", "/v2/pronostico", "?ciudad=santiago&dias=5", "api.clima.com/v2"], respuestaCorrecta: 1, retroalimentacion: { correcta: "Exacto: /v2/pronostico es la ruta. Va después del dominio y antes del ? de los query params.", incorrecta: "La ruta empieza con / después del dominio y termina antes del ?. ¿Cuál parte encaja?" } }
  },

  // === FASE 2-3: Códigos de estado HTTP ===
  {
    fase: 2, titulo: "Códigos de estado HTTP", menuTitulo: "Códigos de estado",
    capas: [
      { nombre: "Las 5 familias", contenido: `<p class="mb-6">El servidor responde con un número de 3 dígitos que le dice al cliente qué pasó con su petición. La primera cifra indica la familia:</p><table><thead><tr><th>Familia</th><th>Significa</th><th>Color mental</th></tr></thead><tbody><tr><td><strong>1xx</strong></td><td>Informativa (sigue procesando)</td><td style="opacity:0.6;">Gris</td></tr><tr><td style="color:#339933;font-weight:700;">2xx</td><td>Todo bien, petición exitosa</td><td style="color:#339933;">Verde</td></tr><tr><td style="color:#5B8BD4;font-weight:700;">3xx</td><td>Redirección (el recurso se movió)</td><td style="color:#5B8BD4;">Azul</td></tr><tr><td style="color:#E6B980;font-weight:700;">4xx</td><td>Error del cliente (pediste mal)</td><td style="color:#E6B980;">Naranja</td></tr><tr><td style="color:#DC6B6B;font-weight:700;">5xx</td><td>Error del servidor (falló internamente)</td><td style="color:#DC6B6B;">Rojo</td></tr></tbody></table>` },
      { nombre: "Los códigos que más verás", contenido: `<p class="mb-6">Toca cada código para ver cuándo aparece:</p><div style="display:flex;flex-wrap:wrap;justify-content:center;gap:0.5rem;margin-bottom:1rem;"><button class="motor-btn simbolo-inactivo" onclick="mostrarCodigo(200)" style="color:#339933;font-weight:700;">200</button><button class="motor-btn simbolo-inactivo" onclick="mostrarCodigo(201)" style="color:#339933;font-weight:700;">201</button><button class="motor-btn simbolo-inactivo" onclick="mostrarCodigo(301)" style="color:#5B8BD4;font-weight:700;">301</button><button class="motor-btn simbolo-inactivo" onclick="mostrarCodigo(400)" style="color:#E6B980;font-weight:700;">400</button><button class="motor-btn simbolo-inactivo" onclick="mostrarCodigo(404)" style="color:#E6B980;font-weight:700;">404</button><button class="motor-btn simbolo-inactivo" onclick="mostrarCodigo(500)" style="color:#DC6B6B;font-weight:700;">500</button></div><div id="codigo-desc" style="max-width:30rem;margin:0 auto;min-height:4rem;"></div>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "Un usuario escribe mal la URL de una página que no existe. ¿Qué código devuelve el servidor?", opciones: ["200 OK", "400 Bad Request", "404 Not Found", "500 Internal Server Error"], respuestaCorrecta: 2, retroalimentacion: { correcta: "Exacto: 404 Not Found. El recurso que pidió el cliente no existe en el servidor.", incorrecta: "Piensa: el problema no es un error en los datos enviados (400), ni un fallo del servidor (500). Es que la página simplemente no existe." } }
  },

  // === FASE 2-4: Cabeceras HTTP ===
  {
    fase: 2, titulo: "Cabeceras HTTP (Headers)", menuTitulo: "Cabeceras HTTP",
    capas: [
      { nombre: "¿Qué son?", contenido: `<p class="mb-6">Las <strong>cabeceras</strong> (<em>headers</em>) son metadatos que viajan junto con la petición y la respuesta. No son el contenido en sí, sino <strong>instrucciones técnicas</strong> que el cliente y el servidor necesitan para comunicarse correctamente.</p><table><thead><tr><th>Dirección</th><th>Cabecera</th><th>Qué dice</th></tr></thead><tbody><tr><td rowspan="2">Petición →</td><td><code>User-Agent</code></td><td>Qué navegador eres</td></tr><tr><td><code>Accept</code></td><td>Qué formatos puedes recibir</td></tr><tr><td rowspan="2">← Respuesta</td><td><code>Content-Type</code></td><td>En qué formato está la respuesta</td></tr><tr><td><code>Content-Length</code></td><td>Cuántos bytes pesa el cuerpo</td></tr></tbody></table>` },
      { nombre: "Content-Type: la más importante", contenido: `<p class="mb-6">El servidor envía bytes crudos por la red. <code>Content-Type</code> le dice al navegador <strong>cómo interpretar esos bytes</strong>. Toca cada tipo:</p><div style="display:flex;justify-content:center;gap:0.75rem;margin-bottom:1rem;flex-wrap:wrap;"><button class="motor-btn simbolo-inactivo" onclick="mostrarContentType('html')">text/html</button><button class="motor-btn simbolo-inactivo" onclick="mostrarContentType('json')">application/json</button><button class="motor-btn simbolo-inactivo" onclick="mostrarContentType('plain')">text/plain</button></div><div id="content-type-resultado" style="max-width:30rem;margin:0 auto;min-height:5rem;"></div>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "Tu API devuelve datos de usuarios como un objeto JavaScript. ¿Qué Content-Type debe usar la respuesta?", opciones: ["text/html", "text/plain", "application/json", "text/javascript"], respuestaCorrecta: 2, retroalimentacion: { correcta: "Exacto: application/json indica que el cuerpo contiene datos JSON, el formato estándar para APIs.", incorrecta: "Piensa: estás enviando datos estructurados (un objeto), no una página HTML ni texto plano. ¿Qué formato se usa para datos?" } }
  },

  // === FASE 2-5: Tu primer servidor con node:http ===
  {
    fase: 2, titulo: "Tu primer servidor con node:http", menuTitulo: "Servidor con http",
    capas: [
      { nombre: "El código completo", contenido: `<p class="mb-6">Un servidor mínimo en Node.js, sin Express, usando solo el módulo nativo <code>node:http</code>:</p><pre class="bloque-codigo"><code><span class="code-comment">// 1. Importamos el módulo de red (viene con Node)</span>\n<span class="code-keyword">import</span> http <span class="code-keyword">from</span> <span class="code-string">'node:http'</span>;\n\n<span class="code-comment">// 2. Creamos el servidor</span>\n<span class="code-comment">//    El callback se ejecuta cada vez que alguien hace una petición</span>\n<span class="code-keyword">const</span> server = http.<span class="code-method">createServer</span>((req, res) => {\n  <span class="code-comment">// 3. Configuramos la respuesta</span>\n  res.statusCode = <span class="code-number">200</span>;                              <span class="code-comment">// código de éxito</span>\n  res.<span class="code-method">setHeader</span>(<span class="code-string">'Content-Type'</span>, <span class="code-string">'text/plain'</span>);   <span class="code-comment">// formato: texto plano</span>\n  res.<span class="code-method">end</span>(<span class="code-string">'Hola desde mi servidor'</span>);                <span class="code-comment">// envía y cierra</span>\n});\n\n<span class="code-comment">// 4. Ponemos el servidor a escuchar en el puerto 3000</span>\nserver.<span class="code-method">listen</span>(<span class="code-number">3000</span>, () => {\n  console.<span class="code-method">log</span>(<span class="code-string">'Servidor en http://localhost:3000'</span>);\n});</code></pre>` },
      { nombre: "Pieza por pieza", contenido: `<p class="mb-6">Toca cada pieza del código para ver qué hace:</p><div style="display:flex;flex-wrap:wrap;justify-content:center;gap:0.5rem;margin-bottom:1rem;"><button class="motor-btn simbolo-inactivo" onclick="explicarPieza('createServer')">createServer</button><button class="motor-btn simbolo-inactivo" onclick="explicarPieza('req')">req</button><button class="motor-btn simbolo-inactivo" onclick="explicarPieza('res')">res</button><button class="motor-btn simbolo-inactivo" onclick="explicarPieza('end')">res.end()</button><button class="motor-btn simbolo-inactivo" onclick="explicarPieza('listen')">listen</button></div><div id="pieza-desc" style="max-width:30rem;margin:0 auto;min-height:4rem;"></div>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "¿Qué pasa si no escribes res.end() en tu servidor?", opciones: ["El servidor no arranca", "La respuesta se envía igual", "El navegador se queda esperando infinitamente", "Se envía un error 500 automáticamente"], respuestaCorrecta: 2, retroalimentacion: { correcta: "Exacto: sin res.end(), el servidor nunca le dice al navegador que terminó de responder. El navegador se queda esperando hasta que la conexión expire.", incorrecta: "Piensa: res.end() es lo que cierra la conexión y envía la respuesta. Si nunca lo llamas, ¿qué le pasa al navegador que está esperando?" } }
  },

  // === FASE 2-6: JSON ===
  {
    fase: 2, titulo: "JSON: el idioma del backend", menuTitulo: "JSON",
    capas: [
      { nombre: "¿Qué es JSON?", contenido: `<p class="mb-6"><strong>JSON</strong> (<em>JavaScript Object Notation</em>) es un formato de texto para enviar datos entre el cliente y el servidor. Se parece a un objeto de JavaScript, pero tiene reglas más estrictas:</p><table><thead><tr><th></th><th>Objeto JS</th><th>JSON</th></tr></thead><tbody><tr><td>Las claves</td><td>Con o sin comillas</td><td><strong>Siempre</strong> con comillas dobles</td></tr><tr><td>Strings</td><td>Comillas simples o dobles</td><td><strong>Solo</strong> comillas dobles</td></tr><tr><td>Funciones</td><td>Permitidas</td><td>Prohibidas</td></tr><tr><td>Comentarios</td><td>Permitidos</td><td>Prohibidos</td></tr></tbody></table><div class="recuadro-resaltado mt-4">JSON no es un objeto: es texto plano. Por eso puede viajar por la red, porque las conexiones HTTP solo transmiten texto.</div>` },
      { nombre: "stringify y parse", contenido: `<p class="mb-6">JavaScript tiene dos métodos para convertir entre objeto y JSON. Toca cada uno para ver qué hace:</p><div style="display:flex;justify-content:center;gap:1rem;margin-bottom:1rem;"><button class="motor-btn simbolo-inactivo" onclick="simularJson('stringify')">JSON.stringify()</button><button class="motor-btn simbolo-inactivo" onclick="simularJson('parse')">JSON.parse()</button></div><pre class="bloque-codigo"><code id="json-codigo" style="min-height:5rem;"><span class="code-comment">// Toca un método arriba</span></code></pre><div class="consola-simulada mt-3"><div class="consola-header">Resultado</div><pre id="json-resultado" style="margin:0;background:transparent;padding:0;font-size:inherit;line-height:inherit;"><span style="opacity:0.4;">Esperando...</span></pre></div>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "Recibes datos del servidor como texto JSON. ¿Qué método usas para poder acceder a las propiedades?", opciones: ["JSON.stringify()", "JSON.parse()", "JSON.toString()", "Object.keys()"], respuestaCorrecta: 1, retroalimentacion: { correcta: "Exacto: JSON.parse() convierte el texto JSON en un objeto JavaScript que puedes usar en tu código.", incorrecta: "Piensa: tienes texto y necesitas un objeto. stringify hace lo contrario (objeto → texto). ¿Cuál convierte texto → objeto?" } }
  },
];
