export const tarjetas = [

  // === FASE 4-1: Persistencia con archivos JSON ===
  {
    fase: 4, titulo: "Persistencia con archivos JSON", menuTitulo: "¿Qué es persistir?",
    capas: [
      { nombre: "¿Qué es la persistencia?", contenido: `<p class="mb-6"><strong>Persistir datos</strong> significa que la información sobrevive después de que el programa que la creó termina. Cuando tu servidor se detiene, toda la RAM (variables, arreglos, objetos) se pierde por completo.</p><div style="display:flex;justify-content:center;align-items:center;gap:1rem;margin:1.5rem 0;flex-wrap:wrap;"><div style="text-align:center;padding:1rem 1.5rem;border:2px dashed rgba(220,107,107,0.4);border-radius:0.75rem;"><p style="font-weight:700;color:#DC6B6B;font-size:0.85rem;">RAM (volátil)</p><p style="font-size:0.8rem;opacity:0.7;">Se borra al apagar el servidor</p></div><span style="opacity:0.4;">→</span><div style="text-align:center;padding:1rem 1.5rem;border:2px solid #339933;border-radius:0.75rem;background:rgba(51,153,51,0.05);"><p style="font-weight:700;color:#339933;font-size:0.85rem;">Disco (persistente)</p><p style="font-size:0.8rem;opacity:0.7;">Sigue ahí al reiniciar</p></div></div><table><thead><tr><th>Cuándo usar archivos JSON</th><th>Cuándo NO usarlos</th></tr></thead><tbody><tr><td>Configuraciones que cambian poco</td><td>Necesitas transacciones seguras</td></tr><tr><td>Prototipos y proyectos pequeños</td><td>Múltiples escrituras simultáneas</td></tr><tr><td>Solo un proceso lee/escribe a la vez</td><td>El volumen de datos supera la RAM disponible</td></tr></tbody></table>` },
      { nombre: "Serializar y deserializar", contenido: `<p class="mb-6">El disco solo entiende <strong>texto</strong>, no objetos de JavaScript. Por eso necesitas convertir en ambas direcciones:</p><pre class="bloque-codigo"><code><span class="code-comment">// 1. Datos en memoria RAM (objeto JavaScript vivo)</span>\n<span class="code-keyword">const</span> servidores = [\n  { id: <span class="code-number">101</span>, ip: <span class="code-string">'192.168.10.5'</span>, activo: <span class="code-keyword">true</span> }\n];\n\n<span class="code-comment">// 2. Serializar: objeto → texto (para poder guardarlo)</span>\n<span class="code-keyword">const</span> textoJSON = JSON.<span class="code-method">stringify</span>(servidores, <span class="code-keyword">null</span>, <span class="code-number">2</span>);\n\n<span class="code-comment">// 3. Deserializar: texto → objeto (para poder usarlo de nuevo)</span>\n<span class="code-keyword">const</span> servidoresDeVuelta = JSON.<span class="code-method">parse</span>(textoJSON);</code></pre><div class="recuadro-resaltado mt-4">El tercer parámetro de <code>stringify</code> (el <code>2</code>) es solo estético: le dice cuántos espacios usar para indentar el JSON, para que sea legible si abres el archivo.</div>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "¿Por qué no puedes escribir directamente un objeto de JavaScript en un archivo, sin usar JSON.stringify() primero?", opciones: ["Node.js lo prohíbe por seguridad", "El sistema de archivos solo entiende texto plano, no objetos vivos de JS", "Los objetos son demasiado pesados para el disco", "Solo funciona con arreglos, no con objetos"], respuestaCorrecta: 1, retroalimentacion: { correcta: "Exacto: las funciones de escritura del sistema operativo trabajan con texto o bytes, nunca con estructuras de JavaScript en memoria.", incorrecta: "Piensa en qué formato entiende el disco duro: ¿objetos de JavaScript en memoria, o texto plano?" } }
  },

  // === FASE 4-2: Escribir y leer archivos ===
  {
    fase: 4, titulo: "Escribir y leer archivos", menuTitulo: "writeFileSync / readFileSync",
    capas: [
      { nombre: "Las dos funciones base", contenido: `<p class="mb-6">Toca cada método para ver sus parámetros:</p><div style="display:flex;justify-content:center;gap:1rem;margin-bottom:1rem;"><button id="btn-write" class="motor-btn simbolo-inactivo" onclick="mostrarFsMetodo('write')">writeFileSync</button><button id="btn-read" class="motor-btn simbolo-inactivo" onclick="mostrarFsMetodo('read')">readFileSync</button></div><div id="fs-metodo-desc" style="max-width:30rem;margin:0 auto;min-height:7rem;"></div>` },
      { nombre: "El código completo con try/catch", contenido: `<p class="mb-6">Si una operación de disco falla, Node lanza una excepción que puede tumbar tu servidor. Por eso siempre va dentro de <code>try/catch</code>:</p><pre class="bloque-codigo"><code><span class="code-keyword">import</span> fs <span class="code-keyword">from</span> <span class="code-string">'node:fs'</span>;\n\n<span class="code-keyword">const</span> ruta = <span class="code-string">'./servidores.json'</span>;\n<span class="code-keyword">const</span> servidores = [{ id: <span class="code-number">101</span>, ip: <span class="code-string">'192.168.10.5'</span> }];\n\n<span class="code-keyword">try</span> {\n  <span class="code-keyword">const</span> texto = JSON.<span class="code-method">stringify</span>(servidores, <span class="code-keyword">null</span>, <span class="code-number">2</span>);\n  fs.<span class="code-method">writeFileSync</span>(ruta, texto, <span class="code-string">'utf8'</span>);\n\n  <span class="code-keyword">const</span> leido = fs.<span class="code-method">readFileSync</span>(ruta, <span class="code-string">'utf8'</span>);\n  <span class="code-keyword">const</span> datos = JSON.<span class="code-method">parse</span>(leido);\n  console.<span class="code-method">log</span>(datos[<span class="code-number">0</span>].id);\n} <span class="code-keyword">catch</span> (error) {\n  <span class="code-keyword">if</span> (error.code === <span class="code-string">'ENOENT'</span>) {\n    console.<span class="code-method">error</span>(<span class="code-string">'El archivo no existe'</span>);\n  } <span class="code-keyword">else if</span> (error <span class="code-keyword">instanceof</span> SyntaxError) {\n    console.<span class="code-method">error</span>(<span class="code-string">'El JSON está mal formado'</span>);\n  }\n}</code></pre>` },
      { nombre: "Errores comunes de disco", contenido: `<table><thead><tr><th>Error</th><th>Cuándo ocurre</th></tr></thead><tbody><tr><td><code>ENOENT</code></td><td>El archivo o la carpeta que intentas leer no existe</td></tr><tr><td><code>EACCES</code></td><td>Node no tiene permisos para leer/escribir esa ruta</td></tr><tr><td><code>SyntaxError</code></td><td>El archivo se leyó bien, pero su contenido no es JSON válido</td></tr></tbody></table>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "fs.readFileSync() lee un archivo .json sin especificar 'utf8' como segundo parámetro. ¿Qué obtienes?", opciones: ["Un objeto JavaScript listo para usar", "Un string con el contenido del archivo", "Un Buffer (datos binarios crudos)", "undefined"], respuestaCorrecta: 2, retroalimentacion: { correcta: "Exacto: sin especificar la codificación, readFileSync devuelve un Buffer, no texto legible. Necesitas 'utf8' para obtener un string.", incorrecta: "Sin el parámetro 'utf8', Node no sabe que quieres texto legible. Te devuelve los datos binarios crudos: eso es un Buffer." } }
  },

  // === FASE 4-3: CRUD sobre un archivo JSON ===
  {
    fase: 4, titulo: "CRUD sobre un archivo JSON", menuTitulo: "CRUD con archivos",
    capas: [
      { nombre: "El patrón: leer, modificar, escribir", contenido: `<p class="mb-6">Un archivo JSON no se edita "a medias". Cada operación CRUD sigue siempre el mismo ciclo de 3 pasos. Toca cada uno:</p><div style="display:flex;flex-direction:column;gap:0.5rem;max-width:28rem;margin:0 auto;"><div class="flujo-paso flujo-activo" onclick="avanzarCicloCrud(0)"><span class="flujo-num">1</span><div><strong>Lectura completa</strong><br><span style="font-size:0.8rem;opacity:0.7;">readFileSync + JSON.parse → arreglo en memoria</span></div></div><div class="flujo-paso flujo-pendiente" onclick="avanzarCicloCrud(1)"><span class="flujo-num">2</span><div><strong>Modificación en memoria</strong><br><span style="font-size:0.8rem;opacity:0.7;">push, find, filter — el archivo en disco todavía no cambia</span></div></div><div class="flujo-paso flujo-pendiente" onclick="avanzarCicloCrud(2)"><span class="flujo-num">3</span><div><strong>Escritura completa</strong><br><span style="font-size:0.8rem;opacity:0.7;">JSON.stringify + writeFileSync → sobrescribe todo el archivo</span></div></div></div>` },
      { nombre: "Las 4 operaciones", contenido: `<p class="mb-6">Toca cada operación CRUD para ver su código:</p><div style="display:flex;justify-content:center;gap:0.5rem;margin-bottom:1rem;flex-wrap:wrap;"><button class="motor-btn simbolo-inactivo" data-crud="create" onclick="mostrarCrudArchivo('create')">Create</button><button class="motor-btn simbolo-inactivo" data-crud="read" onclick="mostrarCrudArchivo('read')">Read</button><button class="motor-btn simbolo-inactivo" data-crud="update" onclick="mostrarCrudArchivo('update')">Update</button><button class="motor-btn simbolo-inactivo" data-crud="delete" onclick="mostrarCrudArchivo('delete')">Delete</button></div><pre class="bloque-codigo"><code id="crud-archivo-codigo" style="min-height:5rem;"><span class="code-comment">// Elige una operación arriba</span></code></pre>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "Quieres eliminar el usuario con id 3 de tu archivo JSON. ¿Qué método de arreglos usas para construir la nueva lista?", opciones: ["push()", "find()", "filter()", "map()"], respuestaCorrecta: 2, retroalimentacion: { correcta: "Exacto: filter() crea un nuevo arreglo excluyendo el elemento que coincide con el id. Ese nuevo arreglo es el que se vuelve a escribir en el disco.", incorrecta: "push() agrega, find() busca uno solo sin modificar nada. Piensa: ¿cuál construye un nuevo arreglo excluyendo algo?" } }
  },

  // === FASE 4-4: Verificar, eliminar y registrar ===
  {
    fase: 4, titulo: "Verificar, eliminar y registrar eventos", menuTitulo: "existsSync, unlink, logs",
    capas: [
      { nombre: "Antes de tocar un archivo: verificar", contenido: `<p class="mb-6">Intentar leer o eliminar un archivo que no existe lanza el error <code>ENOENT</code> y puede tumbar tu servidor. <code>fs.existsSync()</code> es la compuerta de seguridad:</p><pre class="bloque-codigo"><code><span class="code-keyword">if</span> (fs.<span class="code-method">existsSync</span>(<span class="code-string">'./usuarios.json'</span>)) {\n  <span class="code-comment">// Es seguro leerlo</span>\n  <span class="code-keyword">const</span> datos = fs.<span class="code-method">readFileSync</span>(<span class="code-string">'./usuarios.json'</span>, <span class="code-string">'utf8'</span>);\n} <span class="code-keyword">else</span> {\n  <span class="code-comment">// Todavía no existe, empezar con arreglo vacío</span>\n  <span class="code-keyword">const</span> datos = [];\n}</code></pre><p class="mt-4"><code>fs.existsSync(ruta)</code> devuelve <code>true</code> o <code>false</code>. Nada más.</p>` },
      { nombre: "Eliminar y registrar (logs)", contenido: `<p class="mb-6">Toca cada método:</p><div style="display:flex;justify-content:center;gap:0.75rem;margin-bottom:1rem;"><button class="motor-btn simbolo-inactivo" data-metodo2="unlink" onclick="mostrarUnlinkAppend('unlink')">unlinkSync</button><button class="motor-btn simbolo-inactivo" data-metodo2="append" onclick="mostrarUnlinkAppend('append')">appendFileSync</button></div><div id="unlink-append-desc" style="max-width:30rem;margin:0 auto;min-height:6rem;"></div>` },
      { nombre: "Ejemplo: log con marca de tiempo", contenido: `<pre class="bloque-codigo"><code><span class="code-keyword">function</span> <span class="code-method">registrarEnBitacora</span>(accion, detalles) {\n  <span class="code-comment">// new Date().toISOString() genera la fecha y hora exacta</span>\n  <span class="code-keyword">const</span> marca = <span class="code-keyword">new</span> Date().<span class="code-method">toISOString</span>();\n\n  <span class="code-keyword">const</span> linea = <span class="code-string">\`[\${marca}] ACCION: \${accion} | \${detalles}\\n\`</span>;\n\n  <span class="code-comment">// Se agrega al final, sin borrar el historial anterior</span>\n  fs.<span class="code-method">appendFileSync</span>(<span class="code-string">'./servidor.log'</span>, linea, <span class="code-string">'utf8'</span>);\n}\n\n<span class="code-method">registrarEnBitacora</span>(<span class="code-string">'USUARIO_CREADO'</span>, <span class="code-string">'ID: 201, Nombre: Andrés'</span>);\n<span class="code-comment">// → [2026-03-14T10:22:01.000Z] ACCION: USUARIO_CREADO | ID: 201, Nombre: Andrés</span></code></pre><div class="recuadro-resaltado mt-4">Si el servidor falla en producción, este archivo de log te permite reconstruir exactamente qué pasó y en qué orden.</div>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "¿Qué diferencia hay entre fs.writeFileSync() y fs.appendFileSync()?", opciones: ["No hay diferencia", "writeFileSync borra todo el contenido anterior; appendFileSync agrega al final sin borrar", "appendFileSync es más rápido", "writeFileSync solo funciona con archivos .json"], respuestaCorrecta: 1, retroalimentacion: { correcta: "Exacto: writeFileSync sobrescribe todo el archivo desde cero. appendFileSync conserva lo que ya había y agrega texto nuevo al final. Por eso se usa para logs.", incorrecta: "Piensa en un archivo de log: si cada evento nuevo borrara los anteriores, no servería como historial. ¿Cuál de los dos métodos preserva el contenido previo?" } }
  },

  // === FASE 4-5: Manipular texto dentro de archivos ===
  {
    fase: 4, titulo: "Manipular texto dentro de archivos", menuTitulo: "truncate, path, regex",
    capas: [
      { nombre: "Vaciar un archivo sin eliminarlo", contenido: `<p class="mb-6"><code>fs.truncateSync(ruta, 0)</code> deja un archivo en <strong>0 bytes</strong>, pero el archivo sigue existiendo (con su nombre, ruta y permisos intactos).</p><table><thead><tr><th></th><th>fs.unlinkSync()</th><th>fs.truncateSync(ruta, 0)</th></tr></thead><tbody><tr><td>¿El archivo sigue existiendo?</td><td>No, se borra por completo</td><td>Sí, queda vacío pero presente</td></tr><tr><td>Uso típico</td><td>Descartar un archivo temporal</td><td>Reiniciar un log sin perder la ruta configurada</td></tr></tbody></table>` },
      { nombre: "El módulo path", contenido: `<p class="mb-6">Windows usa <code>\\</code> como separador de rutas; Mac y Linux usan <code>/</code>. Si concatenas texto a mano, tu código puede fallar al cambiar de sistema operativo.</p><pre class="bloque-codigo"><code><span class="code-comment">// Riesgoso: depende del sistema operativo</span>\n<span class="code-keyword">const</span> ruta = <span class="code-string">'./carpeta/'</span> + archivo;\n\n<span class="code-comment">// Seguro: path.join detecta el sistema operativo automáticamente</span>\n<span class="code-keyword">import</span> path <span class="code-keyword">from</span> <span class="code-string">'node:path'</span>;\n<span class="code-keyword">const</span> ruta = path.<span class="code-method">join</span>(process.<span class="code-method">cwd</span>(), <span class="code-string">'configuracion.txt'</span>);\n<span class="code-comment">// process.cwd() = carpeta raíz desde donde se ejecuta el servidor</span></code></pre>` },
      { nombre: "Buscar y reemplazar con RegExp", contenido: `<p class="mb-6">Una <strong>expresión regular</strong> (RegExp) es un patrón para buscar texto. Combinada con <code>.replace()</code>, permite modificar contenido dentro de un archivo:</p><pre class="bloque-codigo"><code><span class="code-keyword">const</span> contenido = fs.<span class="code-method">readFileSync</span>(ruta, <span class="code-string">'utf8'</span>);\n\n<span class="code-comment">// /g = reemplaza TODAS las coincidencias, no solo la primera</span>\n<span class="code-keyword">const</span> patron = <span class="code-string">/INACTIVO/g</span>;\n\n<span class="code-keyword">const</span> nuevoContenido = contenido.<span class="code-method">replace</span>(patron, <span class="code-string">'ACTIVO'</span>);\n\nfs.<span class="code-method">writeFileSync</span>(ruta, nuevoContenido, <span class="code-string">'utf8'</span>);</code></pre>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "Quieres reiniciar un archivo de log a cero, pero mantener la misma ruta configurada en tu servidor para que siga escribiendo ahí. ¿Qué usas?", opciones: ["fs.unlinkSync()", "fs.truncateSync(ruta, 0)", "fs.appendFileSync()", "fs.existsSync()"], respuestaCorrecta: 1, retroalimentacion: { correcta: "Exacto: truncateSync deja el archivo en 0 bytes sin eliminarlo, así la ruta configurada sigue siendo válida.", incorrecta: "Si usaras unlinkSync, el archivo dejaría de existir por completo y la ruta configurada fallaría al escribir. Necesitas algo que vacíe sin borrar." } }
  },

  // === FASE 4-6: Versión asíncrona con fs.promises ===
  {
    fase: 4, titulo: "Versión asíncrona con fs.promises", menuTitulo: "fs.promises",
    capas: [
      { nombre: "¿Por qué preferir la versión asíncrona?", contenido: `<p class="mb-6">Las versiones "Sync" bloquean el único hilo de Node.js mientras leen el disco. En un servidor real, eso significa que <strong>nadie más puede ser atendido</strong> mientras dura la operación. Toca cada escenario:</p><div style="display:flex;justify-content:center;gap:1rem;margin-bottom:1rem;"><button id="btn-sync-servidor" class="motor-btn simbolo-inactivo" onclick="compararSyncServidor('sync')">readFileSync</button><button id="btn-async-servidor" class="motor-btn simbolo-inactivo" onclick="compararSyncServidor('async')">fs.promises</button></div><div id="sync-servidor-resultado" style="max-width:30rem;margin:0 auto;min-height:8rem;"></div>` },
      { nombre: "La misma lógica, dos sintaxis", contenido: `<p class="mb-6">Toca cada versión para comparar:</p><div style="display:flex;justify-content:center;gap:1rem;margin-bottom:1rem;"><button id="btn-codigo-sync" class="motor-btn simbolo-inactivo" onclick="compararCodigoFs('sync')">Síncrono</button><button id="btn-codigo-async" class="motor-btn simbolo-inactivo" onclick="compararCodigoFs('async')">fs.promises</button></div><pre class="bloque-codigo"><code id="fs-comparar-codigo" style="min-height:8rem;"><span class="code-comment">// Elige una opción arriba</span></code></pre>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "Un servidor usa fs.readFileSync() para leer un archivo de 50MB en una ruta muy visitada. Mientras se lee ese archivo, ¿qué pasa con otras peticiones que llegan al servidor?", opciones: ["Se procesan normalmente en paralelo", "Se quedan esperando hasta que termine la lectura", "Se rechazan automáticamente con error 503", "Node crea un hilo nuevo para atenderlas"], respuestaCorrecta: 1, retroalimentacion: { correcta: "Exacto: al ser síncrono y single-thread, el Event Loop queda completamente bloqueado hasta que termina de leer los 50MB. Todo lo demás espera en la cola.", incorrecta: "Recuerda: Node tiene un solo hilo para JavaScript. Una operación síncrona lo ocupa por completo mientras dura. ¿Qué le pasa a todo lo demás mientras tanto?" } }
  },
];
