export const tarjetas = [

  // === FASE 8-1: Cómo viaja un archivo por HTTP ===
  {
    fase: 8, titulo: "¿Cómo viaja un archivo por HTTP?", menuTitulo: "multipart/form-data",
    capas: [
      { nombre: "El problema de los formatos de texto", contenido: `<p class="mb-6">JSON y <code>application/x-www-form-urlencoded</code> solo transmiten <strong>texto</strong>. Si intentas meter los bytes crudos de una imagen ahí, se corrompen.</p><p class="mb-6"><strong>multipart/form-data</strong> resuelve esto: divide el cuerpo de la petición en partes separadas por un <code>boundary</code> (límite), permitiendo mezclar texto plano y archivos binarios en un mismo envío.</p><table><thead><tr><th>Formato</th><th>Puede llevar archivos</th></tr></thead><tbody><tr><td><code>application/json</code></td><td>No</td></tr><tr><td><code>application/x-www-form-urlencoded</code></td><td>No</td></tr><tr><td><code>multipart/form-data</code></td><td>Sí</td></tr></tbody></table>` },
      { nombre: "¿Por qué Express necesita un middleware extra?", contenido: `<p class="mb-6">Express, por diseño minimalista, <strong>no</strong> sabe procesar el flujo binario de <code>multipart/form-data</code>. Ni <code>express.json()</code> ni <code>express.urlencoded()</code> entienden dónde empieza y termina cada parte.</p><p><strong>express-fileupload</strong> es el middleware especializado: intercepta la petición, separa los archivos de los campos de texto, y te entrega los archivos listos en <code>req.files</code>.</p>` },
      { nombre: "Configuración completa", contenido: `<pre class="bloque-codigo"><code><span class="code-keyword">import</span> fileUpload <span class="code-keyword">from</span> <span class="code-string">'express-fileupload'</span>;\n\napp.<span class="code-method">use</span>(<span class="code-method">fileUpload</span>({\n  useTempFiles: <span class="code-keyword">true</span>,       <span class="code-comment">// no carga todo en RAM</span>\n  tempFileDir: <span class="code-string">'/tmp/'</span>,\n  limits: { fileSize: <span class="code-number">5</span> * <span class="code-number">1024</span> * <span class="code-number">1024</span> }  <span class="code-comment">// máx 5MB</span>\n}));\n\napp.<span class="code-method">post</span>(<span class="code-string">'/api/imagenes'</span>, (req, res) => {\n  <span class="code-keyword">if</span> (!req.files || Object.<span class="code-method">keys</span>(req.files).length === <span class="code-number">0</span>) {\n    <span class="code-keyword">return</span> res.<span class="code-method">status</span>(<span class="code-number">400</span>).<span class="code-method">json</span>({ error: <span class="code-string">'Sin archivo'</span> });\n  }\n\n  <span class="code-keyword">const</span> imagen = req.files.foto;\n  imagen.<span class="code-method">mv</span>(<span class="code-string">'./almacenamiento/'</span> + imagen.name, (err) => {\n    <span class="code-keyword">if</span> (err) <span class="code-keyword">return</span> res.<span class="code-method">status</span>(<span class="code-number">500</span>).<span class="code-method">json</span>({ error: err.message });\n    res.<span class="code-method">json</span>({ status: <span class="code-string">'success'</span> });\n  });\n});</code></pre>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "¿Por qué express.json() no sirve para procesar un archivo subido desde un formulario?", opciones: ["Porque express.json() solo funciona con GET", "Porque express.json() está diseñado para texto, no para el flujo binario de multipart/form-data", "Porque los archivos deben convertirse a JSON primero", "No hay ninguna diferencia real"], respuestaCorrecta: 1, retroalimentacion: { correcta: "Exacto: express.json() lee y parsea texto plano. No tiene la lógica para identificar los boundaries de un flujo multipart con archivos binarios.", incorrecta: "Piensa en qué tipo de datos procesa cada middleware: express.json() espera texto estructurado, no bytes binarios de un archivo." } }
  },

  // === FASE 8-2: Recibir el archivo en el servidor ===
  {
    fase: 8, titulo: "Recibir el archivo: req.files y .mv()", menuTitulo: "req.files y .mv()",
    capas: [
      { nombre: "El objeto req.files", contenido: `<p class="mb-6">Sus claves coinciden con el atributo <code>name</code> del campo <code>&lt;input type="file"&gt;</code> del formulario. Toca cada propiedad del archivo:</p><div style="display:flex;justify-content:center;gap:0.4rem;margin-bottom:1rem;flex-wrap:wrap;"><button class="motor-btn simbolo-inactivo" data-archivo="name" onclick="mostrarPropArchivo('name')">.name</button><button class="motor-btn simbolo-inactivo" data-archivo="data" onclick="mostrarPropArchivo('data')">.data</button><button class="motor-btn simbolo-inactivo" data-archivo="size" onclick="mostrarPropArchivo('size')">.size</button><button class="motor-btn simbolo-inactivo" data-archivo="mimetype" onclick="mostrarPropArchivo('mimetype')">.mimetype</button></div><div id="prop-archivo-desc" style="max-width:30rem;margin:0 auto;min-height:4rem;"></div>` },
      { nombre: "¿Por qué .mv() exige la ruta completa?", contenido: `<p class="mb-6"><code>.mv()</code> hace una escritura de bajo nivel: no "copia a una carpeta", escribe bytes en una ruta exacta. Por eso necesita el <strong>nombre del archivo incluido</strong>, no solo la carpeta:</p><table><thead><tr><th>Incorrecto</th><th>Correcto</th></tr></thead><tbody><tr><td><code>archivo.mv('/uploads/')</code></td><td><code>archivo.mv('/uploads/foto.jpg')</code></td></tr></tbody></table><div class="recuadro-resaltado mt-4">Ventaja: como tú eliges el nombre final, puedes renombrar el archivo antes de guardarlo (por ejemplo, agregando una marca de tiempo).</div>` },
      { nombre: "Ruta POST completa", contenido: `<pre class="bloque-codigo"><code>app.<span class="code-method">post</span>(<span class="code-string">'/upload'</span>, (req, res) => {\n  <span class="code-keyword">try</span> {\n    <span class="code-keyword">if</span> (!req.files || Object.<span class="code-method">keys</span>(req.files).length === <span class="code-number">0</span>) {\n      <span class="code-keyword">return</span> res.<span class="code-method">status</span>(<span class="code-number">400</span>).<span class="code-method">json</span>({ message: <span class="code-string">'Sin archivo'</span> });\n    }\n\n    <span class="code-keyword">const</span> archivo = req.files.archivo_usuario;\n    <span class="code-keyword">const</span> nombreUnico = <span class="code-string">\`\${Date.now()}-\${archivo.name}\`</span>;\n    <span class="code-keyword">const</span> ruta = path.<span class="code-method">join</span>(process.<span class="code-method">cwd</span>(), <span class="code-string">'almacenamiento'</span>, nombreUnico);\n\n    archivo.<span class="code-method">mv</span>(ruta, (error) => {\n      <span class="code-keyword">if</span> (error) <span class="code-keyword">return</span> res.<span class="code-method">status</span>(<span class="code-number">500</span>).<span class="code-method">json</span>({ message: error.message });\n      res.<span class="code-method">status</span>(<span class="code-number">200</span>).<span class="code-method">json</span>({ status: <span class="code-string">'success'</span> });\n    });\n  } <span class="code-keyword">catch</span> (error) {\n    res.<span class="code-method">status</span>(<span class="code-number">500</span>).<span class="code-method">json</span>({ message: <span class="code-string">'Error interno'</span> });\n  }\n});</code></pre>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "Ejecutas archivo.mv('/uploads/'), pasando solo la carpeta sin nombre de archivo. ¿Qué pasa?", opciones: ["Se guarda con el nombre original automáticamente", "Falla: el sistema de archivos no sabe qué nombre asignarle", "Se sobrescribe el último archivo subido", "Node crea un nombre aleatorio por defecto"], respuestaCorrecta: 1, retroalimentacion: { correcta: "Exacto: .mv() escribe bytes en una ruta exacta, no 'copia a una carpeta'. Sin el nombre del archivo en la ruta, la escritura falla.", incorrecta: ".mv() no adivina nombres. Necesita la ruta completa, incluyendo el nombre final del archivo." } }
  },

  // === FASE 8-3: Validaciones antes de guardar ===
  {
    fase: 8, titulo: "Validaciones antes de guardar", menuTitulo: "Validaciones",
    capas: [
      { nombre: "Las 3 validaciones", contenido: `<p class="mb-6">Toca cada una:</p><div style="display:flex;justify-content:center;gap:0.5rem;margin-bottom:1rem;flex-wrap:wrap;"><button class="motor-btn simbolo-inactivo" data-valfile="presencia" onclick="mostrarValidacionArchivo('presencia')">Presencia</button><button class="motor-btn simbolo-inactivo" data-valfile="tipo" onclick="mostrarValidacionArchivo('tipo')">Tipo (MIME)</button><button class="motor-btn simbolo-inactivo" data-valfile="tamano" onclick="mostrarValidacionArchivo('tamano')">Tamaño</button></div><div id="validacion-archivo-desc" style="max-width:30rem;margin:0 auto;min-height:5rem;"></div>` },
      { nombre: "413 Payload Too Large", contenido: `<p class="mb-6">Cuando el cuerpo de la petición excede el límite configurado, el servidor responde con <strong>413</strong>. Esto le dice al cliente exactamente qué pasó, sin que tenga que adivinar.</p><pre class="bloque-codigo"><code><span class="code-keyword">const</span> formatosPermitidos = [<span class="code-string">'image/jpeg'</span>, <span class="code-string">'image/png'</span>, <span class="code-string">'application/pdf'</span>];\n\n<span class="code-keyword">if</span> (!formatosPermitidos.<span class="code-method">includes</span>(archivo.mimetype)) {\n  <span class="code-keyword">return</span> res.<span class="code-method">status</span>(<span class="code-number">415</span>).<span class="code-method">json</span>({\n    message: <span class="code-string">'Formato no válido. Solo .jpg, .png y .pdf.'</span>\n  });\n}</code></pre>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "Un usuario intenta subir un archivo .exe a un endpoint que solo acepta imágenes. ¿Qué validación debe detectarlo?", opciones: ["Validación de presencia", "Validación de tipo (mimetype)", "Validación de tamaño", "Ninguna, Express lo bloquea solo"], respuestaCorrecta: 1, retroalimentacion: { correcta: "Exacto: comparas archivo.mimetype contra un arreglo de formatos permitidos. Un .exe no coincidirá con image/jpeg ni image/png.", incorrecta: "La presencia solo verifica que SE envió algo. El tamaño solo mide peso. Necesitas la validación que revisa QUÉ TIPO de archivo es." } }
  },

  // === FASE 8-4: Evitar sobrescribir archivos ===
  {
    fase: 8, titulo: "Evitar que se sobrescriban archivos", menuTitulo: "Nombres únicos",
    capas: [
      { nombre: "El problema de la colisión", contenido: `<p class="mb-6">Si guardas archivos con su nombre original, dos usuarios subiendo <code>foto.jpg</code> provocan que el segundo <strong>sobrescriba</strong> el primero. Resultado: pérdida de datos y una falla de privacidad (el usuario A ve la foto del usuario B).</p>` },
      { nombre: "Date.now() + path.extname()", contenido: `<p class="mb-6">Toca cada pieza:</p><div style="display:flex;justify-content:center;gap:1rem;margin-bottom:1rem;"><button id="btn-datenow" class="motor-btn simbolo-inactivo" onclick="mostrarPiezaRenombrado('datenow')">Date.now()</button><button id="btn-extname" class="motor-btn simbolo-inactivo" onclick="mostrarPiezaRenombrado('extname')">path.extname()</button></div><div id="pieza-renombrado-desc" style="max-width:30rem;margin:0 auto;min-height:5rem;"></div>` },
      { nombre: "Construir el nombre único", contenido: `<pre class="bloque-codigo"><code><span class="code-keyword">const</span> nombreOriginal = <span class="code-string">'foto.jpg'</span>;\n\n<span class="code-keyword">const</span> extension = path.<span class="code-method">extname</span>(nombreOriginal);  <span class="code-comment">// '.jpg'</span>\n<span class="code-keyword">const</span> timestamp = Date.<span class="code-method">now</span>();               <span class="code-comment">// 1785987654321</span>\n<span class="code-keyword">const</span> aleatorio = Math.<span class="code-method">round</span>(Math.<span class="code-method">random</span>() * <span class="code-number">1e9</span>);\n\n<span class="code-keyword">const</span> nombreUnico = <span class="code-string">\`archivo-\${timestamp}-\${aleatorio}\${extension}\`</span>;\n<span class="code-comment">// → 'archivo-1785987654321-482930293.jpg'</span></code></pre>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "¿Por qué se usa path.extname() al renombrar un archivo, en vez de solo pegar Date.now() al nombre completo?", opciones: ["Para que el nombre sea más corto", "Para conservar la extensión correcta y que el archivo siga siendo reconocido por su tipo", "path.extname() genera el timestamp", "No hay ninguna razón real"], respuestaCorrecta: 1, retroalimentacion: { correcta: "Exacto: extname() extrae solo la extensión (.jpg, .png). Así el archivo renombrado conserva su tipo correcto y sigue abriéndose normalmente.", incorrecta: "path.extname() no genera fechas. Su función es extraer la extensión para no perderla al renombrar el archivo." } }
  },

  // === FASE 8-5: Servir y eliminar archivos ===
  {
    fase: 8, titulo: "Servir y eliminar archivos", menuTitulo: "express.static y unlink",
    capas: [
      { nombre: "express.static(): hacer pública una carpeta", contenido: `<p class="mb-6">Por defecto, los archivos guardados <strong>no</strong> son accesibles por HTTP. <code>express.static()</code> convierte una carpeta del servidor en pública:</p><pre class="bloque-codigo"><code><span class="code-keyword">const</span> rutaPublica = path.<span class="code-method">join</span>(process.<span class="code-method">cwd</span>(), <span class="code-string">'almacenamiento'</span>);\n\napp.<span class="code-method">use</span>(express.<span class="code-method">static</span>(rutaPublica));\n\n<span class="code-comment">// Ahora http://localhost:3000/archivo-123.jpg funciona directo</span></code></pre>` },
      { nombre: "Eliminar con verificación previa", contenido: `<p class="mb-6"><code>fs.unlink()</code> borra el archivo. Pero si el archivo no existe, lanza <code>ENOENT</code>. Por eso se verifica antes con <code>fs.access()</code>:</p><pre class="bloque-codigo"><code><span class="code-keyword">import</span> fs <span class="code-keyword">from</span> <span class="code-string">'node:fs/promises'</span>;\n\n<span class="code-keyword">async function</span> <span class="code-method">eliminarArchivoSeguro</span>(ruta) {\n  <span class="code-keyword">try</span> {\n    <span class="code-comment">// 1. Verificar que existe (F_OK = comprobar presencia)</span>\n    <span class="code-keyword">await</span> fs.<span class="code-method">access</span>(ruta, fs.constants.F_OK);\n\n    <span class="code-comment">// 2. Solo si existe, eliminarlo</span>\n    <span class="code-keyword">await</span> fs.<span class="code-method">unlink</span>(ruta);\n    console.<span class="code-method">log</span>(<span class="code-string">'Eliminado con éxito'</span>);\n  } <span class="code-keyword">catch</span> (error) {\n    <span class="code-keyword">if</span> (error.code === <span class="code-string">'ENOENT'</span>) {\n      console.<span class="code-method">warn</span>(<span class="code-string">'El archivo ya no existía'</span>);\n    } <span class="code-keyword">else</span> {\n      <span class="code-keyword">throw</span> error;\n    }\n  }\n}</code></pre>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "¿Qué pasa si ejecutas fs.unlink() directamente sobre una ruta que no existe, sin verificar antes con fs.access()?", opciones: ["No pasa nada, unlink lo ignora silenciosamente", "Lanza una excepción ENOENT que hay que capturar", "El archivo se crea automáticamente", "Node lo convierte en una advertencia, no un error"], respuestaCorrecta: 1, retroalimentacion: { correcta: "Exacto: unlink() sobre una ruta inexistente lanza ENOENT. Por eso conviene verificar antes con fs.access(), para manejarlo de forma controlada.", incorrecta: "unlink() sí falla si el archivo no existe, con una excepción real (ENOENT) que interrumpe el flujo si no la capturas." } }
  },

  // === FASE 8-6: Limpiar nombres de archivo ===
  {
    fase: 8, titulo: "Limpiar nombres de archivo", menuTitulo: "Limpiar nombres",
    capas: [
      { nombre: "La expresión regular /\\s+/g", contenido: `<p class="mb-6">Los nombres de archivo pueden traer espacios o caracteres raros. Se limpian con <code>.replace()</code> y una expresión regular:</p><pre class="bloque-codigo"><code><span class="code-keyword">const</span> nombreLimpio = nombreBase.<span class="code-method">replace</span>(<span class="code-string">/\\s+/g</span>, <span class="code-string">'-'</span>).<span class="code-method">toLowerCase</span>();\n<span class="code-comment">// 'mi foto de perfil' → 'mi-foto-de-perfil'</span></code></pre><p class="mb-2">Toca cada parte de la expresión para entenderla:</p><div style="display:flex;justify-content:center;gap:0.4rem;margin-bottom:1rem;flex-wrap:wrap;"><button class="motor-btn simbolo-inactivo" data-regex="s" onclick="mostrarParteRegex('s')">\\s</button><button class="motor-btn simbolo-inactivo" data-regex="mas" onclick="mostrarParteRegex('mas')">+</button><button class="motor-btn simbolo-inactivo" data-regex="g" onclick="mostrarParteRegex('g')">g</button></div><div id="parte-regex-desc" style="max-width:28rem;margin:0 auto;min-height:3.5rem;"></div>` },
      { nombre: "existsSync vs access", contenido: `<p class="mb-6">Toca cada uno:</p><div style="display:flex;justify-content:center;gap:1rem;margin-bottom:1rem;"><button id="btn-existssync" class="motor-btn simbolo-inactivo" onclick="compararExistsAccess('sync')">fs.existsSync()</button><button id="btn-accessasync" class="motor-btn simbolo-inactivo" onclick="compararExistsAccess('async')">fs.access()</button></div><div id="exists-access-desc" style="max-width:30rem;margin:0 auto;min-height:5rem;"></div>` },
    ],
    ejercicio: { tipo: "opcion_multiple", pregunta: "En un servidor de producción con mucho tráfico, ¿por qué se prefiere fs.access() sobre fs.existsSync() para verificar un archivo?", opciones: ["fs.access() es más corto de escribir", "fs.existsSync() bloquea el único hilo de Node mientras consulta el disco; fs.access() no", "fs.existsSync() no existe en versiones nuevas de Node", "No hay ninguna diferencia de rendimiento"], respuestaCorrecta: 1, retroalimentacion: { correcta: "Exacto: existsSync es síncrono y congela el Event Loop mientras consulta el disco. En una ruta de alto tráfico, eso bloquea a todos los demás clientes.", incorrecta: "La diferencia real es de bloqueo: existsSync detiene todo el hilo, access permite que el servidor siga atendiendo otras peticiones mientras espera." } }
  },
];
